### ISSUE TITLE
[firebase_messaging] Ability to specify notification channel and use default notification sound

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1063]
Receiving notifications works but I'm not able to:

1. Hear any notification sound (Android)
2. See my pushed notifications in lock screen (Android)

I've also been reading up about notification channels that are available since android O and I've scourged the docs trying to look into how to set it up in flutter but I'm getting nowhere with that.

> Flutter Doctor

```sh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.0)
[✓] Connected device (1 available)
```

> pubspec.yml

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+1
  intl: ^0.15.7
  shared_preferences: ^0.5.2
  url_launcher: ^5.0.2
  flutter_webview_plugin: ^0.3.3
  google_sign_in: ^4.0.1+3
  firebase_messaging: ^4.0.0+2
  flutter_facebook_login: ^2.0.0
```

> main.dart
```dart
final firebaseMessaging = FirebaseMessaging();
firebaseMessaging.requestNotificationPermissions();
firebaseMessaging.subscribeToTopic("public");
```

> FCM API request
```curl
curl -X POST \
  https://fcm.googleapis.com/fcm/send \
  -H 'Authorization: key=<server-key>' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
    "notification": {
        "body": "this is a body",
        "title": "this is a title",
        "sound": "default",
        "click_action": "FLUTTER_NOTIFICATION_CLICK"
    },
    "priority": "high",
    "to": "/topics/public"
}'
```
