### ISSUE TITLE
[firebase_ ml_vision] Multiple init/dispose of camera gives blank screen but only on MotoZ2, not S9

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1154]
I'm writing a flutter app that uses camera with ml_vision to scan text (it's a 8 character hex value along with a barcode, but I read the text instead of the barcode since the print resolution of the barcode stickers is not good enough).  

Anyway, my issue is that after anywhere from a few to several (say 3 to 15) opens of the stateful page that uses the camera, I get a black screen preview of the camera.  BUT, this only happens on the MOTO Z2.  Never once on the Samsung S9.  I looked at logcat when I get the issue, and I see lots of camera errors.  I'll list those below.  I did confirm that dispose and init are getting called, and I used the boilerplate from the camera plugin.  Again, it works perfect on the S9, so I think I'm doing most stuff right.  

Is there any way to force/garbage collect camera instances?  I believe when the failure happens on the Moto Z2, the logging shows that the camera (or cameras) are actually still running in the background.  

## pubspec
Here are my pubspec dependencies (I'm unfortunately not able to run upgrade at the moment!  I get a crash that I have to figure out still on the build with firebase... )

```yaml
dependencies:
  #quick_actions: ^0.3.2+2
  url_launcher: ^5.1.2
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  auto_size_text: ^2.0.2+1
  image_picker: ^0.6.1+2
  path_provider: ^1.2.0
  video_player: ^0.10.1+6
  camera: ^0.5.3
  firebase_messaging: ^5.1.3
  flutter_sticky_header: "^0.4.0"
  firebase_core: ^0.2.5
  firebase_ml_vision: ^0.8.0
  flutter_camera_ml_vision: ^2.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter
```

## code
Here is some of the code for init/dispose:

```dart
  @override
  void initState() {
    super.initState();
    _portraitModeOnly();
    print("audacy camera: call init");
    _initializeCamera();
    _lastBarcode = null;
    _lastBarcodeTime = DateTime.now().millisecondsSinceEpoch;
    _dialogOpen = false;
  }

  @override
  void dispose() {
    super.dispose();
    _camera?.dispose();
    _isDetecting = false;
    _addDeviceSerialController?.dispose();
    _addDeviceNameController?.dispose();
    _clearBarcodeTimer?.cancel();
    _scannerDataTimeoutTimer?.cancel();
    _renameDeviceController?.dispose();
    _enableRotation();
  }

  void _initializeCamera() async {
    if (_camera != null) {
      _isDetecting = false;
      await _camera?.dispose();
    }

    CameraDescription description = await getCamera(CameraLensDirection.back);
    ImageRotation rotation = rotationIntToImageRotation(
      description.sensorOrientation,
    );

    _camera = CameraController(
        description,
        defaultTargetPlatform == TargetPlatform.iOS
            ? ResolutionPreset.low
            : ResolutionPreset.low // needed to allow moto z2 to work, medium fails
        //: ResolutionPreset.medium  // TODO: should we offer medium for phones that can use it?
        );

    await _camera.initialize();
    //_camera.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    //});


    await _camera.startImageStream((CameraImage image) {
      if (_isDetecting) return;

      _isDetecting = true;

      detect(image, widget.mlVision.textRecognizer().processImage, rotation)
          .then(
        (dynamic result) {
          setState(() {
            _scanResults = result;
          });
          _isDetecting = false;
        },
      ).catchError(
        (_) {
          _isDetecting = false;
        },
      );
    });
  }
```

## flutter doctor -v
```
[✓] Flutter (Channel unknown, v1.7.8+hotfix.5-pre.1, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.5-pre.1 at /Users/jeltoft/flutter/flutter
    • Framework revision d5c254ab3c (6 weeks ago), 2019-08-12 12:18:28 -0500
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jeltoft/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • macOS • macOS • darwin-x64     • Mac OS X 10.14.6 18G87
    • web   • web   • web-javascript • Google Chrome 77.0.3865.90 

• No issues found!
JustinMac:audacy-flutter jeltoft$ 
```
