### ISSUE TITLE
[Firebase messaging] Deprecated API usage or overrides warning

### ISSUE THREAD

**Issue by kunalpowar** [FirebaseExtended/flutterfire#122]
With `firebase_core: ^0.4.0+9` and  `firebase_messaging: ^5.1.5` as dependancies, Am getting the following warnings on build.

><flutter_path>/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.5/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java uses or overrides a deprecated API.

and 

><flutter_path>/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.5/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java uses unchecked or unsafe operations.

**Comment by fauzipadlaw** [comment]
i use this in pubspec.yml
```
firebase_messaging: 
    git:
      url: git://github.com/FirebaseExtended/flutterfire.git
      ref: 3ab5cc0d3767860d3c6d4c46aee84c7b31965172
      path: packages/firebase_messaging
```
it fixes `/FlutterFirebaseMessagingService.java uses or overrides a deprecated API.` but not `/FirebaseMessagingPlugin.java uses unchecked or unsafe operations.`

#136
