### ISSUE TITLE
Implemeting firestore throws the following error - fatal error: 'cloud_firestore/CloudFirestorePlugin.h' file not found

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1243]
This is what I getting after compiling

```
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    While building module 'Flutter' imported from /Users/jashan/Desktop/Programming/FlutterPgms/selfexplorer/ios/Runner/GeneratedPluginRegistrant.h:8:
    In file included from <module-includes>:1:
    In file included from /Users/jashan/Desktop/Programming/FlutterPgms/selfexplorer/ios/Flutter/Flutter.framework/Headers/Flutter.h:37:
    In file included from /Users/jashan/Desktop/Programming/FlutterPgms/selfexplorer/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    /Users/jashan/Desktop/Programming/FlutterPgms/selfexplorer/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:140:58: warning: this block declaration is not a prototype [-Wstrict-prototypes]
                          completionHandler:(nonnull void (^)())completionHandler;
                                                             ^
                                                              void
    1 warning generated.
    /Users/jashan/Desktop/Programming/FlutterPgms/selfexplorer/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'cloud_firestore/CloudFirestorePlugin.h' file not found
    #import <cloud_firestore/CloudFirestorePlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning and 1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.
```

NOTE : I have done all possible solutions mentioned in various forums, like pod install, clean up and install, flutter upgrade, dependency etc. still am stuck here.

AppDelegate.Swift file is as follows
```dart
import UIKit
import Flutter
//import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
   // FirebaseApp.configure()
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

This is the aprt of pubspec.yaml, I have tried cloud_firestore without version, and also with ^0.3.0 results are same.
```yml
name: selfexplorer
description: A new Flutter project.

dependencies:
  cloud_firestore: ^0.2.6
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```
