### ISSUE TITLE
[firebase_in_app_messaging] android build fails after adding firebase_in_app_messaging to project

### ISSUE THREAD

**Issue by kanhaic** [FirebaseExtended/flutterfire#132]
**Describe the bug**
```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:preReleaseBuild'.    
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[18.0.
  0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
                                                                        
  Dependency failing: com.google.firebase:firebase-messaging:18.0.0 -> com.google.firebase:firebase-iid@[18.0.0], but fire
  base-iid version was 19.0.0.                                          
                                                                        
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.                                                 
  -- Project 'app' depends on project 'firebase_in_app_messaging' which depends onto com.google.firebase:firebase-inappmes
  saging-display@18.0.2                                                 
  -- Project 'app' depends onto com.google.firebase:firebase-messaging@18.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-inappmessaging-display@18.0.2
  -- Project 'app' depends on project 'firebase_messaging' which depends onto com.google.firebase:firebase-messaging@18.0.
  0                                                                     
  -- Project 'app' depends onto com.google.firebase:firebase-inappmessaging@18.0.2
  -- Project 'app' depends on project 'firebase_core' which depends onto com.google.firebase:firebase-core@16.0.9
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@16.5.0
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@16.5.0
  -- Project 'app' depends on project 'firebase_analytics' which depends onto com.google.firebase:firebase-analytics@16.5.
  0                                                                     
  -- Project 'app' depends onto com.google.firebase:firebase-core@16.0.9
  -- Project 'app' depends onto com.google.firebase:firebase-iid@19.0.0 
                                                                        
  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.                                                     
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 13s                                                     
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        14.4s
Gradle task bundleRelease failed with exit code 1
```
**To Reproduce**
1. add firebase_in_app_messaging: ^0.0.1+3 to your pubspec.yaml

**Expected behavior**
It should build.

**Additional context**
```yaml
dependencies:
  flutter:
    sdk: flutter
  intl:
  package_info: ^0.4.0+6
  charts_flutter: ^0.8.0
  device_info: 0.4.0+2
  get_it: ^3.0.0+1
  provider: ^3.1.0
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^0.5.3+4
  google_maps_flutter: ^0.5.21
  amazon_cognito_identity_dart:
    git:
      url: git://github.com/kanhaic/amazon-cognito-identity-dart.git  
  firebase_core: ^0.4.0+9
  firebase_messaging: ^5.1.4
  firebase_analytics: ^5.0.1
  firebase_in_app_messaging: ^0.0.1+3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
```
