### ISSUE TITLE
[firebase_auth] ITMS-90809: Deprecated API Usage - UIWebView APIs

### ISSUE THREAD

**Issue by EBR12** [FirebaseExtended/flutterfire#1344]
After I upload my App to test Flight I have revived this message from App Store Connect‏ 👍 

We identified one or more issues with a recent delivery for your app....
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs 

After some googling I think the problem  is in firebase_auth plugin 

Here is a picture for dependencies in my project

![ikik](https://user-images.githubusercontent.com/44747309/68009219-6fa4b200-fc92-11e9-845b-549cf16d4d23.PNG)

And Here my flutter doctor

![okok](https://user-images.githubusercontent.com/44747309/68009307-b1cdf380-fc92-11e9-8c75-f0279d2836d0.PNG)

**Comment by iapicca** [comment]
Reporting information from this [issue](https://github.com/flutter/flutter/issues/44175)

<details>
  <summary>Description</summary>

```
I have 1 app in 2 variants (full and cut) that have different designs.
The difference between variants are:

assets
GoogleService-Info.plist
provision profiles
The 1st variant Apple releases without any warnings when the 2nd one returns warning "ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs ."

So, pods are the same, flutter packages are the same, also I've compare an XCode build logs - they are identical. In GoogleService-Info.plist are different only id/name fields.

Could you please advice what can I check to find the reason of the warning?
```

</details>

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale ru-UA)
    • Flutter version 1.9.1+hotfix.6 at /Users/admin/flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

</details>

<details>
  <summary>pubspec.yaml</summary>

```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.13.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_messaging: ^5.1.6
  flutter_xlider: ^2.5.2
  amazon_cognito_identity_dart: ^0.0.22
  built_value: ^6.6.0
  built_collection: ^4.2.2
  kiwi: ^0.1.0
  modal_progress_hud: ^0.1.3
  graphql_flutter: ^1.0.0
  shared_preferences: ^0.5.3+1
  youtube_player_flutter: 5.2.0+1
  pull_to_refresh: ^1.4.5
  carousel_slider: ^1.3.0
  outline_material_icons: ^0.1.1
  cached_network_image: ^1.0.0
  country_code_picker: ^1.1.7
  flare_flutter: ^1.5.5
  firebase_dynamic_links: ^0.5.0+1
  uni_links: ^0.2.0
  sentry: ^2.3.1
  firebase_crashlytics: ^0.1.0+3
  webview_flutter: ^0.3.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.0
  built_value_generator: ^6.6.0
  mockito: ^4.1.0
```

</details>
