### ISSUE TITLE
[cloud_functions]Migrate Legacy endpoints (pre-GA v0.1 and v1beta1) to V1

### ISSUE THREAD

**Issue by W2YAdmin** [FirebaseExtended/flutterfire#1379]
Hi Team,

I am using the cloud_function plugin in flutter to call my firebase cloud functions and it all works great. At the same time, yesterday I received one email from google stating that am using the Legacy endpoints (pre-GA v0.1 and v1beta1). 

The email mentioned few cloud functions which are still being called by these legacy endpoints and all of them are being called using this plugin.

According to the email, I am supposed to migrate the call from pre-GA v0.1 and v1beta1 to v1 endpoints as the Legacy one will expire on April 30 2020.

How can I upgrade to endpoint v1? Will that require changes on my end or in the plugin it self?

Thank a lot in advance!

Regards,
Rajdeep Barad

**Comment by iapicca** [comment]
Hi @W2YAdmin 
can you please provide your updated  `flutter doctor -v`
and your `pubspec.yaml` dependencies?
thank you

**Comment by W2YAdmin** [comment]
Sure! Here are the requested details:

Flutter doctor -v

```
[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows        
    [Version 10.0.18362.418], locale en-IN)
    • Flutter version 1.9.1+hotfix.5 at C:\flutter
    • Framework revision 1aedbb1835 (3 weeks ago), 2019-10-17 08:37:27    
      -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version  
    28.0.3)
    • Android SDK at C:\Users\Rajdeep\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native    
      profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\Rajdeep\AppData\Local\Programs\Microsoft VS Code    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

pubspec.yaml dependencies:

  ```
flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  google_sign_in: ^4.0.7 #^4.0.1+3
  firebase_core: ^0.4.0+9 #^0.4.0
  firebase_auth: ^0.14.0+5  # add dependency for firebase auth// 0.11.1
  firebase_analytics: ^5.0.2 #^3.0.1
  cloud_firestore: ^0.12.9+5 #^0.12.5
  firebase_storage: ^3.0.6
  cloud_functions: ^0.4.1+1 #^0.4.0+3
  firebase_messaging: ^5.1.6 #^5.0.4

  rxdart: any
  font_awesome_flutter: ^8.5.0 #^8.0.1
  shared_preferences: ^0.5.3+4
  provider: ^3.1.0 #2.0.0+1
  geolocator: ^5.1.4+1 #^5.0.0
  geoflutterfire: 2.0.3+5
  google_maps_flutter: ^0.5.21+7 #^0.5.11
  google_maps_webservice: ^0.0.15 #^0.0.14
  flutter_google_places: ^0.2.3
  firebase_remote_config: ^0.2.0+7 #^0.2.0+3
  flutter_datetime_picker: ^1.2.6 #^1.2.5

  dropdownfield: ^1.0.3 #0.0.2

  flutter_launcher_icons: ^0.7.3 #^0.7.2+1
  intro_views_flutter: ^2.8.0 #^2.6.0
  image_picker: ^0.6.1+4

  fit_kit: ^0.0.6 #^0.0.5
  syncfusion_flutter_charts: ^1.0.0-beta.3
  syncfusion_flutter_gauges: ^1.0.0-beta
  fancy_bottom_navigation: ^0.3.2
  webview_flutter: ^0.3.15+1
```

Please let me know if you need any more details.
