### ISSUE TITLE
[firebase_ml_vision] Flutter iOS app doesn't build after upgrading from firebase_ml_vision: ^0.6.0+2 to ^0.9.3+3

### ISSUE THREAD

**Issue by sebasbad** [FirebaseExtended/flutterfire#1429]
**Describe the bug**
Flutter iOS app doesn't build after upgrading from firebase_ml_vision: ^0.6.0+2 to ^0.9.3+3.

**To Reproduce**
Upgrade from firebase_ml_vision: ^0.6.0+2 to ^0.9.3+3 on the pubspec.yaml. Run flutter app from Android studio on an iOS 13.2.2 Simulator.

**Expected behavior**
The flutter app builds and runs fine on iOS.

**Additional context**
$ flutter doctor
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.12.1, on Mac OS X 10.15.1 19B88, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

pubspec.yaml

```yaml
name: ...
description: A Flutter application that ...

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: ...

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  image_picker: ^0.6.0+10
  #firebase_ml_vision: ^0.9.3+3 # works fine with Android (after fixing the play-services-vision vs firebase-ml-vision-image-label-model versions conflict)
  firebase_ml_vision: ^0.6.0+2 # iOS only works with this version :|‍
  firebase_admob: ^0.9.0+9
  firebase_crashlytics: ^0.1.1+2
  device_info: ^0.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app_icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```

Podfile:

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!
  
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVisionLabelModel'
  pod 'Firebase/MLVisionTextModel'

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

Android Studio build console log when using `firebase_ml_vision: ^0.9.3+3` for iOS:

```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...
Warning: Podfile is out of date
  This can cause a mismatched version of Flutter to be embedded in your app, which may result in App Store submission rejection or crashes.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/24641 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

Running Xcode build...
Xcode build done.                                            5,5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Any.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Any.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Any.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Any.pbobjc.h>
    1 warning generated.
    === BUILD TARGET image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Api.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Api.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Api.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Api.pbobjc.h>
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Api.pbobjc.m:18:10: warning: non-portable path to file '<protobuf/SourceContext.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/SourceContext.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/SourceContext.pbobjc.h>
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Api.pbobjc.m:19:10: warning: non-portable path to file '<protobuf/Type.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Type.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Type.pbobjc.h>
    3 warnings generated.
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Duration.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Duration.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Duration.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Duration.pbobjc.h>
    1 warning generated.
    === BUILD TARGET image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Empty.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Empty.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Empty.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Empty.pbobjc.h>
    1 warning generated.
    === BUILD TARGET image_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/FieldMask.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/FieldMask.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/FieldMask.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/FieldMask.pbobjc.h>
    1 warning generated.
    In file included from ~/.../ios/Pods/Protobuf/objectivec/GPBWellKnownTypes.m:35:
    ~/.../ios/Pods/Protobuf/objectivec/GPBWellKnownTypes.h:40:10: warning: non-portable path to file '<protobuf/Any.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Any.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Any.pbobjc.h>
    ~/.../ios/Pods/Protobuf/objectivec/GPBWellKnownTypes.h:41:10: warning: non-portable path to file '<protobuf/Duration.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Duration.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Duration.pbobjc.h>
    ~/.../ios/Pods/Protobuf/objectivec/GPBWellKnownTypes.h:42:10: warning: non-portable path to file '<protobuf/Timestamp.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Timestamp.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Timestamp.pbobjc.h>
    3 warnings generated.
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/SourceContext.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/SourceContext.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/SourceContext.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/SourceContext.pbobjc.h>
    1 warning generated.
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Struct.pbobjc.m:19:10: warning: non-portable path to file '<protobuf/Struct.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Struct.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Struct.pbobjc.h>
    1 warning generated.
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Timestamp.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Timestamp.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Timestamp.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Timestamp.pbobjc.h>
    1 warning generated.
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Type.pbobjc.m:19:10: warning: non-portable path to file '<protobuf/Type.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Type.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Type.pbobjc.h>
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Type.pbobjc.m:20:10: warning: non-portable path to file '<protobuf/Any.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Any.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Any.pbobjc.h>
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Type.pbobjc.m:21:10: warning: non-portable path to file '<protobuf/SourceContext.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/SourceContext.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/SourceContext.pbobjc.h>
    3 warnings generated.
    ~/.../ios/Pods/Protobuf/objectivec/google/protobuf/Wrappers.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Wrappers.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
     #import <Protobuf/Wrappers.pbobjc.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
             <protobuf/Wrappers.pbobjc.h>
    1 warning generated.
    ~/.../ios/Pods/GoogleUtilities/GoogleUtilities/Logger/GULLogger.m:167:37: warning: implicit conversion loses integer precision: 'const GULLoggerLevel' (aka 'const enum GULLoggerLevel') to 'int' [-Wshorten-64-to-32]
        asl_log(sGULLoggerClient, NULL, level, "%s", logMsg.UTF8String);
        ~~~~~~~                         ^~~~~
    1 warning generated.
    === BUILD TARGET firebase_admob OF PROJECT Pods WITH CONFIGURATION Debug ===
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:8:11: error: unknown type name 'FIRVisionImageLabeler'
    @property FIRVisionImageLabeler *labeler;
              ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:55:4: error: expected a type
    + (FIRVisionOnDeviceImageLabelerOptions *)parseOptions:(NSDictionary *)optionsData {
       ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:64:4: error: expected a type
    + (FIRVisionCloudImageLabelerOptions *)parseCloudOptions:(NSDictionary *)optionsData {
       ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:16:26: error: no visible @interface for 'FIRVision' declares the selector 'onDeviceImageLabelerWithOptions:'
          _labeler = [vision onDeviceImageLabelerWithOptions:[ImageLabeler parseOptions:options]];
                      ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:18:26: error: no visible @interface for 'FIRVision' declares the selector 'cloudImageLabelerWithOptions:'
          _labeler = [vision cloudImageLabelerWithOptions:[ImageLabeler parseCloudOptions:options]];
                      ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:33:30: error: unknown type name 'FIRVisionImageLabel'
            completion:^(NSArray<FIRVisionImageLabel *> *_Nullable labels, NSError *_Nullable error) {
                                 ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:42:16: error: use of undeclared identifier 'FIRVisionImageLabel'
              for (FIRVisionImageLabel *label in labels) {
                   ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:42:37: error: use of undeclared identifier 'label'; did you mean 'labels'?
              for (FIRVisionImageLabel *label in labels) {
                                        ^~~~~
                                        labels
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:33:64: note: 'labels' declared here
            completion:^(NSArray<FIRVisionImageLabel *> *_Nullable labels, NSError *_Nullable error) {
                                                                   ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:44:31: error: use of undeclared identifier 'label'
                  @"confidence" : label.confidence,
                                  ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:45:29: error: use of undeclared identifier 'label'
                  @"entityID" : label.entityID,
                                ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:46:25: error: use of undeclared identifier 'label'
                  @"text" : label.text,
                            ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:31:4: error: bad receiver type 'int *'
      [_labeler
       ^~~~~~~~
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:58:3: error: use of undeclared identifier 'FIRVisionOnDeviceImageLabelerOptions'
      FIRVisionOnDeviceImageLabelerOptions *options = [FIRVisionOnDeviceImageLabelerOptions new];
      ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:58:41: error: use of undeclared identifier 'options'; did you mean 'optind'?
      FIRVisionOnDeviceImageLabelerOptions *options = [FIRVisionOnDeviceImageLabelerOptions new];
                                            ^~~~~~~
                                            optind
    In module 'UIKit' imported from ~/.../ios/Pods/Target Support Files/firebase_ml_vision/firebase_ml_vision-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/unistd.h:512:12: note: 'optind' declared here
    extern int optind, opterr, optopt;
               ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:58:52: error: use of undeclared identifier 'FIRVisionOnDeviceImageLabelerOptions'
      FIRVisionOnDeviceImageLabelerOptions *options = [FIRVisionOnDeviceImageLabelerOptions new];
                                                       ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:59:3: error: use of undeclared identifier 'options'; did you mean 'optind'?
      options.confidenceThreshold = [conf floatValue];
      ^~~~~~~
      optind
    In module 'UIKit' imported from ~/.../ios/Pods/Target Support Files/firebase_ml_vision/firebase_ml_vision-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/unistd.h:512:12: note: 'optind' declared here
    extern int optind, opterr, optopt;
               ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:59:10: error: member reference base type 'int' is not a structure or union
      options.confidenceThreshold = [conf floatValue];
      ~~~~~~~^~~~~~~~~~~~~~~~~~~~
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:61:10: error: use of undeclared identifier 'options'; did you mean 'optind'?
      return options;
             ^~~~~~~
             optind
    In module 'UIKit' imported from ~/.../ios/Pods/Target Support Files/firebase_ml_vision/firebase_ml_vision-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/unistd.h:512:12: note: 'optind' declared here
    extern int optind, opterr, optopt;
               ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.9.3+3/ios/Classes/ImageLabeler.m:67:3: error: unknown type name 'FIRVisionCloudImageLabelerOptions'; did you mean 'FIRVisionCloudDetectorOptions'?
      FIRVisionCloudImageLabelerOptions *options = [FIRVisionCloudImageLabelerOptions new];
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      FIRVisionCloudDetectorOptions
    In module 'FirebaseMLVision' imported from ~/.../ios/Pods/Headers/Public/Firebase/Firebase.h:62:
    ~/.../ios/Pods/FirebaseMLVision/Frameworks/FirebaseMLVision.framework/Headers/FIRVisionCloudDetectorOptions.h:20:12: note: 'FIRVisionCloudDetectorOptions' declared here
    @interface FIRVisionCloudDetectorOptions : NSObject
               ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+7/ios/Classes/FLTMobileAd.m:98:79: warning: implicit conversion loses integer precision: 'FLTMobileAdStatus' to 'int' [-Wshorten-64-to-32]
      NSString *statusString = (NSString *)statusToString[[NSNumber numberWithInt:_status]];
                                                          ~                       ^~~~~~~
    1 warning generated.
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+7/ios/Classes/FLTRequestFactory.m:91:15: warning: 'birthday' is deprecated [-Wdeprecated-declarations]
          request.birthday =
                  ^
    In module 'GoogleMobileAds' imported from ~/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+7/ios/Classes/FLTRequestFactory.h:5:
    ~/.../ios/Pods/Google-Mobile-Ads-SDK/Frameworks/frameworks/GoogleMobileAds.framework/Headers/GADRequest.h:111:55: note: 'birthday' has been explicitly marked deprecated here
    @property(nonatomic, copy, nullable) NSDate *birthday GAD_DEPRECATED_ATTRIBUTE;
                                                          ^
    In module 'GoogleMobileAds' imported from ~/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+7/ios/Classes/FLTRequestFactory.h:5:
    ~/.../ios/Pods/Google-Mobile-Ads-SDK/Frameworks/frameworks/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:25:49: note: expanded from macro 'GAD_DEPRECATED_ATTRIBUTE'
    #define GAD_DEPRECATED_ATTRIBUTE __attribute__((deprecated))
                                                    ^
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+7/ios/Classes/FLTRequestFactory.m:106:19: warning: 'gender' is deprecated [-Wdeprecated-declarations]
              request.gender = genderValue;
                      ^
    In module 'GoogleMobileAds' imported from ~/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+7/ios/Classes/FLTRequestFactory.h:5:
    ~/.../ios/Pods/Google-Mobile-Ads-SDK/Frameworks/frameworks/GoogleMobileAds.framework/Headers/GADRequest.h:108:47: note: 'gender' has been explicitly marked deprecated here
    @property(nonatomic, assign) GADGender gender GAD_DEPRECATED_ATTRIBUTE;
                                                  ^
    In module 'GoogleMobileAds' imported from ~/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+7/ios/Classes/FLTRequestFactory.h:5:
    ~/.../ios/Pods/Google-Mobile-Ads-SDK/Frameworks/frameworks/GoogleMobileAds.framework/Headers/GoogleMobileAdsDefines.h:25:49: note: expanded from macro 'GAD_DEPRECATED_ATTRIBUTE'
    #define GAD_DEPRECATED_ATTRIBUTE __attribute__((deprecated))
                                                    ^
    2 warnings generated.
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+7/ios/Classes/FLTRewardedVideoAdWrapper.m:67:66: warning: implicit conversion loses integer precision: 'FLTRewardedVideoAdStatus' to 'int' [-Wshorten-64-to-32]
          (NSString *)rewardedStatusToString[[NSNumber numberWithInt:_rewardedStatus]];
                                             ~                       ^~~~~~~~~~~~~~~
    1 warning generated.

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
```
