### ISSUE TITLE
[firebase_auth][iOS] MissingPluginException - Channel master, v1.12.8-pre.14

### ISSUE THREAD

**Issue by syedz** [FirebaseExtended/flutterfire#1489]
Whenever I run my iPhone app I get the following error. However, the same code on Android runs just fine. It looks like iPhone doesn't want to connect to Firebase, but not completely sure. The build is just fine and it loads in the iPhone simulator, but nothing is being returned from Firestore, instead I get the following:

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startListeningAuthState on channel plugins.flutter.io/firebase_auth)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)                      
<asynchronous suspension>                                                                                          
#1      FirebaseAuth.onAuthStateChanged.<anonymous closure> (package:firebase_auth/src/firebase_auth.dart:47:25)   
#2      _runGuarded (dart:async/stream_controller.dart:807:24)                                                     
#3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)                  
#4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:820:19)                           
#5      _StreamImpl.listen (dart:async/stream_impl.dart:474:9)                                                     
#6      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:125:10)                                     
#7      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:93:16)                                  
#8      _ForwardingStream.listen (dart:async/stream_pipe.dart:88:12)                                               
#9      _StreamBuilderBaseState._subscribe (package:flutt<…>                                                       
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)                      
<asynchronous suspension>                                                                                          
#1      getTemporaryDirectory (package:path_provider/path_provider.dart:35:22)                                     
#2      DefaultCacheManager.getFilePath (package:flutter_cache_manager/src/cache_manager.dart:37:27)               
#3      new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:60:21)                          
#4      new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:34:29)                     
#5      new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:29:23)                       
#6      _HomeState.initState (package:BazaarOh/src/screens/home.dart:29:19)                                        
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4163:58)                           
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4009:5)                                 
#9      E<…>                                                                                                       
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)                      
<asynchronous suspension>                                                                                          
#1      invokeMethod (package:sqflite/src/sqflite_impl.dart:20:13)                                                 
#2      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:29:7)                       
#3      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite/src/factory_mixin.dart:24:35)
#4      wrapDatabaseException (package:sqflite/src/exception_impl.dart:8:34)                                       
#5      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25:7)              
#6      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite/src/factory_mixin.dart:24:7)                 
#7      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite/src/factory_mixin.dart:140:17)               
#8      getDatabasesPath (package:sqflite/sqflite.dart:169:54)                                                     
#9      Ca<…>                                                                                                      
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)                      
<asynchronous suspension>                                                                                          
#1      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:27)                   
#2      _HomeState.initialSetPageIndex (package:BazaarOh/src/screens/home.dart:38:49)                              
#3      _HomeState.initState (package:BazaarOh/src/screens/home.dart:34:5)                                         
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4163:58)                           
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4009:5)                                 
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)                                 
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)                                   
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4051:16)                       
#9      Element.rebuild (package:flutt<…>                                                                          
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method Query#addSnapshotListener on channel plugins.flutter.io/cloud_firestore)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)                      
<asynchronous suspension>                                                                                          
#1      Query.snapshots.<anonymous closure> (package:cloud_firestore/src/query.dart:61:37)                         
#2      _runGuarded (dart:async/stream_controller.dart:807:24)                                                     
#3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)                  
#4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:820:19)                           
#5      _StreamImpl.listen (dart:async/stream_impl.dart:474:9)                                                     
#6      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:125:10)                                     
#7      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:93:16)                                  
#8      _ForwardingStream.listen (dart:async/stream_pipe.dart:88:12)                                               
#9      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/asy<…>                                     
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method Query#addSnapshotListener on channel plugins.flutter.io/cloud_firestore)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)                      
<asynchronous suspension>                                                                                          
#1      Query.snapshots.<anonymous closure> (package:cloud_firestore/src/query.dart:61:37)                         
#2      _runGuarded (dart:async/stream_controller.dart:807:24)                                                     
#3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)                  
#4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:820:19)                           
#5      _StreamImpl.listen (dart:async/stream_impl.dart:474:9)                                                     
#6      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:125:10)                                     
#7      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:93:16)                                  
#8      _ForwardingStream.listen (dart:async/stream_pipe.dart:88:12)                                               
#9      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/asy<…>                                     
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging                 
to ensure proper integration.                                                                                      
Syncing files to device iPhone XS...  
```

Here is my pubspec.yaml:

```
environment:
    sdk: '>=2.2.2 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    algolia: ^0.1.6+1
    cupertino_icons: ^0.1.2
    carousel_pro: ^0.0.13
    cloud_firestore: 0.12.10+2
    firebase_auth: ^0.15.0+1
    firebase_core: 0.4.2
    firebase_messaging: 5.1.6
    firebase_storage: 3.0.6
    flutter_facebook_login: 3.0.0
    flutter_image_compress: 0.6.3
    flutter_slidable: 0.5.4
    font_awesome_flutter: 8.5.0
    geoflutterfire: ^2.0.3+5
    google_maps_flutter: 0.5.21+3
    google_sign_in: ^4.0.7
    image_cropper: ^1.0.2
    image_picker: 0.6.1+4
    cached_network_image: 2.0.0-rc
    intl: ^0.15.8
    keyboard_visibility: ^0.5.6
    liquid_pull_to_refresh: ^1.1.1
    flutter_cache_manager: ^1.1.3
    location: 2.3.4
    modal_progress_hud: ^0.1.3
    package_info: 0.4.0+6
    photo_view: ^0.4.2
    provider: ^3.0.0+1
    rxdart: ^0.22.2
    shared_preferences: 0.4.3
    url_launcher: 5.0.2


dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: '^0.7.0'
```

Here is my `flutter doctor -v`

```
[✓] Flutter (Channel master, v1.12.8-pre.14, on Mac OS X 10.14.6 18G1012, locale en-CA)
    • Flutter version 1.12.8-pre.14 at /flutter
    • Framework revision ae88f0190e (3 days ago), 2019-11-21 19:38:51 -0500
    • Engine revision 96fc607b8a
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zee/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone XS • F39E61CA-6A15-404C-A310-7C95B4438711 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-1 (simulator)

• No issues found!
```

Any help would be really appreciated. I can provide more details if needed.

**Comment by kroikie** [comment]
@syedz If you could provide any of the following it would help us track down this issue:

- test case that we could reproduce to track down this issue. 
- version of the plugin where this is happening
- is this an issue with flutter itself or the firebase_auth plugin

**Comment by altShiftDev** [comment]
I'm getting this too with the latest update, only on iOS builds, Android is working fine. It seems to be an issue with firebase_auth as I can't get past my app's login screen but flutter does load.

My plugin versions:
```
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.15.2
  firebase_database: ^3.1.1
  cloud_firestore: ^0.13.0+1
  firebase_messaging: ^6.0.9
```

**Comment by mpreddie** [comment]
We also have this same issue, using phone authentication. Updated to the latest version of Flutter (1.12.13+ hotfix.5), along with latest versions of firebase_core (^0.4.3+1) and firebase_auth (^0.15.2).

**Comment by syedz** [comment]
@kroikie All I have setup is an iOS app that won't connect to Firebase, Android will work just fine. My `pubspec.yaml` file is below, I've updated a few dependencies from the original post.

```
environment:
    sdk: '>=2.2.2 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    algolia: ^0.1.6+1
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.2
    carousel_pro: ^0.0.13
    cloud_firestore: ^0.12.5
    firebase_auth: ^0.15.2
    firebase_core: ^0.4.3+1
    firebase_messaging: ^6.0.9
    firebase_storage: 3.0.6
    flutter_facebook_login: 3.0.0
    flutter_image_compress: 0.6.3
    flutter_slidable: 0.5.4
    font_awesome_flutter: 8.5.0
    geoflutterfire: ^2.0.3+5
    google_maps_flutter: 0.5.21+3
    google_sign_in: ^4.0.7
    image_cropper: ^1.0.2
    image_picker: 0.6.1+4
    cached_network_image: 2.0.0-rc.1
    intl: ^0.15.8
    keyboard_visibility: ^0.5.6
    liquid_pull_to_refresh: ^1.1.1
    flutter_cache_manager: ^1.1.3
    location: 2.3.4
    modal_progress_hud: ^0.1.3
    package_info: 0.4.0+6
    photo_view: ^0.4.2
    provider: ^3.0.0+1
    rxdart: ^0.22.2
    shared_preferences: 0.4.3
    simple_moment: ^1.0.3
    url_launcher: 5.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: '^0.7.0'
```
