### ISSUE TITLE
[firebase_crashlytics] failed to download settings Error Domain=FABNetworkError Code=-6 "(null)"

### ISSUE THREAD

**Issue by JoshRice1** [FirebaseExtended/flutterfire#1592]
When I build the project and it starts I get the following two error messages and nothing is reported:

  ```bash
  Launching lib/main.dart on iPhone in debug mode...
    Automatically signing iOS for device deployment using specified development team in Xcode project: 63M82A35U9
    Xcode build done.                                           619.2s
    Checking for advertised Dart observatories...
    Configuring the default Firebase app...
    [Crashlytics] Version 3.14.0 (144)
    Configured the default Firebase app __FIRAPP_DEFAULT.
    [Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize
    [Fabric] failed to download settings Error Domain=FABNetworkError Code=-6 "(null)" UserInfo={retryLimit=1, NSErrorFailingURLStringKey=https://settings.crashlytics.com/spi/v2/platforms/ios/apps/com.reconyx.reconyx2dev/settings?build_version=1&display_version=0.1.0&instance=e0dc32f226809d7d8a0ef830766c3655bd24b0a9&source=1}
    Checking for available port on com.reconyx.reconyx2dev._dartobservatory._tcp.local
    Checking for authentication code for com.reconyx.reconyx2dev._dartobservatory._tcp.local
```

**To Reproduce**
1. Follow the steps for adding crashlytics
2.  Build the project

```yaml
pubspec.yaml dependencies:

    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    firebase_core: ^0.4.2+1  # add dependency for Firebase Core
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.2
    firebase_auth: ^0.15.1
    google_sign_in: ^4.0.7
    shared_preferences: ^0.5.3+4
    http: ^0.12.0+2
    rxdart: ^0.22.1
    cloud_firestore: ^0.12.11  
    flutter_auth_buttons: ^0.5.0
    firebase_storage: ^3.0.8
    provider: ^3.1.0
    extended_image: ^0.6.7
    cloud_functions: ^0.4.1+4
    barcode_scan: ^1.0.0
    auto_size_text: ^2.1.0
    esys_flutter_share: ^1.0.2
    flutter_multi_carousel: ^1.0.1
    firebase_crashlytics: ^0.1.1+2
```

**Expected behavior**
App builds and reports to crashlytics project

**Additional context**
N/A
