### ISSUE TITLE
[firebase_remote_config]: No visible @interface for 'FIRRemoteConfig' causing ios build to fail

### ISSUE THREAD

**Issue by CoderNamedHendrick** [FirebaseExtended/flutterfire#17141]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Remote Config

### Which platforms are affected?

iOS

### Description

The application fails to run on an iOS device. It fails with this error message in the console

```console
Could not build the precompiled application for the device.
ARC Semantic Issue (Xcode): No visible @interface for 'FIRRemoteConfig' declares the selector 'setCustomSignals:withCompletion:'
/Users/sebastineodeh/.pub-cache/hosted/pub.dev/firebase_remote_config-5.4.1/ios/firebase_remote_config/Sources/firebase_remote_config/FLTFirebaseRemoteConfigPlugin.m:120:16


Error launching application on Sebastine’s iPhone.

```

### Reproducing the issue

upgrading firebase_remote_config to 5.4.1

### Firebase Core version

3.12.0

### Flutter Version

3.24.5

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.5.4
Flutter SDK 3.24.5
app 1.3.1+88

dependencies:
- adaptive_theme 3.6.0 [flutter shared_preferences]
- aku_pay 1.0.3 [flutter adaptive_theme android_intent_plus cached_network_image clipboard convex_bottom_bar dio either_dart geolocator google_fonts flutter_cupertino_datetime_picker flutter_screenutil flutter_svg mobile_scanner path path_provider permission_handler modal_bottom_sheet pin_code_fields webview_flutter url_launcher dotted_border flutter_riverpod intl share_plus package_info_plus pdf printing shimmer file_picker image_picker qr_flutter uuid local_auth equatable easy_debounce ficonsax firebase_remote_config cupertino_icons]
- android_intent_plus 5.3.0 [flutter platform meta]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- camera 0.11.0+2 [camera_android_camerax camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle]
- carousel_slider 5.0.0 [flutter]
- clipboard 0.1.3 [flutter]
- collection 1.19.1
- convex_bottom_bar 3.2.0 [flutter]
- cupertino_icons 1.0.8
- dart_jsonwebtoken 2.17.0 [crypto pointycastle convert collection ed25519_edwards clock]
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- dotted_border 2.1.0 [flutter path_drawing]
- easy_debounce 2.0.3
- either_dart 1.0.0
- equatable 2.0.7 [collection meta]
- esc_pos_utils_plus 2.0.4 [flutter image html]
- ficonsax 0.0.3 [flutter]
- file_picker 9.0.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32 cross_file web]
- firebase_core 3.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.2.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 5.4.1 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- fk_user_agent 2.1.0 [flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bluetooth_printer 2.16.10 [flutter image flutter_bluetooth_printer_platform_interface plugin_platform_interface flutter_bluetooth_printer_macos]
- flutter_cupertino_datetime_picker 3.0.0 [flutter]
- flutter_dotenv 5.2.1 [flutter]
- flutter_local_notifications 18.0.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_riverpod 2.6.1 [collection flutter meta riverpod state_notifier]
- flutter_screenutil 5.9.3 [flutter]
- flutter_secure_storage 9.2.4 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_svg 2.0.16 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- fluttercontactpicker 5.0.0 [flutter contact_picker_platform_interface contact_picker_web]
- geolocator 13.0.2 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- http 1.3.0 [async http_parser meta web]
- image 4.5.3 [archive meta xml]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.20.2 [clock meta path]
- local_auth 2.3.0 [flutter local_auth_android local_auth_darwin local_auth_platform_interface local_auth_windows]
- mobile_scanner 5.2.3 [flutter flutter_web_plugins plugin_platform_interface web]
- modal_bottom_sheet 3.0.0 [flutter]
- open_store 0.5.0 [flutter url_launcher]
- package_info_plus 8.1.1 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- path 1.9.0
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- pdf 3.11.3 [archive barcode bidi crypto image meta path_parsing vector_math xml]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- pin_code_fields 8.0.1 [flutter]
- printing 5.13.4 [ffi flutter flutter_web_plugins http image meta pdf pdf_widget_wrapper plugin_platform_interface web]
- pub_semver 2.1.5 [collection meta]
- qr_flutter 4.1.0 [flutter qr]
- salesiq_mobilisten 6.3.3 [flutter]
- share_plus 10.1.4 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi web win32]
- shared_preferences 2.5.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 3.0.0 [flutter]
- smile_id 10.3.2 [flutter plugin_platform_interface]
- stack_trace 1.11.1 [path]
- story_page_view 1.0.0 [flutter freezed_annotation]
- timeago 3.7.0 [intl]
- turf 0.0.10 [geotypes turf_equality turf_pip rbush sweepline_intersections]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- webview_flutter 4.10.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- flutter_lints 5.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- mocktail 1.0.4 [collection matcher test_api]
- patrol 3.14.0 [boolean_selector equatable flutter flutter_test http json_annotation meta patrol_finders patrol_log shelf test_api]

dependency overrides:
- collection 1.19.1
- flutter_bluetooth_printer 2.16.10 [flutter image flutter_bluetooth_printer_platform_interface plugin_platform_interface flutter_bluetooth_printer_macos]
- geolocator_android 4.5.5 [flutter geolocator_platform_interface meta uuid]
- intl 0.20.2 [clock meta path]
- js 0.7.2
- qr_flutter 4.1.0 [flutter qr]
- web 1.1.0

transitive dependencies:
- _flutterfire_internals 1.3.52 [collection firebase_core firebase_core_platform_interface flutter meta]
- adaptive_number 1.0.0 [fixnum]
- archive 4.0.3 [crypto path posix]
- args 2.6.0
- async 2.11.0 [collection meta]
- barcode 2.2.8 [meta qr]
- benchmark 0.3.0 [meta args]
- bidi 2.0.12
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- camera_android_camerax 0.6.10 [async camera_platform_interface flutter meta stream_transform]
- camera_avfoundation 0.9.17+5 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.8.0 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.5 [camera_platform_interface flutter flutter_web_plugins stream_transform web]
- characters 1.3.0
- clock 1.1.1
- contact_picker_platform_interface 5.0.0 [flutter plugin_platform_interface]
- contact_picker_web 5.0.0 [flutter flutter_web_plugins js contact_picker_platform_interface]
- convert 3.1.2 [typed_data]
- cross_file 0.3.4+2 [meta web]
- crypto 3.0.6 [typed_data]
- csslib 1.0.2 [source_span]
- dart_sort_queue 0.0.2+3 [collection]
- dbus 0.7.10 [args ffi meta xml]
- dio_web_adapter 2.0.0 [dio http_parser meta web]
- dispose_scope 2.1.0 [meta]
- ed25519_edwards 0.3.1 [collection crypto convert adaptive_number]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.3
- file 7.0.1 [meta path]
- file_selector_linux 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+2 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.21.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.6.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.10.3 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config_platform_interface 1.5.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.8.1 [_flutterfire_internals firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.1
- flutter_bluetooth_printer_macos 1.3.0 [flutter flutter_bluetooth_printer_platform_interface plugin_platform_interface]
- flutter_bluetooth_printer_platform_interface 0.0.7 [flutter plugin_platform_interface]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_local_notifications_linux 5.0.0 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 8.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.23 [flutter]
- flutter_secure_storage_linux 1.2.2 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.1.2 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.2.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 3.1.2 [ffi flutter flutter_secure_storage_platform_interface path path_provider win32]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- freezed_annotation 1.1.0 [collection json_annotation meta]
- geolocator_apple 2.3.8+1 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.4 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 4.1.1 [flutter flutter_web_plugins geolocator_platform_interface web]
- geolocator_windows 0.2.3 [flutter geolocator_platform_interface]
- geotypes 0.0.2 [json_annotation]
- hive 2.2.3 [meta crypto]
- html 0.15.5 [csslib source_span]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.12+17 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.6 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.5 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.5 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 5.0.0
- local_auth_android 1.0.46 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_darwin 1.4.1 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.10 [flutter plugin_platform_interface]
- local_auth_windows 1.0.11 [flutter local_auth_platform_interface]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.15.0
- mime 2.0.0
- octo_image 2.1.0 [flutter]
- package_info_plus_platform_interface 3.0.1 [flutter meta plugin_platform_interface]
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.14 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- patrol_finders 2.7.0 [flutter flutter_test meta patrol_log]
- patrol_log 0.3.0 [dispose_scope equatable json_annotation]
- pdf_widget_wrapper 1.0.4 [flutter pdf]
- permission_handler_android 12.0.13 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+5 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- posix 6.0.1 [ffi meta path]
- qr 3.0.2 [meta]
- rbush 1.1.1
- riverpod 2.6.1 [collection meta stack_trace state_notifier]
- rxdart 0.28.0
- share_plus_platform_interface 5.0.2 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.4.6 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.2 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.1 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.0 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.4+6 [synchronized path meta]
- sqflite_darwin 2.4.1 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- sweepline_intersections 0.0.4 [turf dart_sort_queue collection benchmark]
- synchronized 3.3.0+3
- term_glyph 1.2.1
- test_api 0.7.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.10.0 [http path]
- turf_equality 0.1.0 [geotypes]
- turf_pip 0.0.2 [turf]
- typed_data 1.4.0 [collection]
- url_launcher_android 6.3.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.3 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.15 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.12
- vector_graphics_compiler 1.1.16 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 14.2.5
- webview_flutter_android 4.1.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.16.3 [flutter path webview_flutter_platform_interface]
- win32 5.10.1 [ffi]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]


```

</details>
