### ISSUE TITLE
[cloud_firestore]: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com"

### ISSUE THREAD

**Issue by neo-xy** [FirebaseExtended/flutterfire#17297]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Android

### Description

related to: [https://github.com/firebase/flutterfire/issues/17130](url)

Iissue both on real device and emulator when I'm signing in trough broswer (read: browser on top in stack) it's printing out the title error (see attached logs below)  untill webbrowser is closed and user is navigated back to app.
extra info:
-This error does not happen on pixel 5 API 30 (emulator).
-when running on 35 (emulator) if broswer window is not close after around 1min we get "Lost connection to device" error.

### Reproducing the issue

- run application on android 35
- sign in (application login should be set up trough browser)

### Firebase Core version

3.11.0

### Flutter Version

3.29.0 

### Relevant Log Output

```shell
W/ManagedChannelImpl(27213): [{0}] Failed to resolve name. status={1}
W/Firestore(27213): (25.1.2) [WatchStream]: (99829d2) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(27213):     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
W/Firestore(27213):     at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
W/Firestore(27213):     at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
W/Firestore(27213):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/Firestore(27213):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/Firestore(27213):     at java.lang.Thread.run(Thread.java:1012)
W/Firestore(27213): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(27213):     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
W/Firestore(27213):     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/Firestore(27213):     at java.net.InetAddress.getAllByName(InetAddress.java:1152)
W/Firestore(27213):     at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
W/Firestore(27213):     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
W/Firestore(27213):     ... 5 more
W/Firestore(27213): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(27213):     at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore(27213):     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
W/Firestore(27213):     at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
W/Firestore(27213):     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
W/Firestore(27213):     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
W/Firestore(27213):     ... 9 more
W/Firestore(27213): }.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  logger: ^2.5.0
  dio: ^5.8.0+1
  firebase_core: ^3.11.0
  firebase_analytics: ^11.4.2
  firebase_crashlytics: ^4.3.2
  firebase_messaging: ^15.2.2
  firebase_remote_config: ^5.4.0
  cloud_firestore: ^5.6.5
  flutter_local_notifications: ^18.0.1
  easy_localization: ^3.0.7+1
  shared_preferences: ^2.5.2
  flutter_riverpod: ^2.6.1
  auto_route: ^10.0.1
  http: ^1.3.0
  google_maps_flutter: ^2.10.1
  flutter_svg: ^2.0.17
  geolocator: ^13.0.2
  geolocator_platform_interface: ^4.2.4

```

</details>
