### ISSUE TITLE
[firebase_dynamic_links]: Receive crash report from Play Console

### ISSUE THREAD

**Issue by felixkwok2** [FirebaseExtended/flutterfire#17454]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

Android

### Description

Recently, we received a message from the Play Store stating: "Your app exceeds the Android vitals emerging bad behavior threshold." Upon investigation, we discovered a significant number of crashes occurring after updating our Flutter SDK to version 3.29.3. (origin 3.24.3)

These crashes appear to be related to Dynamic Links.

We understand that Dynamic Links will be deprecated in August 2025. However, we would like to continue using them until August, as some advertisements and social media posts still rely on these links.

### Reproducing the issue

We’ve been unable to reproduce the issue, but in the past 14 days, it has affected 1,370 users and resulted in 2,904 crash events.

### Firebase Core version

3.13.1

### Flutter Version

3.29.3

### Relevant Log Output

```shell
Exception java.lang.RuntimeException: Unable to resume activity {com.myapp.myapp/com.myapp.myapp.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.myapp.myapp. Make sure to call FirebaseApp.initializeApp(Context) first.
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:5229)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:5268)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:54)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2440)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8641)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1133)
Caused by java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.myapp.myapp. Make sure to call FirebaseApp.initializeApp(Context) first.
  at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:179)
  at com.google.firebase.dynamiclinks.FirebaseDynamicLinks.getInstance (FirebaseDynamicLinks.java:73)
  at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.getDynamicLinkInstance (FlutterFirebaseDynamicLinksPlugin.java:107)
  at io.flutter.plugins.firebase.dynamiclinks.FlutterFirebaseDynamicLinksPlugin.onNewIntent (FlutterFirebaseDynamicLinksPlugin.java:112)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent (FlutterEngineConnectionRegistry.java:799)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onNewIntent (FlutterEngineConnectionRegistry.java:437)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onNewIntent (FlutterActivityAndFragmentDelegate.java:941)
  at io.flutter.embedding.android.FlutterActivity.onNewIntent (FlutterActivity.java:927)
  at android.app.Activity.performNewIntent (Activity.java:8298)
  at android.app.Instrumentation.callActivityOnNewIntent (Instrumentation.java:1429)
  at android.app.Instrumentation.callActivityOnNewIntent (Instrumentation.java:1442)
  at android.app.ActivityThread.deliverNewIntents (ActivityThread.java:4243)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:5195)
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

dart SDK 3.7.2
Flutter SDK 3.29.3
my_app 1.0.0+10000

dependencies:
- advertising_id 2.7.1 [flutter]
- android_id 0.3.6 [flutter]
- app_links 3.5.1 [flutter plugin_platform_interface flutter_web_plugins gtk]
- app_tracking_transparency 2.0.6+1 [flutter]
- appcenter_sdk_flutter 0.5.1 [flutter meta plugin_platform_interface]
- auto_size_text 3.0.0 [flutter]
- badges 3.1.2 [flutter]
- battery_plus 6.2.1 [flutter flutter_web_plugins battery_plus_platform_interface meta upower web]
- bloc 8.1.4 [meta]
- build_runner 2.4.15 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web web_socket_channel yaml]
- built_value_generator 8.10.1 [analyzer build build_config built_collection built_value collection source_gen]
- carousel_slider 5.0.0 [flutter]
- collection 1.19.1
- convert 3.1.2 [typed_data]
- crypto 3.0.6 [typed_data]
- cupertino_icons 1.0.8
- cupertino_will_pop_scope 1.2.1 [flutter]
- dart_ping 9.0.1 [async collection]
- dart_ping_ios 4.0.2 [flutter dart_ping flutter_icmp_ping]
- dchs_flutter_beacon 0.6.4 [flutter plugin_platform_interface]
- device_info_plus 9.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- dotted_border 2.1.0 [flutter path_drawing]
- dotted_line 3.2.3 [flutter]
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- equatable 2.0.7 [collection meta]
- event_bus 2.0.1
- extended_nested_scroll_view 6.2.1 [flutter visibility_detector]
- facebook_app_events 0.19.7 [flutter]
- firebase_analytics 11.4.6 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.5.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_database 11.3.6 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_dynamic_links 6.1.6 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 15.2.6 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.10.1+6 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_performance_dio 0.7.1 [flutter dio firebase_performance]
- firebase_remote_config 5.4.4 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.6 [bloc flutter provider]
- flutter_blue_plus 1.35.5 [flutter flutter_blue_plus_android flutter_blue_plus_darwin flutter_blue_plus_linux flutter_blue_plus_platform_interface flutter_blue_plus_web]
- flutter_inappwebview 6.1.5 [flutter flutter_inappwebview_platform_interface flutter_inappwebview_android flutter_inappwebview_ios flutter_inappwebview_macos flutter_inappwebview_web flutter_inappwebview_windows]
- flutter_local_notifications 17.2.4 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_mime 0.0.2 [flutter freezed_annotation json_serializable]
- flutter_sound 9.28.0 [path_provider path synchronized logger flutter flutter_sound_platform_interface flutter_sound_web]
- flutter_svg 2.1.0 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_widget_from_html 0.16.0 [flutter flutter_widget_from_html_core fwfh_cached_network_image fwfh_chewie fwfh_just_audio fwfh_svg fwfh_url_launcher fwfh_webview html]
- geolocator 11.1.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get_ip_address 0.0.7 [http]
- google_fonts 6.2.1 [flutter http path_provider crypto]
- google_maps_flutter 2.12.2 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- graphic 2.5.1 [collection flutter vector_math path_drawing]
- growingio_tracker_flutter_plugin 2.1.3 [flutter plugin_platform_interface growingio_flutter_library]
- horizontal_data_table 4.3.1 [flutter provider]
- html 0.15.6 [csslib source_span]
- image_gallery_saver 2.0.3 [flutter aes256 flutter_image_gallery_saver]
- image_picker 1.1.2 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- in_app_review 2.0.10 [flutter in_app_review_platform_interface]
- intl 0.19.0 [clock meta path]
- jovial_svg 1.1.25 [xml collection args vector_math jovial_misc http meta flutter]
- lazy_data_table 0.3.1 [flutter]
- logger 2.5.0
- mime 1.0.6
- open_file_plus 3.4.1+1 [flutter ffi]
- open_settings_plus 0.4.0 [flutter plugin_platform_interface]
- overlay_support 2.1.0 [flutter async]
- package_info_plus 8.3.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- page_view_indicators 2.0.0 [flutter]
- path 1.9.1
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 11.4.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- photo_view 0.14.0 [flutter]
- pretty_dio_logger 1.4.0 [dio]
- pull_to_refresh 2.0.0 [flutter]
- reflectable 4.0.13 [analyzer build build_resolvers build_config build_runner build_runner_core dart_style glob logging package_config path pub_semver source_span]
- ribbon_widget 1.0.5 [flutter]
- scrollable_positioned_list 0.3.8 [flutter collection]
- sensors_plus 4.0.2 [flutter flutter_web_plugins sensors_plus_platform_interface]
- share_plus 7.2.2 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shared_preferences 2.5.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- skeletonizer 1.4.3 [flutter]
- smooth_page_indicator 1.2.1 [flutter]
- sprintf 7.0.0
- sticky_and_expandable_list 1.1.3 [flutter]
- timezone 0.9.4 [path]
- turf 0.0.10 [geotypes turf_equality turf_pip rbush sweepline_intersections]
- turf_pip 0.0.2 [turf]
- two_dimensional_scrollables 0.1.2 [flutter]
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- visibility_detector 0.4.0+2 [flutter]
- webview_flutter 4.13.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- whatsapp_stickers_exporter 1.0.0 [flutter plugin_platform_interface]
- youtube_player_flutter 9.1.1 [flutter flutter_inappwebview]

dev dependencies:
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_lints 3.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file leak_tracker leak_tracker_flutter_testing leak_tracker_testing matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- test 1.25.15 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

dependency overrides:
- image_gallery_saver 2.0.3 [flutter aes256 flutter_image_gallery_saver]

transitive dependencies:
- _fe_analyzer_shared 76.0.0 [meta]
- _flutterfire_internals 1.3.55 [collection firebase_core firebase_core_platform_interface flutter meta]
- _macros 0.3.3
- aes256 1.1.0 [crypto encrypt]
- analyzer 6.11.0 [_fe_analyzer_shared collection convert crypto glob macros meta package_config path pub_semver source_span watcher yaml]
- args 2.7.0
- asn1lib 1.6.4
- async 2.12.0 [collection meta]
- audio_session 0.1.25 [flutter flutter_web_plugins rxdart meta]
- battery_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- benchmark 0.3.0 [meta args]
- bluez 0.8.3 [dbus]
- boolean_selector 2.1.2 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.4 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.10.1 [built_collection collection fixnum meta]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.4.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- chewie 1.11.3 [cupertino_icons flutter provider video_player wakelock_plus]
- cli_config 0.2.0 [args yaml]
- clock 1.1.2
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- coverage 1.14.0 [args cli_config glob logging meta package_config path pubspec_parse source_maps stack_trace vm_service]
- cross_file 0.3.4+2 [meta web]
- csslib 1.0.2 [source_span]
- dart_sort_queue 0.0.2+3 [collection]
- dart_style 3.0.1 [analyzer args collection package_config path pub_semver source_span yaml]
- dbus 0.7.11 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.2 [flutter meta plugin_platform_interface]
- dio_web_adapter 2.1.1 [dio http_parser meta web]
- fake_async 1.3.2 [clock collection]
- ffi 2.1.4
- file 7.0.1 [meta path]
- file_selector_linux 0.9.3+2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+4 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 4.3.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+12 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_platform_interface 7.6.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.14.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.23.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.6 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.2.6+6 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.6+12 [collection firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins]
- firebase_dynamic_links_platform_interface 0.2.7+6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.6.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.10.6 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_performance_platform_interface 0.1.5+6 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.7+12 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins]
- firebase_remote_config_platform_interface 1.5.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.8.4 [_flutterfire_internals firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.1
- flutter_blue_plus_android 4.0.5 [flutter flutter_blue_plus_platform_interface]
- flutter_blue_plus_darwin 4.0.1 [flutter flutter_blue_plus_platform_interface]
- flutter_blue_plus_linux 3.0.2 [bluez flutter flutter_blue_plus_platform_interface rxdart]
- flutter_blue_plus_platform_interface 4.0.2 [flutter]
- flutter_blue_plus_web 3.0.1 [flutter flutter_blue_plus_platform_interface flutter_web_plugins web]
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_icmp_ping 3.1.3 [async flutter]
- flutter_image_gallery_saver 0.0.2 [flutter plugin_platform_interface]
- flutter_inappwebview_android 1.1.3 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_internal_annotations 1.2.0
- flutter_inappwebview_ios 1.1.2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_macos 1.1.2 [flutter flutter_inappwebview_platform_interface]
- flutter_inappwebview_platform_interface 1.3.0+1 [flutter flutter_inappwebview_internal_annotations plugin_platform_interface]
- flutter_inappwebview_web 1.1.2 [flutter flutter_web_plugins web flutter_inappwebview_platform_interface]
- flutter_inappwebview_windows 0.6.0 [flutter flutter_inappwebview_platform_interface]
- flutter_local_notifications_linux 4.0.1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.2.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.28 [flutter]
- flutter_sound_platform_interface 9.28.0 [flutter plugin_platform_interface logger]
- flutter_sound_web 9.28.0 [flutter_sound_platform_interface flutter logger flutter_web_plugins web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- flutter_widget_from_html_core 0.16.0 [csslib flutter html logging]
- freezed_annotation 2.4.4 [collection json_annotation meta]
- frontend_server_client 4.0.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- fwfh_cached_network_image 0.16.0 [cached_network_image flutter flutter_cache_manager flutter_widget_from_html_core]
- fwfh_chewie 0.16.0 [chewie flutter flutter_widget_from_html_core video_player]
- fwfh_just_audio 0.16.0 [flutter flutter_widget_from_html_core just_audio]
- fwfh_svg 0.16.0 [flutter flutter_svg flutter_widget_from_html_core]
- fwfh_url_launcher 0.16.0 [flutter flutter_widget_from_html_core url_launcher]
- fwfh_webview 0.15.4 [flutter flutter_widget_from_html_core logging web webview_flutter webview_flutter_android webview_flutter_wkwebview]
- geolocator_android 4.6.2 [flutter geolocator_platform_interface meta uuid]
- geolocator_apple 2.3.13 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.2.6 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 3.0.0 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.2.5 [flutter geolocator_platform_interface]
- geotypes 0.0.2 [json_annotation]
- glob 2.1.3 [async collection file path string_scanner]
- google_maps 8.1.1 [meta web]
- google_maps_flutter_android 2.16.1 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.15.2 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.11.1 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.12 [collection flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform web]
- graphs 2.3.2 [collection]
- growingio_flutter_library 2.1.3 [flutter collection plugin_platform_interface]
- gtk 2.1.0 [ffi flutter meta]
- http 1.4.0 [async http_parser meta web]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.12+23 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.6 [flutter flutter_web_plugins image_picker_platform_interface mime web]
- image_picker_ios 0.8.12+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+2 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+2 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- in_app_review_platform_interface 2.0.5 [flutter url_launcher plugin_platform_interface platform]
- io 1.0.5 [meta path string_scanner]
- jovial_misc 0.9.2 [async collection convert meta]
- js 0.7.2
- json_annotation 4.9.0 [meta]
- json_serializable 6.9.5 [analyzer async build build_config collection dart_style json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- just_audio 0.9.46 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- just_audio_platform_interface 4.5.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.16 [just_audio_platform_interface flutter flutter_web_plugins web synchronized]
- leak_tracker 10.0.8 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- logging 1.3.0
- macros 0.1.3-main.0 [_macros]
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- nested 1.0.0 [flutter]
- node_preamble 2.0.2
- octo_image 2.1.0 [flutter]
- package_config 2.2.0 [path]
- package_info_plus_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.17 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 12.1.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.7 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+5 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.3.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.1.0 [meta collection]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 5.0.3 [file path platform]
- provider 6.1.5 [collection flutter nested]
- pub_semver 2.2.0 [collection]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- rbush 1.1.1
- rxdart 0.28.0
- sanitize_html 2.1.0 [html meta]
- sensors_plus_platform_interface 1.2.0 [flutter logging meta plugin_platform_interface]
- share_plus_platform_interface 3.4.0 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences_android 2.4.10 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.3 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.3 [convert http_parser mime path shelf]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.0
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_map_stack_trace 2.1.2 [path source_maps stack_trace]
- source_maps 0.10.13 [source_span]
- source_span 1.10.1 [collection path term_glyph]
- sqflite 2.4.2 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.1 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.5 [synchronized path meta]
- sqflite_darwin 2.4.2 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- stack_trace 1.12.1 [path]
- stream_channel 2.1.4 [async]
- stream_transform 2.1.1
- string_scanner 1.4.1 [source_span]
- sweepline_intersections 0.0.4 [turf dart_sort_queue collection benchmark]
- sync_http 0.3.1
- synchronized 3.3.1
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.6.8 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- timing 1.0.2 [json_annotation]
- turf_equality 0.1.0 [geotypes]
- typed_data 1.4.0 [collection]
- upower 0.7.0 [dbus]
- url_launcher_android 6.3.16 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.18 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.17 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- video_player 2.9.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.8.7 [flutter video_player_platform_interface]
- video_player_avfoundation 2.7.1 [flutter video_player_platform_interface]
- video_player_platform_interface 6.3.0 [flutter plugin_platform_interface]
- video_player_web 2.3.5 [flutter flutter_web_plugins video_player_platform_interface web]
- vm_service 14.3.1
- wakelock_plus 1.3.2 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus web]
- wakelock_plus_platform_interface 1.2.3 [flutter plugin_platform_interface meta]
- watcher 1.1.1 [async path]
- web 1.1.1
- web_socket 1.0.1 [web]
- web_socket_channel 3.0.3 [async crypto stream_channel web web_socket]
- webdriver 3.0.4 [matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.2.1 [logging]
- webview_flutter_android 4.7.0 [flutter meta webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.13.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.22.0 [flutter meta path webview_flutter_platform_interface]
- win32 5.13.0 [ffi]
- win32_registry 1.1.5 [ffi win32]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>

### Additional context and comments

I have found similar issue on https://github.com/firebase/flutterfire/issues/10747 , and tried:
 - Ran `flutterfire configure` again
 - Confirmed that the `google-services.json` file is located in the `android/app` directory
 - Ensured that `await Firebase.initializeApp()` is executed before `runApp()`
 - Even comment out `FirebaseDynamicLinks.instance.getDynamicLink(uri` and hardcode the dynamic link as below

```
// final PendingDynamicLinkData? dynamicLinkData = await FirebaseDynamicLinks.instance.getDynamicLink(uri);
// if (dynamicLinkData != null) {
//   Log.d("[Deeplink] the uri is dynamic link -> ${dynamicLinkData.link}");
//   uri = dynamicLinkData.link;
// } else {
//   Log.d("[Deeplink][DynamicLink] null");
// }

/// Hardcode the dynamic link
if (uri.toString().startsWith("https://myapp.page.link/abc")) {
  uri = Uri.parse("https://www.myapp.com/abc");
} else if (uri.toString().startsWith("https://myapp.page.link/def")) {
  uri = Uri.parse("https://www.myapp.com/def");
} else {
  return null; // Not a supported dynamic link
}

... // action based on uri
```
