### ISSUE TITLE
[firebase_auth]: iOS Sign-In-with-Apple signInWithCredential throws "invalid-credential"

### ISSUE THREAD

**Issue by katsuhiro-ito** [FirebaseExtended/flutterfire#17466]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

firebase_auth: 5.6.0

When calling `signInWithCredential` or `linkWithCredential` on iOS, the following exception is thrown: 
```
[firebase_auth/invalid-credential] The supplied auth credential is malformed, has expired or is not currently supported.
```

The following message will also appear with it:
```
Support for an auth provider with identifier 'apple.com' is not implemented.
```

An exception is thrown, but the user is successfully registered with Firebase.
So I don't see any problem with the required settings for Sign-In-with-Apple.
However, anonymous accounts cannot be converted to permanent accounts.

This problem does not occur on Android.

If `signInWithProvider` or `linkWithProvider` is used instead, this problem does not occur.
However, it does not fit my requirements because the authentication is performed again if the account already exists.

Other issues (https://github.com/firebase/flutterfire/issues/12944) say it has been fixed, but I still reproduce it in my environment.

### Reproducing the issue

```dart
Future<void> signInWithApple() async {
  final UserCredential userCredential = await FirebaseAuth.instance
      .signInWithProvider(AppleAuthProvider());
  final AuthCredential? authCredential = userCredential.credential;
  if (authCredential == null) {
    throw Exception('No credential received.');
  }
  final User? user = FirebaseAuth.instance.currentUser;
  if (user == null) {
    await FirebaseAuth.instance.signInWithCredential(authCredential);
    return;
  }
  try {
    await user.linkWithCredential(authCredential);
  } on FirebaseAuthException catch (e) {
    switch (e.code) {
      case 'credential-already-in-use':
      case 'email-already-in-use':
        await FirebaseAuth.instance.signInWithCredential(authCredential);
        break;
      case 'provider-already-linked':
        break;
      default:
        rethrow;
    }
  }
}
```

### Firebase Core version

3.14.0

### Flutter Version

3.32.5

### Relevant Log Output

```shell
[firebase_auth/invalid-credential] The supplied auth credential is malformed, has expired or is not currently supported.
#0      FirebaseAuthHostApi.signInWithCredential (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1103:7)
<asynchronous suspension>
#1      MethodChannelFirebaseAuth.signInWithCredential (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:305:22)

Support for an auth provider with identifier 'apple.com' is not implemented.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.8.1
Flutter SDK 3.32.5

dependencies:
- app_settings 6.1.1 [flutter plugin_platform_interface]
- audio_service 0.18.18 [audio_service_platform_interface audio_service_web audio_session rxdart flutter_cache_manager clock js flutter flutter_web_plugins]
- cached_network_image 3.4.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- change_case 2.2.0 [meta]
- collection 1.19.1
- crypto 3.0.6 [typed_data]
- dio 5.8.0+1 [async collection http_parser meta path dio_web_adapter]
- drift 2.27.0 [async convert collection meta stream_channel sqlite3 path stack_trace web]
- drift_flutter 0.2.4 [drift flutter meta path path_provider sqlite3 sqlite3_flutter_libs]
- expand_widget 3.1.1 [flutter]
- firebase_analytics 11.5.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.6.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.14.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.3.7 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.2.7 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 5.4.5 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_hooks 0.21.2 [flutter]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_launcher_icons 0.14.4 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_local_notifications 19.3.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_windows flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_loggy 2.0.3+1 [flutter loggy]
- flutter_loggy_dio 3.1.0 [loggy dio]
- flutter_riverpod 2.6.1 [collection flutter meta riverpod state_notifier]
- flutter_svg 2.2.0 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- freezed_annotation 3.0.0 [collection json_annotation meta]
- go_router 15.2.4 [collection flutter flutter_web_plugins logging meta]
- google_sign_in 6.3.0 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hooks_riverpod 2.6.1 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- infinite_scroll_pagination 5.1.0 [flutter flutter_staggered_grid_view sliver_tools collection meta]
- intl 0.20.2 [clock meta path]
- json_annotation 4.9.0 [meta]
- just_audio 0.10.4 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter synchronized]
- loggy 2.0.3 [stack_trace]
- lottie 3.3.1 [archive flutter http path vector_math]
- mockito 5.4.6 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- package_info_plus 8.3.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- path_provider 2.1.5 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 12.0.0+1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- retrofit 4.5.0 [dio meta]
- riverpod_annotation 2.6.1 [meta riverpod]
- rxdart 0.28.0
- scroll_to_index 3.0.1 [flutter]
- settings_ui 2.0.2 [flutter]
- shared_preferences 2.5.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 7.0.1 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- synchronized 3.4.0
- url_launcher 6.3.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 4.13.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- build_runner 2.4.15 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web web_socket_channel yaml]
- custom_lint 0.7.5 [analyzer analyzer_plugin args async ci cli_util collection custom_lint_core freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]
- drift_dev 2.27.0 [charcode collection recase meta path json_annotation stream_transform args logging cli_util yaml io drift sqlite3 sqlparser analyzer source_span package_config pub_semver build build_resolvers build_config dart_style source_gen string_scanner]
- flutter_flavorizr 2.4.1 [flutter archive args checked_yaml collection image io json_annotation mason_logger sprintf xml yaml]
- flutter_gen_runner 5.10.0 [flutter_gen_core build collection crypto glob path yaml]
- flutter_lints 6.0.0 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- freezed 3.0.6 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- go_router_builder 3.0.1 [analyzer async build build_config collection meta path source_gen source_helper]
- json_serializable 6.9.5 [analyzer async build build_config collection dart_style json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- retrofit_generator 9.3.0 [analyzer build built_collection code_builder dart_style dio protobuf source_gen retrofit]
- riverpod_generator 2.6.5 [analyzer build build_config collection crypto meta path riverpod_analyzer_utils riverpod_annotation source_gen]
- riverpod_lint 2.6.5 [analyzer analyzer_plugin collection custom_lint_builder meta path riverpod riverpod_analyzer_utils source_span yaml]

transitive dependencies:
- _fe_analyzer_shared 82.0.0 [meta]
- _flutterfire_internals 1.3.56 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 7.4.5 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.13.1 [analyzer collection dart_style pub_semver yaml path]
- archive 4.0.7 [crypto path posix]
- args 2.7.0
- async 2.13.0 [collection meta]
- audio_service_platform_interface 0.1.3 [flutter plugin_platform_interface meta]
- audio_service_web 0.1.4 [audio_service_platform_interface rxdart web flutter flutter_web_plugins]
- audio_session 0.2.2 [flutter flutter_web_plugins rxdart meta]
- boolean_selector 2.1.2 [source_span string_scanner]
- build 2.4.2 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.2 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.4 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.4 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 8.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.10.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.1.1 [flutter flutter_cache_manager]
- cached_network_image_web 1.3.1 [cached_network_image_platform_interface flutter flutter_cache_manager web]
- characters 1.4.0
- charcode 1.4.0
- checked_yaml 2.0.4 [json_annotation source_span yaml]
- ci 0.1.0
- cli_util 0.4.2 [meta path]
- clock 1.1.2
- code_builder 4.10.1 [built_collection built_value collection matcher meta]
- color 3.0.0
- convert 3.1.2 [typed_data]
- custom_lint_builder 0.7.5 [analyzer analyzer_plugin collection custom_lint custom_lint_core custom_lint_visitor glob hotreloader meta package_config path pubspec_parse rxdart]
- custom_lint_core 0.7.5 [analyzer analyzer_plugin collection custom_lint_visitor glob matcher meta package_config path pubspec_parse source_span uuid yaml]
- custom_lint_visitor 1.0.0+7.4.5 [analyzer]
- dart_style 3.1.0 [analyzer args collection package_config path pub_semver source_span yaml]
- dartx 1.2.0 [characters collection crypto meta path time]
- dbus 0.7.11 [args ffi meta xml]
- dio_web_adapter 2.1.1 [dio http_parser meta web]
- fake_async 1.3.3 [clock collection]
- ffi 2.1.4
- file 7.0.1 [meta path]
- firebase_analytics_platform_interface 4.4.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.10+13 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_platform_interface 7.7.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.15.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.4.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.23.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.8.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.6.7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.10.7 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- firebase_remote_config_platform_interface 1.5.5 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.8.5 [_flutterfire_internals firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins]
- fixnum 1.1.1
- flutter_cache_manager 3.4.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_gen_core 5.10.0 [meta path yaml mime xml dartx color collection json_annotation glob dart_style archive args pub_semver vector_graphics_compiler image_size_getter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 6.0.0 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 9.1.0 [plugin_platform_interface]
- flutter_local_notifications_windows 1.0.0 [flutter ffi flutter_local_notifications_platform_interface meta timezone xml]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.3 [async collection file path string_scanner]
- google_identity_services_web 0.3.3+1 [meta web]
- google_sign_in_android 6.2.1 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.9.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.5.0 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+4 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.2 [collection]
- hashcodes 2.0.0
- hotreloader 4.3.0 [collection logging path stream_transform vm_service watcher]
- http 1.4.0 [async http_parser meta web]
- http_multi_server 3.2.2 [async]
- http_parser 4.1.2 [collection source_span string_scanner typed_data]
- image 4.5.4 [archive meta xml]
- image_size_getter 2.4.0 [collection hashcodes meta]
- io 1.0.5 [meta path string_scanner]
- js 0.7.2
- just_audio_platform_interface 4.5.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.16 [just_audio_platform_interface flutter flutter_web_plugins web synchronized]
- leak_tracker 10.0.9 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.9 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 6.0.0
- logging 1.3.0
- mason_logger 0.3.3 [ffi io win32]
- matcher 0.12.17 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.11.1 [collection]
- meta 1.16.0
- mime 2.0.0
- octo_image 2.1.0 [flutter]
- package_config 2.2.0 [path]
- package_info_plus_platform_interface 3.2.0 [flutter meta plugin_platform_interface]
- path 1.9.1
- path_parsing 1.1.0 [meta vector_math]
- path_provider_android 2.2.17 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.3.0 [ffi flutter path path_provider_platform_interface]
- permission_handler_android 13.0.1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.7 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+5 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.3.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.1.0 [meta collection]
- platform 3.1.6
- plugin_platform_interface 2.1.8 [meta]
- pool 1.5.1 [async stack_trace]
- posix 6.0.3 [ffi meta path]
- protobuf 4.1.0 [collection fixnum meta]
- pub_semver 2.2.0 [collection]
- pubspec_parse 1.5.0 [checked_yaml collection json_annotation pub_semver yaml]
- recase 4.1.0
- riverpod 2.6.1 [collection meta stack_trace state_notifier]
- riverpod_analyzer_utils 0.5.10 [analyzer collection crypto custom_lint_core freezed_annotation meta path source_span]
- shared_preferences_android 2.4.10 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.5.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.4.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.4.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.4.3 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.4.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.2 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 3.0.0 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 2.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 3.0.0 [flutter flutter_web_plugins sign_in_with_apple_platform_interface]
- sky_engine 0.0.0
- sliver_tools 0.2.12 [flutter]
- source_gen 2.0.0 [analyzer async build dart_style glob path pub_semver source_span yaml]
- source_helper 1.3.5 [analyzer collection source_gen]
- source_span 1.10.1 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.4.2 [flutter sqflite_android sqflite_darwin sqflite_platform_interface sqflite_common path]
- sqflite_android 2.4.1 [flutter sqflite_common path sqflite_platform_interface]
- sqflite_common 2.5.5 [synchronized path meta]
- sqflite_darwin 2.4.2 [flutter sqflite_platform_interface meta sqflite_common path]
- sqflite_platform_interface 2.4.0 [flutter platform sqflite_common plugin_platform_interface meta]
- sqlite3 2.7.6 [collection ffi meta path web typed_data]
- sqlite3_flutter_libs 0.5.34 [flutter]
- sqlparser 0.41.0 [meta collection source_span charcode]
- stack_trace 1.12.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.4 [async]
- stream_transform 2.1.1
- string_scanner 1.4.1 [source_span]
- term_glyph 1.2.2
- test_api 0.7.4 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- time 2.1.5 [clock]
- timezone 0.10.1 [http path]
- timing 1.0.2 [json_annotation]
- typed_data 1.4.0 [collection]
- url_launcher_android 6.3.16 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.3 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.2.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.2 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.4.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.4 [flutter url_launcher_platform_interface]
- uuid 4.5.1 [crypto sprintf meta fixnum]
- vector_graphics 1.1.19 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.13
- vector_graphics_compiler 1.1.17 [args meta path path_parsing vector_graphics_codec xml]
- vector_math 2.1.4
- vm_service 15.0.0
- watcher 1.1.2 [async path]
- web 1.1.1
- web_socket 1.0.1 [web]
- web_socket_channel 3.0.3 [async crypto stream_channel web web_socket]
- webview_flutter_android 4.7.0 [flutter meta webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.13.1 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.22.0 [flutter meta path webview_flutter_platform_interface]
- win32 5.14.0 [ffi]
- xdg_directories 1.1.0 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.3 [collection source_span string_scanner]

```

</details>
