### ISSUE TITLE
getting UNAUTHENTICATED when I called a cloud function

### ISSUE THREAD

**Issue by michealchow2324** [FirebaseExtended/flutterfire#1811]
i have deployed a simple cloud function like this:

```
exports.test = functions.https.onCall( async (data, context) => {
   
    console.log('test');
        
});
```

When I tried to call the function in my flutter app, it keeps saying UNAUTHENTICATED from the line of `error.message`.

```
final HttpsCallable callable = CloudFunctions.instance.getHttpsCallable(
  functionName: 'test',
);
dynamic resp = await callable.call().catchError((error){
  print('error :${error.code}');
  print('error :${error.message}');
  print('error :${error.details}');
});
```

Since i have made an authentication with Google Sign-in in the app already, May I know what is the cause of this issue?

**Comment by iapicca** [comment]
Hi @michealchow2324  
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose`
and your `pubspec.yaml`
Thank you

**Comment by TahaTesser** [comment]
Hi @michealchow2324 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by bdairy** [comment]
Hello Guys I am having the same issue.. here is my flutter doctor
I get this error,,, and the function never gets called

PlatformException(functionsError, Cloud function failed with exception., {code: UNAUTHENTICATED, details: null, message: UNAUTHENTICATED})

My Flutter doctor:
```
Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-JO)
    • Flutter version 1.12.13+hotfix.9 at /Users/mohammadbdair/development/tools/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at /Users/mohammadbdair/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc2
    • ANDROID_HOME = /Users/mohammadbdair/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```
and here is my pubspec.yaml

```
name: shahenty_mobile_driver
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  flutter_cupertino_localizations: ^1.0.1
  intl: ^0.16.0
  intl_translation: ^0.17.7
  scoped_model: ^1.0.1
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_analytics: ^5.0.11
  cloud_functions: ^0.4.1+6
  firebase_messaging: ^6.0.13
  flutter_app_badger: ^1.1.2
  rxdart: ^0.23.1
  timeago: ^2.0.26
  google_fonts: ^0.3.10
  flutter_form_builder: ^3.8.1
  convex_bottom_bar: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  intl: ^0.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - lang/en.json
   - lang/ar.json
   - assets/images/logo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages




```
