### ISSUE TITLE
[cloud_firestore] ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized

### ISSUE THREAD

**Issue by MrMagloire** [FirebaseExtended/flutterfire#1815]
### Steps to Reproduce
I created a function to save data on cloud_firestore, there is so much data that the application crashes from a moment, so to remedy it I create an Isolate in order to do the processing in another thread. But I have a problem with Isolate.

### Logs
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before runApp() has been called (for example, during plugin initialization), then you need to explicitly call the WidgetsFlutterBinding.ensureInitialized() first.
If you're running a test, you can call the TestWidgetsFlutterBinding.ensureInitialized() as the first line in your test's main() method to initialize the binding.)

**Though I have put WidgetsFlutterBinding.ensureInitialized(); in main as below**

**Comment by iapicca** [comment]
Hi @MrMagloire  
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and your `pubspec.yaml`
Thank you

**Comment by MrMagloire** [comment]
### futter doctor -v
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [version 10.0.17763.737],
    locale fr-CI)
    • Flutter version 1.12.13+hotfix.5 at C:\Users\MrMagloire\DevTools\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\MrMagloire\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\MrMagloire\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26)
      (emulator)

! Doctor found issues in 2 categories.
```

### My dependencies 
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+2
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  font_awesome_flutter: ^8.5.0
  cloud_firestore: ^0.13.0+1
  flutter_slidable: ^0.5.3
  sqflite: ^1.2.0
  shimmer: ^1.0.0
  location: ^2.3.5
  permission_handler: ^3.1.0
  flushbar: ^1.7.1+1
  screen: ^0.0.5
  animated_text_kit: ^1.3.1
  share: ^0.6.1+1
  country_code_picker: ^1.1.7
  random_string: ^1.1.0
  firebase_messaging: ^5.1.0
  timeago: ^2.0.17
  liquid_pull_to_refresh: ^1.1.1
  flutter_spinkit: ^4.0.0
  http: ^0.12.0+2
  image_picker_saver: ^0.3.0
  path_provider: ^1.1.2
  google_maps_flutter: ^0.5.19+2
  rxdart: ^0.22.0
  wave: ^0.0.8
  latlong: ^0.6.1
  percent_indicator: ^2.1.1
  dio: ^2.1.13
  sliding_up_panel: ^0.3.4
  rect_getter: ^0.0.1
  flutter_colorpicker: ^0.2.5
  rubber: ^0.3.2
  flutter_datetime_picker: ^1.2.5
  image_cropper: ^1.0.2
  firebase_storage: ^3.0.2
  admob_flutter: "^1.0.0-beta"
  overlay_support: ^1.0.0
  flutter_webview_plugin: ^0.3.7
  highlighter_coachmark: ^0.0.3
  intl: ^0.16.0
  flutter_local_notifications: ^0.8.4
  get_it: ^3.0.1
  uuid: ^2.0.2
  geolocator: ^5.1.4+1
  flutter_compass: ^0.3.3
  flutter_svg: ^0.14.2
  flutter_map: ^0.8.0
  diff_match_patch: ^0.3.0
  package_info: ^0.4.0+6
  url_launcher: ^5.1.6
  flare_flutter: ^1.6.2
  app_review: ^1.0.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  provider: ^4.0.1
```

### My log
```
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before runApp() has been called (for example, during plugin initialization), then you need to explicitly call the WidgetsFlutterBinding.ensureInitialized() first.
If you're running a test, you can call the TestWidgetsFlutterBinding.ensureInitialized() as the first line in your test's main() method to initialize the binding.)
```
