### ISSUE TITLE
[firebase_auth] compilation error uprgading from 0.15.3 to 0.15.4

### ISSUE THREAD

**Issue by tianhaoz95** [FirebaseExtended/flutterfire#1885]
**Describe the bug**
When I upgrade firebase_auth from v0.15.3+1 to v0.15.4, the following error appear in compilation:

```bash
Error: The method 'confirmPasswordReset' isn't defined for the class 'FirebaseAuthPlatform'.
```

details can be found in the check run https://github.com/tianhaoz95/iwfp/pull/265/checks?check_run_id=411215259#step:12:57

**To Reproduce**
1. compile a project with firebase_auth 0.15.3 or below
2. upgrade to 0.15.4
3. compile again
4. see the compilation error

**Expected behavior**
It should compile and execute without crashing.

**Additional context**
The compilation was executed in ubuntu-latest in GitHub Actions.

**Comment by 2ZeroSix** [comment]
there is an error in transitive dependency `confirmPasswordReset` is implemented in `firebase_auth_platform_interface` 1.1.3.
As hotfix you could run `flutter pub upgrade` or (if you don't want to upgrade other packages for some reason) find `firebase_auth_platform_interface` in `pubspec.lock` and change it like this:
```
  firebase_auth_platform_interface:
    dependency: transitive
    description:
      name: firebase_auth_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.5"
```
