### ISSUE TITLE
[cloud_firestore] The plugin cloud_firestore could not be built due to the issue above.

### ISSUE THREAD

**Issue by rignaneseleo** [FirebaseExtended/flutterfire#1896]
I've got this strange bug: if I use 
```yaml
cloud_firestore: ^0.13.0+1
flutter_downloader: ^1.4.0
```
then the project compiles and runs with this error: 

```bash
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

If I remove flutter_downloader (because I'm actually not using it) then I get:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/leo/Dev/Projects/MyGrandKids/my_grand_kids/build/app/intermediates/merged_manifests/debug/AndroidManifest.xml:72: AAPT: error: resource xml/provider_paths (aka boydpearce.my_grand_kids:xml/provider_paths) not found.

  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
Finished with error: The plugin cloud_firestore could not be built due to the issue above.
```

My flutter doctor:
```console
[✓] Flutter (Channel dev, v1.14.3, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!
```
 
My complete list of plugins:
```yaml
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #vcontrol-start
  mime_type: ^0.2.4

  #firestore
  firebase_storage: ^3.1.1
  firebase_core: ^0.4.3+2
  firebase_analytics: ^5.0.9
  firebase_messaging: ^6.0.9
  firebase_crashlytics: 0.1.2+4

  cloud_firestore: ^0.13.0+1
  flutter_downloader: ^1.4.0 #<----- I don't need this


  #download
  dio: ^3.0.8

  validators: 2.0.0+1

  encrypt: ^4.0.0
  random_string: ^2.0.1
  flutter_image_compress: ^0.6.5+1
  flutter_typeahead: ^1.7.0
  cached_network_image: 2.0.0-rc
  sqflite: ^1.1.7+3
  http: ^0.12.0+2
  path_provider: 1.5.0
  fluttertoast: ^3.1.3
  flutter_mailer: ^0.4.1+2
  shared_preferences: ^0.5.4+8
  flutter_launcher_icons: ^0.7.4
  file_picker: 1.4.3+2
  auto_size_text: ^2.1.0
  package_info: ^0.4.0+12
  share_extend: 1.1.0
  indexed_list_view: ^1.0.8
  page_indicator: ^0.3.0
  photo:
    path: ./my_flutter_photo
  photo_view: ^0.9.0
  synchronized: ^2.1.1
  contacts_service: ^0.3.10
  permission_handler: ^4.0.0
  flutter_fab_dialer: ^0.1.1
  #chewie is a video player
  chewie: 0.9.8+1
  font_awesome_flutter: 8.5.0
  flutter_cupertino_date_picker: ^1.0.12
  downloads_path_provider:
    git:
      url: git://github.com/jld3103/downloads_path_provider.git
  #vcontrol-end
```
