### ISSUE TITLE
[firebase_analytics] Crashing iOS app on startup

### ISSUE THREAD

**Issue by trqalothman** [FirebaseExtended/flutterfire#1900]
**Describe the bug**
When I add the `firebase_analytics: ^5.0.10` to my `pubspec.yaml` file iOS app will not run in debug mode, android runs fine.  If I remove it and add "pod 'Firebase/Analytics' " to my pod file, everything works fine, both android and iOS.  

All instructions specify that adding to pubspec should be enough for both OS.

**To Reproduce**
**pubspec:**
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^3.2.0
  intl: ^0.16.0
  admob_flutter: ^0.3.4
  geolocator: ^5.1.5
  url_launcher: ^5.4.1
  http: ^0.12.0+2
  flutter_sticky_header: ^0.4.0
  share: ^0.6.3+5
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  firebase_core: ^0.4.3+2
  # firebase_analytics: ^5.0.10
```

**podfile:**
```
platform :ios, '10.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'Firebase/Core'
  # pod 'Firebase/AdMob'
  # pod 'Firebase/Analytics'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMobileAdsMediationAppLovin'
  pod 'GoogleMobileAdsMediationUnity'
```

**Additional context**
**Debug console:**
```
Configuring the default Firebase app...
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001131ec6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000112790ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001131ec555 +[NSException raise:format:] + 197
	3   Runner                              0x000000010acf7b8c +[FIRApp addAppToAppDictionary:] + 284
	4   Runner                              0x000000010acf6d50 +[FIRApp configureWithName:options:] + 1312
	5   Runner                              0x000000010acf66ef +[FIRApp configureWithOptions:] + 143
	6   Runner                              0x000000010acf6645 +[FIRApp configure] + 165
	7   Runner                              0x000000010af376e6 -[FLTFirebaseAnalyticsPlugin init] + 214
	8   Runner            <…>
```

Please help me overcoming this problem.  Thanks.
