### ISSUE TITLE
Firebase Cloud Messaging - Callbacks bugs

### ISSUE THREAD

**Issue by royibernthal** [FirebaseExtended/flutterfire#1959]
I'm using the latest flutter and firebase_messaging.
I'm testing on Android Emulator on Pixel 3a Android Q.

I encountered 2 bugs. It's not unlikely they occur because I'm doing something wrong, no idea what though.

1. onMessage and onResume are called twice for each push notification with the exact same data and message id.
I only called configure once, and the push notification is only sent once.

2. When the app is closed and I'm clicking on the notification, no callback is called whatsoever (if I understood the docs correctly, I should expect onLaunch to be called).
I'm of course passing click_action: 'FLUTTER_NOTIFICATION_CLICK' in the push notification's data. onResume is called as expected when the notification is tapped while the app is in the background.

**Comment by vkammerer** [comment]
I can see the same behaviour, also testing on the Android Emulator with a Pixel 3a running Android Q

**Comment by vkammerer** [comment]
This seems to be a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1669

**Comment by iapicca** [comment]
Hi @royibernthal 
as @vkammerer  stated the first part of your issue appears to be a duplicate,
please follow up on the linked [issue](https://github.com/FirebaseExtended/flutterfire/issues/1959#issuecomment-590148391).

About the notification callback 
can you please provide your `flutter doctor -v` , 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by royibernthal** [comment]
Hi @iapicca 

Yeah, the first part indeed seems to be a duplicate as @vkammerer stated.

Here's my `pubspec.yaml:`

```
name: myappname
description: A new Flutter application.

version: 0.1.4+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  uuid: ^2.0.2
  cached_network_image: ^2.0.0-rc
  image_picker: ^0.6.3+4
  flutter_form_builder: ^3.5.5
  video_player: ^0.10.8+1
  pin_input_text_field: ^3.0.1
  flutter_icons: ^0.3.1
  quiver: ^2.1.3
  password_strength: ^0.1.2
  permission_handler: ^4.4.0
  dio: ^3.0.9
  event_bus: ^1.1.1
  shared_preferences: ^0.5.6+2
  flutter_pubnub: ^0.3.2
  flushbar: ^1.9.1
  firebase_messaging: ^6.0.12
  firebase_crashlytics: ^0.1.3
  get_it: ^4.0.0
  http_parser: ^3.1.3
  flutter_dotenv: ^2.1.0
  crypto: ^2.1.4
  package_info: ^0.4.0+14
  flutter_uploader: ^1.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  
flutter:
  
  uses-material-design: true

  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto/Roboto-Regular.ttf
         - asset: assets/fonts/Roboto/Roboto-RegularItalic.ttf
           style: italic
         - asset: assets/fonts/Roboto/Roboto-Bold.ttf
           weight: 700
         - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
           weight: 700
           style: italic
     - family: Mansalva
       fonts:
        - asset: assets/fonts/Mansalva/Mansalva-Regular.ttf


  assets:
    - dev.env
    - prod.env
    - assets/icon/icon.png
```

That's what I get when I run `flutter doctor -v`:

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at D:\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\royib\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\royib\AppData\Local\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

```

I have IntelliJ IDEA Community Edition installed separately from Android Studio but I'm using Android Studio which does have the Flutter and Dart plugins installed, so that warning can be ignored.
