### ISSUE TITLE
[firebase_admob] build error

### ISSUE THREAD

**Issue by ezero9** [FirebaseExtended/flutterfire#198]
I have added firebase_admob to yaml dependencies. and I am facing error when i try to build.
please check below logs..
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_slidable: ^0.5.3
  firebase_admob: ^0.9.0+7
  sqflite: any
  path: any
```
```
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                           15.5s
Configuring the default Firebase app...
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bcad8db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010b250ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bcad735 +[NSException raise:format:] + 197
	3   Runner                              0x0000000103bded7a +[FIRApp configure] + 138
	4   Runner                              0x0000000103dbc292 -[FLTFirebaseAdMobPlugin init] + 258
	5   Runner                              0x0000000103dbbffe +[FLTFirebaseAdMobPlugin registerWithRegistrar:] + 78
	6   Runner                              0x0000000103bda5e0 +[GeneratedPluginRegistrant registerWithRegistry:] + 112
	7   Runner                           <…>

```
