### ISSUE TITLE
[firebase_admob] iOS can't load multiple ads at once.

### ISSUE THREAD

**Issue by robindijkhof** [FirebaseExtended/flutterfire#2045]
**Describe the bug**
It seems ads do not show up when multiple are loaded at once.

**To Reproduce**

    class PageState extends State<Page> {

    BannerAd _bannerAd;
    bool _showAd = true;
    final InterstitialAd _interstitial = InterstitialAd(
      adUnitId: MyAdmob.getInterhersialEmailSend(),
      listener: (MobileAdEvent event) {},
    );

    @override
    void initState() {
      super.initState();
  
      _bannerAd = BannerAd(
        adUnitId: MyAdmob.getBannerId()
        size: AdSize.banner,
        listener: (MobileAdEvent event) {
          if (_showAd) {
            _bannerAd.show();
          } else {
            _bannerAd = null;
          }
        },
      );
  
      _bannerAd.load();
      _interstitial.load();
    }

Using this snippet does not display the banner. Removing `_interstitial.load()` does display the banner.

**Expected behavior**
It should be possible to load multiple ads

**Additional information**
Does work fine on Android

**Comment by ThrowJojo** [comment]
Just chiming in to post links to two other issues that are related to this:

https://github.com/FirebaseExtended/flutterfire/issues/1328
https://github.com/FirebaseExtended/flutterfire/issues/135

**Comment by iapicca** [comment]
Hi @robindijkhof 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by robindijkhof** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/robin/development/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/robin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by robindijkhof** [comment]
```
name: urenapp
description: Urenapp.
version: 5.1.2+154
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.


environment:
  sdk: ">=2.6.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  firebase_auth: ^0.15.3
  firebase_database: ^3.1.1
  firebase_admob: ^0.9.0+10
  firebase_crashlytics: ^0.1.2+4
  firebase_messaging: ^6.0.9
  google_sign_in: 4.1.1
  shared_preferences: ^0.5.6
  fluttertoast: ^3.1.3
  rxdart: 0.23.1
  url_launcher: ^5.4.1
  image: 2.1.4
  path_provider: ^1.5.1
  flutter_mailer: ^0.4.2
  json_annotation: ^2.0.0
  http: ^0.12.0+2
  i18n_extension: ^1.3.2
  device_info: ^0.4.1+4
  flutter_picker: ^1.1.0
  flutter_webview_plugin: ^0.3.10
  rate_my_app: ^0.4.0
  android_intent: ^0.3.4+8
  rect_getter: ^0.0.1
  progress_dialog: ^1.2.0
  flutter_list_drag_and_drop: ^0.1.6


  #flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path_ios: "base assets/icon_ios.png"
  image_path_android: "base assets/android_icon.png"
  adaptive_icon_background: "#2196f3"
  adaptive_icon_foreground: "base assets/android_foreground.png"


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  screenshots: ^2.1.1
  test: any
  flutter_launcher_icons: ^0.7.4


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/
  - packages/urenapp/assets/colorwheel.png

  fonts:
  - family:  CustomIcons
    fonts:
    - asset: fonts/CustomIcons.ttf
```
