### ISSUE TITLE
[Cloud Firestore] .snapshots swallows error

### ISSUE THREAD

**Issue by elvisun** [FirebaseExtended/flutterfire#2056]
**Describe the bug**
When the following query is rejected due to permission (and maybe other) reasons, the error is swallowed, and the stream is stuck at `ConnectionState.waiting`.

For example if the following query is rejected due to permission issue:
```
Firestore.instance
          .collection('users')
          .where('uid', isEqualTo: user.uid)
          .snapshots()
```

When I changed the code to the following, it was able to produce the error correctly
```
Firestore.instance
          .collection('users')
          .where('uid', isEqualTo: user.uid)
          .getDocuments()
          .asStream()
```

**To Reproduce**
See above example

**Expected behavior**
Stream should emit error instead of getting stuck at waiting state.

**Additional context**
Found this stackoverflow question about the same issue
https://stackoverflow.com/questions/59452829/firestore-collection-group-query-stream-is-not-updated/59454959#59454959

**Comment by iapicca** [comment]
Hi @elvisun 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by elvisun** [comment]
Thanks for taking a look!

flutter doctor -v:
```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.657], locale en-US)
    • Flutter version 1.12.13+hotfix.6 at D:\flutter
    • Framework revision 18cd7a3601 (3 months ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\1\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.3
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.3968.27

[!] Connected device
    ! No devices available
```

pubspec.yaml:
```
version: 1.0.4

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cloud_firestore: ^0.13.0+1
  cloud_functions: ^0.4.1+6
  cupertino_icons: ^0.1.2
  devicelocale: ^0.2.1
  firebase_auth: ^0.15.2
  firebase_storage: ^3.1.1
  flutter_auth_buttons: ^0.6.0
  logger: 0.8.2
  image_picker: ^0.6.3
  intl: ^0.16.1
  provider: ^4.0.2
  rxdart: ^0.23.1
  flutter_spinkit: ^4.1.1+1
  tuple: ^1.0.3
  font_awesome_flutter: ^8.5.0
  google_fonts: ^0.3.2
  flutter_staggered_grid_view: ^0.3.0
  pull_to_refresh: ^1.5.8
  flutter_cache_manager: ^1.1.3
  transparent_image: ^1.0.0
  flutter_cupertino_date_picker: ^1.0.12
  intl_phone_number_input: ^0.3.0
  pin_input_text_field: 3.0.1
  equatable: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  mockito: ^4.1.1
  test: ^1.9.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/antaa_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
```
