### ISSUE TITLE
[Firebase_Messaging] Missing plugin exception

### ISSUE THREAD

**Issue by geek2driod** [FirebaseExtended/flutterfire#2091]
Hello, I am trying to integrate firebase cloud messaging with my flutter project, I am using this version 6.0.9 . I am facing following issues

1 - Unable to find a way to receive notification when the app is killed or in background.
	=> To make it work on Android I wrote a messaging service in Android Native which receive notifications when the app is killed/backgorund/foreground
2 - Unable to handle the click listener of push notification in flutter. I know it will work in android native But I need to handle the click listener in flutter.
3 - On iOS I am using this method to request permission => `requestNotificationPermissions()` but getting this error 

```
VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method requestNotificationPermissions on channel plugins.flutter.io/firebase_messaging)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      FirebaseMessaging.requestNotificationPermissions (package:firebase_messaging/firebase_messaging.dart:87:21)
#2      NotificationHandler.requestNotification (package:talkshot/fcm/notification_handler.dart:43:32)
#3      main (package:talkshot/main.dart:75:23)
<asynchronous suspension>
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1502:12)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

Its humble request to all experts here, to please help me out to resolve these issues. Thank you

**Comment by iapicca** [comment]
Hi @geek2driod 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by geek2driod** [comment]
Hi @iapicca Thank you so much for your response.

`pubspec.yml`
```
name: talkshot
description: Talk & enjoy the game

version: 0.5+31

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  provider: ^4.0.1
  chopper: ^3.0.1+1
  cloud_firestore: 0.13.0+1
  firebase_core: 0.4.0+9
  get_it: 3.0.3
  flutter_screenutil: 0.6.0
  video_player: 0.10.2+5
  flutter_simple_video_player: 0.0.9
  firebase_auth: ^0.15.3+1
  flutter_cache_manager: 1.1.3
  firebase_storage: ^3.1.0
  shared_preferences: 0.5.4+5
  pusher_websocket_flutter: 0.1.1
  cached_network_image: 2.0.0-rc.1
  auto_size_text: 2.1.0
  flutter_widgets: 0.1.7+1
  contacts_service: ^0.3.10
  permission_handler: ^4.0.0
  image_picker: 0.6.2+2
  hive:
  hive_flutter:
  path_provider: ^1.5.1
  keyboard_actions: ^3.1.2
  camera:
  path:
  intl:
  storage_path: ^0.2.0
  firebase_database: ^3.1.1
  fluttertoast: ^3.1.3
  firebase_dynamic_links: 0.5.0+9
  share: 0.6.3+1
  cache_image: ^1.0.5
  extended_image: ^0.6.8
  flutter_advanced_networkimage: 0.6.3
  flutter_video_compress: 0.3.7+8
  transparent_image: any
  photo_manager: 0.4.7
  firebase_messaging:
  notification_permissions: 0.4.4
  rxdart: ^0.23.1
  firebase_crashlytics: ^0.1.2+5
  firebase_analytics: ^5.0.11
  flutter_svg: ^0.16.1
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.3
  build_runner:
  flutter_launcher_icons: "^0.7.0"


flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: gilroy
      fonts:
        - asset: assets/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/gilroy/Gilroy-ExtraBold.ttf
          weight: 900
```


Flutter doctor
```
/Users/bhatti/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15 19A583, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/bhatti/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bhatti/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/bhatti/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0
```

I have followed the official documentation and used the same code that is written in the example. My requirement is to show HeadsUpNotification in all cases i.e. when the app is background, when app is in foreground, & when the app is in killed state.

Please let me know if it's possible, without writing code in native. I have experience of writing code in Android native, I can handle the android part but I don't have zero experience of iOS native. Ideally everything should work in flutter but please let me know if it's not possible to do it in flutter. 

App link : https://play.google.com/store/apps/details?id=com.talkshotapp&hl=en_US

Looking forward to get response from you soon.
