### ISSUE TITLE
Google gms service causes app not to run

### ISSUE THREAD

**Issue by ram-koushik-reddy** [FirebaseExtended/flutterfire#2103]
### Bug Description
App runs as long as I don't add
**apply plugin: 'com.google.gms.google-services'**
in my **android/app/build.grade**

**Platform:** Flutter

### Things I have tried:

- tried versions of gms - 3.2.1 and 3.2.2.
- tried downgrading Flutter to its previous stable version.

### My pubspec.yaml file

 ```yaml
cupertino_icons: ^0.1.3
  intl_phone_number_input: ^0.3.0
  **firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  firebase_crashlytics: ^0.1.3
  firebase_performance: ^0.3.1+5
  firebase_messaging: ^6.0.9
  firebase_analytics: ^5.0.11**
  sqflite: ^1.2.1
  google_fonts: ^0.3.9
  **firebase_database: ^3.1.1**
  intl: ^0.16.1
  rxdart: ^0.23.1
  font_awesome_flutter: ^8.7.0
  streamqflite: ^1.0.0
  **cloud_firestore: ^0.13.3**
  fancy_on_boarding: ^1.4.0
  **cloud_functions: ^0.4.2**
  get_it: ^4.0.0
  grouped_buttons: ^1.0.4
  pin_code_fields: ^2.3.0+3
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  cached_network_image: ^2.0.0
```

### Expected Behaviour
The app needs to run on Android.

### Additional details:

- The present version of gms is 3.2.1.
- App runs on IOS but gives this problem when run on android.

**Flutter doctor:**
```console
[✓] Flutter (Channel master, v1.15.4-pre.241, on Mac OS X 10.15.3 19D76, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)

```
