### ISSUE TITLE
[FIXIED] Notifications sound doesn't work on IOS

### ISSUE THREAD

**Issue by Achhraf** [FirebaseExtended/flutterfire#2128]
**The solution** : in json use ( " ) not ( ' ), I had to change (sound: 'default') to (sound: "default") json work like that 

Notifications work fine on Android but in IOS I get notifications without sound 

My code :

**GETING TOKEN**

**firebase_messaging: ^6.0.12**

```
`if (Platform.isIOS) {
              await _fcm.requestNotificationPermissions(
                  const IosNotificationSettings(sound: true, badge: true, alert: true, provisional: false),
              );
              _fcm.onIosSettingsRegistered.listen((data) async {
                String fcmToken = await _fcm.getToken();
                if(fcmToken != null) {
                  await Firestore.instance.collection('users').document(res['getData'].toString()).collection('tokens').document(fcmToken).setData({
                    'token': fcmToken,
                    'createdAt': FieldValue.serverTimestamp(),
                    'platform': Platform.operatingSystem,
                    'platformVersion': Platform.operatingSystemVersion
                  });
                }
              });
            }`
```

The function json using nodejs (typeScript)

```
`const tokens = querySnapshot.docs.map(snap => snap.id);
		const payload: admin.messaging.MessagingPayload = {
			notification: {
				title: notification.title,
				body: notification.body,
				sound: 'default',
				click_action: 'FLUTTER_NOTIFICATION_CLICK'
			},
			data: {
				click_action: 'FLUTTER_NOTIFICATION_CLICK',
				sound: 'default',
				type: notification.type,
				iud: notification.iud
			}
		}
		return fcm.sendToDevice(tokens, payload);`

```

**FLUTTER DOCTOR**
```
`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G1012, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
[✓] Android Studio (version 3.5)
`
...
```

**Comment by iapicca** [comment]
Hi @Achhraf 
can you please provide your `flutter run --verbose` 
and your `pubspec.yaml`
Thank you

**Comment by Achhraf** [comment]
> 
> 
> Hi @Achhraf
> can you please provide your `flutter run --verbose`
> and your `pubspec.yaml`
> Thank you

Hi & thank you @iapicca 

My pubspec.yaml

```
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons:
  carousel_pro:
  http:
  shared_preferences:
  image_picker:
  provider: ^3.1.0
  toast:
  url_launcher:
  firebase_core: 0.4.4
  cloud_firestore: 0.13.4
  firebase_auth: 0.15.4
  firebase_storage: 3.0.5
  photo_view:
  timeago:
  firebase_messaging: 6.0.12
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: font
      fonts:
        - asset: assets/font.ttf
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/android.png"
  image_path_ios: "assets/icon/ios.png"
  adaptive_icon_background: "#fdee1f"

```

`flutter run --verbose` on runing now
