### ISSUE TITLE
[firebase_messaging] MediaNotification handlers broken after first received message

### ISSUE THREAD

**Issue by hw-dwalter** [FirebaseExtended/flutterfire#2154]
**Describe the bug**
Using flutter_media_notification to show media control notification. After receiving first firebase message, the handles for MediaNotification are not working.

**To Reproduce**
1. init firebase messaging
2. show MediaNotification
2.1 register callbacks for play/pause etc

**Sample Code**
Here is an minimal example code to demonstrate this:
```dart
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_media_notification/flutter_media_notification.dart';

class SplashScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => SplashState();
}

class SplashState extends State<SplashScreen> {
  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();

  @override
  void initState() {
    super.initState();

    MediaNotification.showNotification(
        title: 'Title', author: 'Song author', isPlaying: false);
    MediaNotification.setListener('play', () {
      print("play");
    });

    MediaNotification.setListener('pause', () {
      print("pause");
    });

    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");

      },
    );
  }
}
```

**Expected behavior**
While clicking play/pause button in the media notification the handlers are called as expected. After receiving first firebase message this is broken. Callbacks are not called again.

![image](https://user-images.githubusercontent.com/1303452/76336277-0bf05c80-62f6-11ea-8ee8-ac4aed34100e.png)

**Additional context**
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

Same behaviour with both media notification plugins:
https://pub.dev/packages/media_notification
https://pub.dev/packages/media_notification_control

Tested ob Android Emulator. Android Version 8.

**Comment by iapicca** [comment]
Hi @hw-dwalter 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml`
Thank you

**Comment by hw-dwalter** [comment]
flutter run --verbose:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /opt/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/dwalter/Android/Sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/dwalter/Android/Sdk/
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /opt/idea-IU-173.4548.28
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /opt/idea-IC-193.6494.35
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6494.35

[✓] Connected device (2 available)
    • VOG L29                   • 22X7N19329008040 • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 2 categories.
```

pubspec.yaml:
```yaml
name: appname
description: desc

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  url_launcher: 3.0.1
  media_notification:
  flutter_media_notification:
  dynamic_theme: ^1.0.1
  scoped_model:
  firebase_messaging:
  firebase_analytics:

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

flutter:
  assets:
    - images/back.jpg
    - images/avatar.jpg
    - images/artist.jpg
    - images/splash.png
    - images/logo.png
    - images/logo_white.png
    - images/kid.png
    - images/sad.png

  fonts:
      - family: Raleway
        fonts:
          - asset: fonts/Raleway-Regular.ttf
          - asset: fonts/Raleway-Italic.ttf
            style: italic
     

  uses-material-design: true
```
