### ISSUE TITLE
[flutterfire] Password less login and deep links not working reliably on iOS

### ISSUE THREAD

**Issue by dpedrinha** [FirebaseExtended/flutterfire#2199]
**Describe the bug**
I've a published app developed on Flutter with Firebase Deep links for password less login only for iOS. On Android I use Google Sign in which is working fine.

But on iOS it works on the emulator and on most devices (as I see new accounts every day) but I'm getting some complains from people that just can't finish the login process. The email link opens an intermediary page on the browser (it's kind of a confirmation screen with a button to proceed) that some times redirects to the App Store and some times to the app but nothing happens on the app and no errors are shown on the console.

On the Emulator, the email link redirects straight to the app and finishes the login with no problem.

This problem has been happening on various device models. And sometimes, even people who could once log in, can't any more after uninstalling the app and installing it again.

I can't reproduce it on my device or emulator.

So what kind of configuration could be causing this weird behavior?

I'm on flutter master channel and using these plugin versions:

```yaml
  firebase_core: 0.4.4
  firebase_auth: 0.15.0
  firebase_dynamic_links: ^0.5.0+9
  cloud_firestore: 0.13.4
  firebase_analytics: ^5.0.11
```

**To Reproduce**
I can't

**Expected behavior**
...

**Additional context**
...
