### ISSUE TITLE
[web] Browser showing "Because of firebase login web is currently not supported!"

### ISSUE THREAD

**Issue by Tonne-TM** [FirebaseExtended/flutterfire#2254]
I tried to use firbase auth + cloud_firestore in flutter web. On android it is working fine but in the browser it is showing the following:
![](https://i.gyazo.com/4d51a52140fcdd12063bfcb2028e22ae.png)

I am a bit confused because it said web is supported now for firebase auth.

My `pubspec.yaml` 
```yaml
version: 1.0.0+5

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  assets_audio_player: ^1.2.3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  flutter_reorderable_list: ^0.1.3
  percent_indicator: ^2.1.1+1
  url_launcher: ^5.4.2
  flutter_email_sender: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:


  uses-material-design: true


  assets:
    - assets/sounds/beep8.mp3

```

My `index.html`
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hangboard Timer</title>
</head>
<body>



    <!-- The core Firebase JS SDK is always required and must be listed first -->
    <script src="https://www.gstatic.com/firebasejs/7.13.1/firebase-app.js"></script>

    <!-- TODO: Add SDKs for Firebase products that you want to use
         https://firebase.google.com/docs/web/setup#available-libraries -->
    <script src="https://www.gstatic.com/firebasejs/7.13.1/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.13.1/firebase-firestore.js"></script>


    <script>
        // Your web app's Firebase configuration
        var firebaseConfig = {
            apiKey: ...
            ...
        };
        // Initialize Firebase
        firebase.initializeApp(firebaseConfig);
    </script>

    <script src="main.dart.js" type="application/javascript"></script>

</body>
</html>
```

Flutter Doctor:
```
[√] Flutter (Channel master, v1.16.4-pre.18, on Microsoft Windows [Version 10.0.18362.720], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[!] VS Code, 64-bit edition (version 1.41.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (3 available)

```
