### ISSUE TITLE
[firebase_remote_config] isDeveloperModeEnabled is deprecated

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#2302]
Seeing this compiler warning:
```
    /Users/anthony/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.3.0+3/ios/Classes/FirebaseRemoteConfigPlugin.m:52:
    65: warning: 'isDeveloperModeEnabled' is deprecated: This no longer needs to be set during development. Refer to documentation for
    additional details. [-Wdeprecated-declarations]
            [[NSNumber alloc] initWithBool:[firRemoteConfigSettings isDeveloperModeEnabled]];
                                                                    ^
    In module 'FirebaseRemoteConfig' imported from /Users/anthony/github/org/app/ios/Pods/Headers/Public/Firebase/Firebase.h:146:
    /Users/anthony/github/org/app/ios/Pods/FirebaseRemoteConfig/FirebaseRemoteConfig/Sources/Public/FIRRemoteConfig.h:141:37:
    note: property 'isDeveloperModeEnabled' is declared deprecated here
    @property(nonatomic, readonly) BOOL isDeveloperModeEnabled DEPRECATED_MSG_ATTRIBUTE(
                                        ^
    /Users/anthony/github/org/app/ios/Pods/FirebaseRemoteConfig/FirebaseRemoteConfig/Sources/Public/FIRRemoteConfig.h:141:60:
    note: 'isDeveloperModeEnabled' has been explicitly marked deprecated here
    @property(nonatomic, readonly) BOOL isDeveloperModeEnabled DEPRECATED_MSG_ATTRIBUTE(
                                                               ^
```

I am using **firebase_remote_config: 0.3.0+3**.

**Comment by devlimba** [comment]
hii i have solved this issue use this one firebase_admob: ^0.5.5

**Comment by iapicca** [comment]
Hi @awhitford 
I'm glad you solved the issue
Thank you for letting me know

**Comment by awhitford** [comment]
@iapicca  I'm not using `firebase_admob` -- I'm unclear what @devlimba is referring to.  This is still an issue.

**Comment by iapicca** [comment]
Hi @awhitford 
my bad, I misread and thought it was your answer.

Could you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by le-kamba** [comment]
I got same warnings from

- firebaseRemoteConfigInfo.getConfigSettings().isDeveloperModeEnabled
- FirebaseRemoteConfigSettings.Builder().setDeveloperModeEnabled
- firebaseRemoteConfig.setConfigSettings
- FirebaseRemoteConfig.getInstance().setDefault

Env:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale ja-JP)
    • Flutter version 1.12.13+hotfix.5 at /develop/flutter
    • Framework revision 27321ebbad (5 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /develop/android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /develop/android_sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

and the `pubspec.yaml`.

```
version: 1.0.4+7

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Provider
  provider: ^4.0.0

  tuple: ^1.0.3
  intl: ^0.16.0
  get_it: ^4.0.1
  jiffy: ^3.0.1
  # DB
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.7

  # Firebase
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_remote_config: ^0.3.0+3

  package_info: '>=0.4.0+17 <2.0.0'
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # matcher
  matcher: ^0.12.6
  # mock
  mockito: ^3.0.0

  # network image test
  image_test_utils: ^1.0.0

  # for hive
  hive_generator: 0.7.0+2
  build_runner: ^1.9.0

  # icon generate
  flutter_launcher_icons: ^0.7.5

  # splash
  flutter_native_splash: ^0.1.9

# icon generate sources
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/icon1024.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/ic_background.png"
  adaptive_icon_foreground: "assets/icon/ic_foreground.png"

# splash generate sources
flutter_native_splash:
  image: "assets/splash/splash.png"
  color: "97d4d9"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/
```
