### ISSUE TITLE
[firebase_auth] android release build failing

### ISSUE THREAD

**Issue by mflesh1** [FirebaseExtended/flutterfire#2412]
**Describe the bug**
I am trying to build an and android release version running the following command.

`flutter build apk --no-shrink  --split-per-abi`

```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':shared_preferences:verifyReleaseResources'. 
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /Users/mattfleshman/.gradle/caches/transforms-2/files-2.1/77a5d7c3f5c22bab0d3c60446f5dad5f/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
     /Users/mattfleshman/.gradle/caches/transforms-2/files-2.1/77a5d7c3f5c22bab0d3c60446f5dad5f/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 6s                                                      
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       7.6s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin firebase_auth...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.9s
✓ Built build/app/outputs/repo.
Building plugin firebase_auth_web...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.7s


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mattfleshman/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'firebaseauth_web'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /Users/mattfleshman/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s


The plugin firebase_auth_web could not be built due to the issue above.
```
**pubspec.yaml snippet**

```
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.4+3
  firebase_crashlytics: ^0.1.3+3
  #firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.13
  firebase_auth: 0.16.0
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  meta: ^1.1.6
  equatable: ^1.0.0
  shared_preferences: ^0.4.2
  flutter_native_timezone: ^1.0.4
  sprintf: "^4.0.0"
  get_it: ^4.0.1
  email_validator: '^1.0.0'
  geolocator: ^5.3.1
  google_maps_flutter: ^0.5.25+3
  dio: ^3.0.9
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^4.4.0
  font_awesome_flutter: ^8.8.1
```

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```
