### ISSUE TITLE
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility. Building plugin cloud_firestore... The plugin cloud_firestore could not be built due to the issue above.

### ISSUE THREAD

**Issue by Omar-ramadan1** [FirebaseExtended/flutterfire#2481]
```yaml
pubspec.yaml
`version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  

  cloud_firestore: 0.8.2+3

  firebase_auth: 0.6.6
  google_sign_in: ^3.2.4

  rxdart: 0.20.0`
```

```gradle
build.gradle android
` dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'

    }`
```
