### ISSUE TITLE
[firebase_remote_config] Inaugural fetch fails

### ISSUE THREAD

**Issue by awhitford** [FirebaseExtended/flutterfire#2592]
**Describe the bug**

When my app runs **for the first time on a physical iPhone device**, the Remote Config initialization fails.  Specifically, the [`fetch`](https://pub.dev/documentation/firebase_remote_config/latest/firebase_remote_config/RemoteConfig/fetch.html) call throws an exception:  **Unable to fetch remote config**:
```
#0   RemoteConfig.fetch (package:firebase_remote_config/src/remote_config.dart:134:<…>
<asynchronous suspensio<…>                      
#1   _KozzetedAppState.initRemoteConfig (package:kozzeted/main.dart:56:2<…>
<asynchronous suspensio<…>                      
#2   _KozzetedAppState.initState (package:kozzeted/main.dart:49:2<…>
#3   StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:5<…>
#4   ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:<…>
#5   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:1<…>
#6   Element.updateChild (package:flutter/src/widgets/framework.dart:3214:1<…>
#7   RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:1<…>
```

If I kill the app and run it again, everything works as expected.  However, **first impressions are everything!** (I'm highly concerned that this flaky behavior breaks first time downloads using  _Firebase Dynamic Link_.)

**To Reproduce**

I run into this issue every time I `flutter install` on my physical device; the very first start exhibits this issue.

I was finally able to reproduce the issue in the Simulator after running **Erase All Content and Settings...**, then `flutter run`.  Again, the first run fails, but subsequent runs will work as expected.

**Expected behavior**
`fetch` should work.  Unless there is something preventing it like no network connectivity, then I would expect the first run to behave the same as the next run, and so on.

**Additional context**
I have only really noticed this with iPhone testing.  I'm not sure if this is impacting Android too.  (It took me quite a while to trace this mysterious issue to this code and circumstances.)

My `initRemoteConfig` code is pretty vanilla:
```dart
  Future<RemoteConfig> initRemoteConfig() async {
    final RemoteConfig remoteConfig = await RemoteConfig.instance;
    await remoteConfig.fetch();
    await remoteConfig.activateFetched();
    return remoteConfig;
  }
```

Here are the Remote Config related lines from my `ios/Podfile.lock` file:
```
  - Firebase/RemoteConfig (6.24.0):
    - FirebaseRemoteConfig (~> 4.4.10)
  - firebase_remote_config (0.0.1):
    - Firebase/RemoteConfig
  - FirebaseRemoteConfig (4.4.10):
  - firebase_remote_config (from `.symlinks/plugins/firebase_remote_config/ios`)
    - FirebaseRemoteConfig
  firebase_remote_config:
    :path: ".symlinks/plugins/firebase_remote_config/ios"
  firebase_remote_config: f3581c5addecc691a968f2a7f2bcdf0878509bfd
  FirebaseRemoteConfig: 12669ca87e6d9cf87a6123cb8ad8a771a7b49c6b
```
I recently ran `pod update` to ensure that I'm running the latest versions.  I am using `firebase_remote_config 0.3.0+3`.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

• No issues found!
```
