### ISSUE TITLE
[firebase_auth] Firebase Auth User signs out after page reload

### ISSUE THREAD

**Issue by ShardulNalegave** [FirebaseExtended/flutterfire#2624]
**Description**
On my flutter web app, the plugin works great, I can sign in, sign out, etc. But when I reload my web app I get logged out automatically. This happens after Hot Restart too! Because of this I need to log in everytime in my app.

**Note:-** This doesn't happen on Mobile app (With same code)

**To Reproduce**
- Create a basic flutter web app with firebase_auth.
- Log in with your account. 
- Reload the page.
- Log in again.

**Expected behavior**
The user login should persist.

**Additional context**
I searched for this problem on stackoverflow and github. There are some similar issues but their solutions don't work at all.
For example:-
I use the following code to determine if the user is logged in.
````dart
(await FirebaseAuth.instance.currentUser()) != null;
````
I saw a suggesstion which told to use:-
````dart
await FirebaseAuth.instance.onAuthStateChanged.first;
````
But it doesn't work!

**Flutter doctor**
````
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] Connected device (2 available)

• No issues found!
````

**Comment by iapicca** [comment]
Hi @ShardulNalegave 
can you please provide
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by ShardulNalegave** [comment]
My `pubspec.yaml` file:-
````yaml
name: Shoppit
description: Desktop application for Shoppit

publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  cloud_firestore: ^0.13.5
  get: ^2.5.9
  get_it: ^4.0.2
  firebase_auth: ^0.16.0
  stacked: ^1.5.4
  injectable: ^0.4.0
  firebase_messaging: ^6.0.15
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator:

flutter:
  uses-material-design: true
````

My Application has nothing, just some text fields (email and password) to log in. Login is always successful but after page reload the user signs out automatically and I need to login again.
