### ISSUE TITLE
[FIREBASE_AUTH] Email Sign-in not working as expected on Android

### ISSUE THREAD

**Issue by PaulTR** [FirebaseExtended/flutterfire#2642]
Using the FlutterFire Auth demo app, after setting up dynamic links, the `FirebaseDynamicLinks.instance.getInitialLink();` call only returns null.

**To Reproduce**
Use the FlutterFire auth sample, add values for project, i.e.

```return await _auth.sendSignInWithEmailLink(
      email: _userEmail,
      url: 'https://flutterfirestore.page.link/emailSignInLink',
      handleCodeInApp: true,
      iOSBundleID: 'com.google.firebase.flutterfirestore',
      androidPackageName: 'com.google.firebase.flutterfirestore',
      androidInstallIfNotAvailable: true,
      androidMinimumVersion: "1",
    );
```
Manifest mimics the Android sample, which does work with my console setup:
```
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <data
                    android:host="flutterfirestore.page.link"
                    android:scheme="https" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
```

Enable Dynamic Links and auth per docs https://firebase.google.com/docs/auth/android/email-link-auth. Ensure dependencies added to build.gradle at the project level:

```
    implementation 'com.google.firebase:firebase-auth:19.3.1'
    implementation 'com.google.android.gms:play-services-auth:18.0.0'
```
Make sure the rest of Firebase is initialized to get the json file, and app is registered with the debug sha1.

Set launchMode for android to singleInstance to get around issue with multiple instances of the app being opened up.

When opening the link sent to the email, the app opens, but then data pulled from the dynamic link is null and the red 'sign-in failed' message is displayed.

**Expected behavior**
App should open to the sign-in page and finish authenticating against the registered user.

**Additional context**

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
➜ flutter_firestore /Users/ptruiz/Documents/code/flutter/bin/flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/ptruiz/Documents/code/flutter
    • Framework revision 0b8abb4724 (4 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ptruiz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

pubspec.yaml:
```
name: flutterfirestore
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.4
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  firebase_dynamic_links: ^0.5.0+11

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
