### ISSUE TITLE
[Firebase_Auth] Firestore (7.14.6): Could not reach Cloud Firestore backend. Fetching auth token failed: getToken aborted due to token change.

### ISSUE THREAD

**Issue by sam-parks** [FirebaseExtended/flutterfire#2699]
**Describe the bug**
When I hot reload or hot restart a Flutter Web debug session, the client can't access Firebase because of this error. The client switches to offline mode when this error occurs and I can no longer reach Firebase without completely restarting the app.  

**To Reproduce**

1. Create a flutter web app with firebase plugins
2. Access Firebase successfully in debug session
3. hot reload or hot restart session  
4. Sends request to Firebase

**Expected behavior**
Can consistently make requests to Firebase after hot reload or hot restart. 

**Additional context**

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel master, 1.19.0-2.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @sam-parks 
Can you please provide your `flutter run -d chrome --verbose` 
(while performing hot-restart)
and your `pubspec.yaml`
Thank you

**Comment by sam-parks** [comment]
**flutter run -d chrome --verbose** 

[+15814 ms] Performing hot restart...
[   +5 ms] Starting incremental build...
[   +5 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +5 ms] complete
[   +6 ms] Scanned through 497 files in 5ms
[        ] Syncing files to device Chrome...
[   +1 ms] <- recompile
org-dartlang-app:/web_entrypoint.dart
85a837b4-c909-4f22-806c-7f52524c44be
[        ] <- 85a837b4-c909-4f22-806c-7f52524c44be
[  +22 ms] Syncing files to device Chrome...
(completed in 24ms)
[        ] Synced 0.0MB.
[        ] <- accept
[  +92 ms] Performing hot restart... (completed in
151ms)
[        ] Restarted application in 152ms.
[  +42 ms] Null is not a subtype of
Future<dynamic>.
           This will become a failure when runtime
null
           safety is enabled.
           
I recently upgraded the firestore package and now this is the error from the Chrome console: 
<img width="456" alt="Screen Shot 2020-06-05 at 7 52 51 AM" src="https://user-images.githubusercontent.com/44235716/83878304-8ff18f00-a701-11ea-9696-a23fa215e052.png">


**pubspec.yaml**
```
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


    #Firebase
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.12.9+5
  firebase: any
  firebase_storage: ^3.1.5
  cloud_functions: 0.4.1+9

  #Utilities
  intl: any
  provider: any
  googleapis_auth: ^0.2.11+1
  service_worker: ^0.2.3
  auto_size_text: ^2.1.0
  flutter_selectable_text: 0.3.1
  http: ^0.12.0+4
  url_launcher: 5.4.2
  flutter_bloc: ^4.0.0
  file_picker: ^1.4.3+2
  mime_type: ^0.2.7
  esys_flutter_share: ^1.0.2
  image_picker_web: ^1.0.8
  universal_html: ^1.2.2
  cached_network_image: ^2.0.0
  path_provider: ^1.5.0
  image_picker_saver: ^0.3.0
  flutter_web_image_picker: ^0.0.2
  google_sign_in: ^4.5.1
  flutter_auth_buttons: ^0.8.0
  flutter_svg: ^0.17.4
  flushbar: ^1.10.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Mermaid
      fonts:
        - asset: fonts/Mermaid-Bold-700.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**Firebase JS** 
```
       <!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/7.14.6/firebase-app.js"></script>


<!-- TODO: Add SDKs for Firebase products that you want to use
   https://firebase.google.com/docs/web/setup#available-libraries -->
<script src="https://www.gstatic.com/firebasejs/7.14.6/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.14.6/firebase-firestore.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.14.6/firebase-functions.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.14.6/firebase-auth.js"></script>
```
It seems that Firebase Auth is working but its when I try to access Firestore. Here is some code I am using to talk with Firebase: 
```
Future<CortadoUser> registerUser(String email, String password) async {
  if (email.isNotEmpty && password.isNotEmpty) {
    try {
      final _user = await auth.signInWithEmailAndPassword(email, password);
      if (_user != null) {
        print(_user.user.uid);
        DocumentSnapshot snapshot =
            await _usersCollection.doc(_user.user.uid).get();
        CortadoUser cortadoUser =
            CortadoUser.fromSnapshot(snapshot, firebaseUser: _user.user);
        if (cortadoUser.isAdmin)
          return cortadoUser;
        else
          throw 'Invalid User';
      }
    } catch (e) {
      throw e;
    }
  } else {
    throw "Please fill correct e-mail and password.";
  }
  throw 'Error Communicating with Firebase';
}
```
