### ISSUE TITLE
Firebase dynamic link not working with android sdk version 26

### ISSUE THREAD

**Issue by kumarlalapet** [FirebaseExtended/flutterfire#2721]
In android version 8.1 (sdk version 26). Flutter app is crashing with the below error

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.legacy.content.WakefulBroadcastReceiver"
```

Im using the the latest beta channel flutter and the below dependencies

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: 0.4.5
  cloud_firestore: 0.13.6     # new
  firebase_database: 3.1.6
  firebase_auth: 0.16.1
  google_sign_in: 4.5.1 #for google sign in
  timeago: ^2.0.20
  http: ^0.12.0+4
  after_layout: ^1.0.7 #new check later
  url_launcher: ^5.4.2 # used only in the curater
  carousel_slider: ^1.4.1
  random_color: ^1.0.3
  font_awesome_flutter: 8.8.1
  share: ^0.6.3+6
  firebase_dynamic_links: ^0.5.1
  firebase_analytics: ^5.0.14
```

I made sure Im using the latest dependencies. Can someone help where Im going wrong?
