### ISSUE TITLE
[firebase_auth] sms not being sent on some devices 

### ISSUE THREAD

**Issue by athlona64** [FirebaseExtended/flutterfire#2766]
**Describe the bug**
a phone number authentication not send sms to desination. this behavior is happen in some phone number on some device. i'm not sure why firebase is block phone number on device i try change device but use same phone number is sent and i use different phone number with old phone is sent same.

**To Reproduce**
1. fill phone number
2. request sms from firebase
3. verify is complete but codeSent is not call and can't signin

**Expected behavior**
```
            await FirebaseAuth.instance.verifyPhoneNumber(
                phoneNumber: phoneNumber,
                timeout: const Duration(seconds: 10),
                verificationCompleted: verificationCompleted,
                verificationFailed: verificationFailed,
                codeSent: codeSent,
                codeAutoRetrievalTimeout: codeAutoRetrievalTimeout);
```

codeSent is not call in some phone number on some device

**Additional context**
```
            await FirebaseAuth.instance.verifyPhoneNumber(
                phoneNumber: phoneNumber,
                timeout: const Duration(seconds: 10),
                verificationCompleted: verificationCompleted,
                verificationFailed: verificationFailed,
                codeSent: codeSent,
                codeAutoRetrievalTimeout: codeAutoRetrievalTimeout);
```

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision e6b34c2b5c (6 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\prapa\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\prapa\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

Pubspec.yaml

```

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_platform_widgets: ^0.20.3-beta.1
  path_provider: ^1.3.0
  flutter:
    sdk: flutter
  permission: ^0.1.3
  share: ^0.6.3+6
  fluttertoast: ^3.1.3
  shared_preferences: 0.4.3
  flutter_screenutil: ^0.5.2
  qr_flutter: ^3.0.1
  web3dart: ^1.1.1+1
  web_socket_channel: ^1.0.8
  bip39: ^1.0.2
  bitcoin_flutter: ^2.0.0
  toast: ^0.1.3
  crypto: ^2.1.4
  flutter_spinkit: ^4.1.1+1
  after_layout: ^1.0.7+2
  cached_network_image: ^2.0.0
  intl: ^0.16.0
#  firebase_ml_vision: ^0.9.3+8
  barcode_scan: ^3.0.1
  ethereum: 4.0.1
  bmnav: 0.3.4
  loading_indicator: ^1.0.0
  image_gallery_saver: ^1.2.2
  firebase_storage: ^3.1.1
  package_info: ^0.4.0+13
  native_widgets: ^1.3.5

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.2
  http: ^0.12.0+2
  auto_size_text: ^2.0.1
  flutter_file_manager: ^0.2.0
  contacts_service: ^0.0.8
  pattern_formatter: ^1.0.1
  countdown: ^0.1.0
  english_words: ^3.1.0
  #man
  ed25519_hd_key: ^1.0.1
  dart_ssss: ^0.0.5
  local_auth: ^0.6.0+1
  get_it: ^3.0.1
  passcode_screen:
    path: ./passcode_screen-1.0.2


#  firebase_auth: 0.15.3+1
  sms_receiver: ^0.3.1+1
  sms_autofill: ^1.2.1
  firebase_auth: ^0.16.1
  firebase_core: 0.4.4
  permission_handler: ^4.4.0+hotfix.2
  firebase_analytics: ^5.0.6
  pull_to_refresh: ^1.5.7
  cloud_firestore: ^0.12.11
  bip32_dart: ^1.0.5
  json_annotation: ^3.0.0
  provider: ^3.2.0
  flutter_share_me: ^0.9.0
  encrypt: ^4.0.0
  flutter_secure_storage: ^3.3.1+1
  ads: ^1.7.2
  image_picker: ^0.6.3+1
  http_parser: ^3.1.3
  dio: ^3.0.8
  infinite_listview: ^1.0.1+1
  qrscan: ^0.2.17
  rxdart: ^0.23.1
  keyboard_actions: ^3.2.0
  keyboard_visibility: ^0.5.6
  carousel_slider: ^1.3.0
  mqtt_client: ^6.1.0
  in_app_update: ^1.1.7
  store_redirect: ^1.0.2
  url_launcher: ^5.4.7
  dash_chat:
    path: ./dash_chat
  avataaar_image: ^1.0.8
  esys_flutter_share: ^1.0.2
  #ios pod
#  flutter_camera_ml_vision: ^2.2.4
  camera: ^0.5.7+3s

  #ios pod
#  flutter_camera_ml_vision: ^2.2.4
#  qr_mobile_vision: ^1.0.1+1
  flutter_camera_ml_vision: ^2.2.5
  launch_review: ^2.0.0
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^1.2.0+2
  flare_flutter: ^1.8.3
  date_format: any
  webview_flutter: ^0.3.21
  firebase_ml_vision: ^0.9.3+8
  firebase_crashlytics: ^0.1.3+3
  adobe_xd:
  flutter_svg:
  device_apps: ^1.0.9

  #Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist file with the key io.flutter.embedded_views_preview and the value YES.


#  flutter_money_formatter:
#    path: ./flutter_money_formatter
  snaplist: ^0.1.8

```
