### ISSUE TITLE
[firebase_auth_web] Exceptions in web don't match exceptions on android

### ISSUE THREAD

**Issue by mrmax99** [FirebaseExtended/flutterfire#2864]
**Describe the bug**
When an error occurs on flutter web, the error code looks like "auth/credential-already-in-use" and catching a PlatformException won't detect it.  The same error occurring in flutter on an android emulator triggers a PlatformException with error code ERROR_CREDENTIAL_ALREADY_IN_USE.

It looks like this commit was going to fix it, but never got pulled in?
https://github.com/FirebaseExtended/flutterfire/pull/1617/commits/8f23976e59fc885c37b2d3fcf1deeec27cdff5aa

**To Reproduce**
Trigger any firebase_auth error on both web and android emulator and observe the error that you catch.

The instance I'm having trouble with in this particular instance is calling FirebaseUser linkWithCredential with a google credential to link a google account to an anonymous account, but the google account already exists, thus yielding the ERROR_CREDENTIAL_ALREADY_IN_USE error.

**Expected behavior**
The same flutter code should work on android and web, catching a PlatformException with matching error codes.

e.g.:
on PlatformException catch (e) {

**Additional context**
Using firebase_auth 0.16.1

**Flutter doctor**
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.18363.900], locale  
    en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.46.1)
[√] Connected device (2 available)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @mrmax99 
Can you please provide your `flutter run -d Chrome --verbose`, your `pubspec.yaml` and a complete reproducible minimal code sample
Thank you

**Comment by mrmax99** [comment]
I thought it might be easier to reproduce this with a test in the firebase_auth_web area of the repo, but I can't even seem to get those tests to run.

> flutter test .\test\firebase_auth_web_test.dart   
No tests ran.

I was able to get the test for firebase_auth to run just fine.  Am I missing some setup or something to get these tests to run?

**Comment by TahaTesser** [comment]
Hi @mrmax99 
Please provide details https://github.com/FirebaseExtended/flutterfire/issues/2864#issuecomment-651786591
Thank you

**Comment by mrmax99** [comment]
Here's code that reproduces a difference between web and android exceptions raised when **anonymous accounts are disabled** on firebase.  Android raises a PlatformException with "ERROR_ADMIN_RESTRICTED_OPERATION" code, and web raises a FirebaseError with "auth/admin-restricted-operation" code.  There's similar mismatch for other errors, but this was the easiest one for me to reproduce in a simple example.


Code to reproduce:
```
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/services.dart';
import 'package:google_sign_in/google_sign_in.dart';


void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  final FirebaseAuth _auth = FirebaseAuth.instance;

  Future<FirebaseUser> _signInAnonymously() async {
    print("Trying to sign in anonymously!");
    try {
      await _auth.signInAnonymously();
    } on PlatformException catch (e) {
      print("Caught PlatformException exception correctly!");
      print(e);
      print(e.code);
      return null;
    } catch (e) {
      print("Incorrect!  This is not a PlatformException!");
      print(e);
      print(e.code);
      return null;
    }
    print("Signed in!");
    return await _auth.currentUser();
  }

  void _incrementCounter() {
    _signInAnonymously()
      .then((FirebaseUser user) => print(user.uid))
      .catchError((e) => print(e));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}

```


Android log:
```
I/flutter ( 5722): Trying to sign in anonymously!
I/BiChannelGoogleApi( 5722): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@443e776
I/flutter ( 5722): Caught PlatformException exception correctly!
I/flutter ( 5722): PlatformException(ERROR_ADMIN_RESTRICTED_OPERATION, This operation is restricted to administrators only., null)
I/flutter ( 5722): ERROR_ADMIN_RESTRICTED_OPERATION
I/flutter ( 5722): NoSuchMethodError: The getter 'uid' was called on null.
I/flutter ( 5722): Receiver: null
I/flutter ( 5722): Tried calling: uid
```

Web log (from flutter run -d Chrome --verbose):
```
PS C:\Users\MrMax\Documents\bash_work\debug_firebase_auth_web_exceptions> flutter run -d Chrome --verbose
[   +9 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8fe7655ed20ffd1395f68e30539a847a01a30351        
[   +1 ms] executing: [C:\flutter/] git tag --contains HEAD
[ +214 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.19.0-4.3.pre
[  +14 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[   +1 ms] executing: [C:\flutter/] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +77 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping  
update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.      
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +31 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.    
[  +12 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping       
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping       
update.
[  +27 ms] executing: C:\Users\MrMax\AppData\Local\Android\sdk\platform-tools\adb.exe
devices -l
[  +52 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping   
update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.      
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.    
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.    
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.[  +11 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping       
update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping       
update.
[ +130 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.1\
[  +10 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.3+1\
[   +7 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[   +7 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +37 ms] Found plugin google_sign_in at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.1\
[  +19 ms] Found plugin google_sign_in_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.1+1\
[  +80 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.1\
[   +4 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.3+1\
[   +3 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[  +14 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +5 ms] Found plugin google_sign_in at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.1\
[  +14 ms] Found plugin google_sign_in_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.1+1\
[  +91 ms] Generating
C:\Users\MrMax\Documents\bash_work\debug_firebase_auth_web_exceptions\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +105 ms] Launching lib\main.dart on Chrome in debug mode...
[  +83 ms] Updating assets
[  +96 ms] Syncing files to device Chrome...
[  +11 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.1\
[   +4 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.3+1\
[   +4 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[  +12 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +3 ms] Found plugin google_sign_in at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.1\
[  +15 ms] Found plugin google_sign_in_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.1+1\
[  +35 ms] Found plugin firebase_auth at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.1\
[   +8 ms] Found plugin firebase_auth_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.3+1\
[   +3 ms] Found plugin firebase_core at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[   +3 ms] Found plugin firebase_core_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +14 ms] Found plugin google_sign_in at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.1\
[   +5 ms] Found plugin google_sign_in_web at
C:\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.9.1+1\
[  +31 ms] Generating
C:\Users\MrMax\Documents\bash_work\debug_firebase_auth_web_exceptions\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +73 ms] <- reset
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
--old_gen_heap_size=2000
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root  
C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc
--debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\MrMax\AppData\Local\Temp\flutter_tools.b6221686\flutter_tool.16e94a46\app.dill     
--libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages     
.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-root
C:\Users\MrMax\AppData\Local\Temp\flutter_tools.b6221686\flutter_tools.8e5a8c09
--filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill     
--platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +21 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+8911 ms] Syncing files to device Chrome... (completed in 9,158ms, longer than expected)
[   +2 ms] Synced 23.2MB.
[   +1 ms] <- accept
[ +220 ms] [CHROME]:
[  +11 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:60511/devtools/browser/a7bde6ac-af04-4b19-b37b-3dd8e9de159f
[+4436 ms] Debug service listening on ws://127.0.0.1:60561/ycI0qDnPb-4=

[ +485 ms] Debug service listening on ws://127.0.0.1:60561/ycI0qDnPb-4=
[   +4 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[  +22 ms] been thoroughly tested in production environments.
[   +1 ms] For more information see https://flutter.dev/web
[   +3 ms]   To hot restart changes while running, press "r" or "R".
[  +31 ms] For a more detailed help message, press "h". To quit, press "q".
[+7105 ms] Trying to sign in anonymously!

[ +716 ms] Incorrect!  This is not a PlatformException!

[   +2 ms] FirebaseError: This operation is restricted to administrators only.
           (auth/admin-restricted-operation)

[  +12 ms] auth/admin-restricted-operation

[  +12 ms] NoSuchMethodError: invalid member on null: 'uid'
```


pubspec.yaml:
```
name: debug_firebase_auth_web_exceptions
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.0+9
  google_sign_in: ^4.5.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```
