### ISSUE TITLE
[Firebase Auth] firebase_core 0.5.0-dev.1 version solving failed

### ISSUE THREAD

**Issue by deependrasolanky** [FirebaseExtended/flutterfire#2995]
```
dependencies:
  flutter:
    sdk: flutter

  firebase_core: "0.5.0-dev.1"
  firebase_auth: "0.16.1"
```
```
Running "flutter pub get" in <myappname>...             

Because firebase_auth 0.16.1 depends on firebase_core ^0.4.4 and <myappname> depends on firebase_core 0.5.0-dev.1, firebase_auth 0.16.1 is forbidden.
So, because <myappname> depends on firebase_auth 0.16.1, version solving failed.
pub get failed (1; So, because <myappname> depends on firebase_auth 0.16.1, version solving failed.)
Process finished with exit code 1
```
I am following official FlutterFire docs but getting above error while installing packages.

**Comment by Salakar** [comment]
Hey @deependrasolanky - the updated auth package has not been published yet. Please keep an eye out on the roadmap issue for when this happens (#2582).

**Comment by deependrasolanky** [comment]
@Salakar  For beginners in Flutter it is suggested to mention package incompatibility in the docs. It will help in saving time in debugging. [https://firebase.flutter.dev/docs/overview#installation](https://firebase.flutter.dev/docs/overview#installation)  
```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.5.0-dev.1"
```
