### ISSUE TITLE
FIREBASE_MESSAGING Google-Services.json  not found

### ISSUE THREAD

**Issue by SnehModi** [FirebaseExtended/flutterfire#3007]
Inspite of saving the google-services.json file at correct location, an error is occurring that google-services.json file not found.
**To Reproduce**
pubspec.yaml :
```
dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.0
  pull_to_refresh: ^1.6.0
  http: ^0.12.1
  lazy_load_scrollview: ^1.1.0
  flutter_speed_dial:
  carousel_slider: ^2.2.1
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  clipboard_manager: ^0.0.4
  flutter_share: ^1.0.2+1
  provider: ^4.3.1
  shared_preferences: ^0.5.8
  url_launcher: ^5.5.0
  store_redirect: ^1.0.2
  fluttertoast: ^7.0.1
  firebase_analytics: ^5.0.16
  firebase_messaging: ^6.0.16
  firebase_core: ^0.4.5
```
Followed all the other steps mentioned [here](https://pub.dev/packages/firebase_messaging)
Error :
```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_messaging:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.16\android\src\nullnull\google-services.json
  C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.16\android\src\debug\google-services.json
  C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.16\android\src\nullnullDebug\google-services.json
  C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.16\android\src\nullnull\debug\google-services.json
  C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.16\android\src\debug\nullnull\google-services.json
  C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.16\android\google-services.json
```

It is checking irrelevant location which doesn't exists 

Flutter Doctor Summary:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.2)
[√] Connected device (1 available)
```
