### ISSUE TITLE
[cloud_firestore]: Flutter Web: "TypeError: Cannot read property 'app' of undefined"

### ISSUE THREAD

**Issue by maxmoros** [FirebaseExtended/flutterfire#3072]
**Describe the bug**
Flutter Web crashes when cloud_firestore: "0.14.0-dev.1" is added to pubspec.yaml

```
TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (http://localhost:60710/packages/firebase/src/top_level.dart.lib.js:78:89)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:60710/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:688:57)
    at Function.registerWith (http://localhost:60710/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:624:73)
    at Object.registerPlugins (http://localhost:60710/packages/the_basics/generated_plugin_registrant.dart.lib.js:15:46)
    at main (http://localhost:60710/web_entrypoint.dart.lib.js:29:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:60710/dart_sdk.js:37369:34)
    at Object._async [as async] (http://localhost:60710/dart_sdk.js:37400:7)
    at main$ (http://localhost:60710/web_entrypoint.dart.lib.js:28:18)
    at http://localhost:60710/main_module.bootstrap.js:20:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:60710/main_module.bootstrap.js:19:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:60710/dwds/src/injected/client.js:8758:21)
    at http://localhost:60710/dwds/src/injected/client.js:22459:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:60710/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:60710/dwds/src/injected/client.js:10996:12)
    at Object._asyncStartSync (http://localhost:60710/dwds/src/injected/client.js:3766:20)
    at main__closure1.$call$body$main__closure (http://localhost:60710/dwds/src/injected/client.js:22471:16)
    at main__closure1.call$1 (http://localhost:60710/dwds/src/injected/client.js:22398:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:60710/dwds/src/injected/client.js:4136:16)
    at _CustomZone.runUnary$2$2 (http://localhost:60710/dwds/src/injected/client.js:12301:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:60710/dwds/src/injected/client.js:12233:14)
    at _ControllerSubscription._sendData$1 (http://localhost:60710/dwds/src/injected/client.js:11784:19)
    at _DelayedData.perform$1 (http://localhost:60710/dwds/src/injected/client.js:11936:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:60710/dwds/src/injected/client.js:11985:14)
    at Object._microtaskLoop (http://localhost:60710/dwds/src/injected/client.js:3969:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:60710/dwds/src/injected/client.js:3975:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:60710/dwds/src/injected/client.js:10865:9)
    at invokeClosure (http://localhost:60710/dwds/src/injected/client.js:1204:26)
    at MutationObserver.<anonymous> (http://localhost:60710/dwds/src/injected/client.js:1223:18)
```

**To Reproduce**
My index.html: 
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>the_basics</title>
</head>
<body id="app-container">
  <!-- Insert these scripts at the bottom of the HTML, but before you use any Firebase services -->

  <!-- Firebase App (the core Firebase SDK) is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-auth.js"></script>

  <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
       \\Stuff
    };
    // Initialize Firebase
    const firebase = require("firebase");
    require("firebase/firestore");
    firebase.initializeApp(firebaseConfig);
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```

my pubspec.yaml:
```
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  responsive_builder: ^0.1.4
  get_it:
  provider_architecture:
  provider: ^3.1.0
  http: ^0.12.0+2
  firebase: ^7.3.0
  # firebase_core: "0.5.0-dev.2"
  cloud_firestore: 0.14.0-dev.1
  cached_network_image: ^2.2.0+1
  firebase_auth:
  firebase_auth_web:

dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Expected behavior**
I expected the cloud firestore plugin to work after following the documentation to get it working.
I need this plugin to work so I can 

**Additional context**
The application runs fine when I remove the cloud_firestore plugin from pubspec.yaml

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Mac OS X 10.15.5 19F2200, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.2)
[✓] Connected device (2 available)

• No issues found!
```
