### ISSUE TITLE
Firebase_Dynamic_links Missing plugin exception after adding facebook_app_events package

### ISSUE THREAD

**Issue by anass-naoushi** [FirebaseExtended/flutterfire#3092]
I have added firebase dynamic links to my flutter app and it works perfectly, then I wanted to add facebook_app_events to my app. I added it following the instructions. I launched the app then firebase dynamic links stopped working with the following error:
Launching lib\main.dart on SM G930V in debug mode...
Plugin project :firebase_core_web not found. Please update settings.gradle.
√ Built build\app\outputs\flutter-apk\app-debug.apk.
**W/FlutterActivity( 8798): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@90d680) but could not find and invoke the GeneratedPluginRegistrant.
E/FlutterFcmService( 8798): Fatal: failed to find callback**
Connecting to VM Service at ws://127.0.0.1:4725/ji05M87o10Q=/ws
D/libGLESv2( 8798): STS_GLApi : DTS, ODTC are not allowed for Package : qcard.club
**I/flutter ( 8798): error:MissingPluginException(No implementation found for method FirebaseDynamicLinks#getInitialLink on channel plugins.flutter.io/firebase_dynamic_links)**
I/zygote64( 8798): Do partial code cache collection, code=60KB, data=47KB
I/zygote64( 8798): After code cache collection, code=60KB, data=47KB
I/zygote64( 8798): Increasing code cache capacity to 256KB

**To Reproduce**
1. Add firebase dynamic links to your pubspec.yaml  firebase_dynamic_links: ^0.5.3
2. the app works perfectly
3. add facebook app events to your pubspec.yaml  facebook_app_events: ^0.6.0
4. the app builds and installs and runs but anything related to dynamic links does ot work throwing the above mentioned error.
5. remove facebook app events, everything returns to normal

**Expected behavior**
adding facebook app events and firebase dynamic links should not cause a problem and the app must function normally
**Additional context**
I entered the GeneratedPluginRegistrant.java file and found that the firebase dynamic links and the facebook app events are there and this is the file content:
```
package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.registerWith(shimPluginRegistry.registrarFor("id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin"));
      io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.firebaseauth.FirebaseAuthPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.core.FirebaseCorePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebasedynamiclinks.FirebaseDynamicLinksPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin());
      io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
      com.apptreesoftware.flutterwebview.FlutterWebViewPlugin.registerWith(shimPluginRegistry.registrarFor("com.apptreesoftware.flutterwebview.FlutterWebViewPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.googlesignin.GoogleSignInPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
      com.codeheadlabs.libphonenumber.LibphonenumberPlugin.registerWith(shimPluginRegistry.registrarFor("com.codeheadlabs.libphonenumber.LibphonenumberPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
  }
}
```

**Flutter doctor**
flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-5.0.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.7)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 3.3)
[√] Connected device (5 available)

! Doctor found issues in 1 category.
```
**Flutter Version**
flutter --version
```
Flutter 1.21.0-5.0.pre • channel master • https://github.com/flutter/flutter.git
Framework • revision 54c9441723 (3 weeks ago) • 2020-07-17 18:56:12 -0400
Engine • revision d327828632
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)
```

**Comment by kroikie** [comment]
HI @anass-naoushi I'm unable to reproduce this with the example app in the [`firebsase_dynamic_links`](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links/example) plugin, could you give that a try so we can better narrow down the issue?

**Comment by anass-naoushi** [comment]
did the app work properly after adding all configurations for facebook app events??

**Comment by anass-naoushi** [comment]
I launched the example app without the facebook_app_events package and the app worked. I added the package using the following code in pubspec.yaml:
```
name: firebase_dynamic_links
description: Flutter plugin for Google Dynamic Links for Firebase, an app solution for creating
  and handling links across multiple platforms.
version: 0.5.3
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links

dependencies:
  flutter:
    sdk: flutter

  facebook_app_events: ^0.6.0  

dev_dependencies:
  pedantic: ^1.8.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  url_launcher: ^5.1.6
  firebase_core: ^0.4.5
  e2e: ^0.6.1
  

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebasedynamiclinks
        pluginClass: FirebaseDynamicLinksPlugin
      ios:
        pluginClass: FLTFirebaseDynamicLinksPlugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
```

The app compiled and ran successfully and gave no errors .
