### ISSUE TITLE
[Cloud Firestore] Unable to instantiate Cloud Firestore/ query

### ISSUE THREAD

**Issue by transilience** [FirebaseExtended/flutterfire#3161]
**Describe the bug**
In a new project unable to work with cloud firestore

**To Reproduce**
1. create a new project with ```flutter create newproject```
2. Add dependencies in build.gradle
3. Try to query the Cloud firestore
4. Firebase auth working fine

**Expected behavior**
Obtain documents from the firestore

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
flutter doctor -v
[✓] Flutter (Channel master, 1.21.0-8.0.pre.145, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.21.0-8.0.pre.145 at /home/c0de/Desktop/development/flutter
    • Framework revision 2c1b95b9e7 (23 hours ago), 2020-08-11 09:31:03 -0400
    • Engine revision 235e389d29
    • Dart version 2.10.0 (build 2.10.0-9.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/c0de/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/91/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/91/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

! Doctor found issues in 1 category.
```
**pubspec.yaml**

```
name: truechat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.4+2
  fluttertoast: ^7.0.2
  image_picker:  ^0.6.7+4
  shared_preferences: ^0.5.8
  firebase_storage: ^3.1.6
  cached_network_image: ^2.2.0
  intl: ^0.16.1
  diacritic: ^0.1.1
  sentry: ^3.0.1
  image_cropper: ^1.3.0
  contacts_service: ^0.4.6
  permission_handler: ^3.0.0
  share: ^0.6.4+3
  scoped_model: ^1.0.1
  local_auth: ^0.6.2+3
  crypto: ^2.1.5
  encrypt: ^4.0.2
  localstorage: ^3.0.2+5
  flutter_cache_manager: ^1.4.1
  photo_view: ^0.9.2
  mime: ^0.9.7
  ntp: ^1.0.7
  url_launcher: ^5.5.0
  launch_review: ^2.0.0
  flutter_secure_storage: ^3.3.3
  giphy_client: ^0.2.0
  firebase_messaging: ^6.0.16
  cloud_functions: ^0.5.0
  async: ^2.4.2
  provider: ^4.0.5+1
  firebase_core: ^0.4.0+9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/img_not_available.jpeg
    - assets/flags/
    - assets/bg.png
    - assets/giphy.png
    - assets/512x512.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

** app build.gradle**
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.transilience.truechat"
        minSdkVersion 18
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    signingConfigs {
        debug {
            keyAlias 'androiddebugkey'
            keyPassword 'android'
            storeFile file("keystore/chatdebug.keystore")
            storePassword 'android'
        }
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            minifyEnabled true
        }
        debug{
            debuggable true
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-auth:19.3.2'
    implementation 'com.google.firebase:firebase-inappmessaging-display:19.1.0'
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.google.firebase:firebase-core:17.4.4'
    implementation 'com.google.firebase:firebase-analytics:17.4.4'
    implementation 'com.google.firebase:firebase-firestore:19.0.0'

    //for 64 thing
    implementation 'com.android.support:multidex:1.0.3'
}

apply plugin: 'com.google.gms.google-services'
```

## As soon as I call

```
Firestore _firestore = Firestore.instance;
```

** Error thrown **

```
W/DynamiteModule( 6486): Local module descriptor class for providerinstaller not found.
D/AndroidRuntime( 6486): Shutting down VM
E/AndroidRuntime( 6486): FATAL EXCEPTION: main
E/AndroidRuntime( 6486): Process: com.transilience.truechat, PID: 6486
E/AndroidRuntime( 6486): java.lang.RuntimeException: Internal error in Cloud Firestore (21.3.0).
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(com.google.firebase:firebase-firestore@@21.3.0:529)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(com.google.firebase:firebase-firestore@@21.3.0)
E/AndroidRuntime( 6486): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 6486): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6486): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 6486): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/AndroidRuntime( 6486): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6486): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/AndroidRuntime( 6486): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/AndroidRuntime( 6486): Caused by: java.lang.ExceptionInInitializerError
E/AndroidRuntime( 6486): 	at com.google.firestore.v1.ListenRequest.getDefaultInstance(com.google.firebase:firebase-firestore@@21.3.0:915)
E/AndroidRuntime( 6486): 	at com.google.firestore.v1.FirestoreGrpc.getListenMethod(com.google.firebase:firebase-firestore@@21.3.0:408)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.remote.WatchStream.<init>(com.google.firebase:firebase-firestore@@21.3.0:61)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.remote.Datastore.createWatchStream(com.google.firebase:firebase-firestore@@21.3.0:115)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.remote.RemoteStore.<init>(com.google.firebase:firebase-firestore@@21.3.0:167)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.core.FirestoreClient.initialize(com.google.firebase:firebase-firestore@@21.3.0:280)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0(com.google.firebase:firebase-firestore@@21.3.0:108)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.core.FirestoreClient$$Lambda$1.run(com.google.firebase:firebase-firestore@@21.3.0)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(com.google.firebase:firebase-firestore@@21.3.0:431)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(com.google.firebase:firebase-firestore@@21.3.0)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(com.google.firebase:firebase-firestore@@21.3.0:317)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(com.google.firebase:firebase-firestore@@21.3.0)
E/AndroidRuntime( 6486): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
E/AndroidRuntime( 6486): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 6486): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
E/AndroidRuntime( 6486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime( 6486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime( 6486): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@21.3.0:224)
E/AndroidRuntime( 6486): 	at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime( 6486): Caused by: java.lang.RuntimeException: Unable to get message info for com.google.firestore.v1.ListenRequest
E/AndroidRuntime( 6486): 	at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:62)
E/AndroidRuntime( 6486): 	at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:143)
E/AndroidRuntime( 6486): 	at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:55)

```

been stuck at it for about 24 hours now
