### ISSUE TITLE
MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core) on Android

### ISSUE THREAD

**Issue by tomtaila** [FirebaseExtended/flutterfire#3212]
I am getting the above error when calling `Firebase.initializeApp()` in my flutter code.
I have followed the documentation here: https://firebase.flutter.dev/docs

Here is my pubspec.yaml
```
name: moolla
description: Moolla - Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0
  firebase_auth: ^0.18.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: BalooThambi2
      fonts:
        - asset: fonts/baloo_thambi2_m.ttf
        - asset: fonts/baloo_thambi2_r.ttf
        - asset: fonts/baloo_thambi2_b.ttf
        - asset: fonts/baloo_thambi2_sb.ttf
        - asset: fonts/baloo_thambi2_xb.ttf
```

Here is my flutter code:
```
import 'dart:core';
import 'dart:developer';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    FutureBuilder(
      future: Firebase.initializeApp(),
      builder: (context, snapshot) {
        // Check for errors
        if (snapshot.hasError) {
          log(snapshot.error.toString());
          return Container(color: Colors.red,);
        }

        // Once complete, show your application
        if (snapshot.connectionState == ConnectionState.done) {
          return Container(color: Colors.green);
        }

        // Otherwise, show something whilst waiting for initialization to complete
        return Container(color: Colors.blue,);
      },
    ),
  );
}
```

Here are the relevant part of my .gradle (app) file:
```
plugins {
    id "com.android.application"
    id "com.google.gms.google-services"
    id "kotlin-android"
    id "kotlin-android-extensions"
}

```

Here is my project gradle file:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.3.72"
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0-alpha07'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}
```

and my Application class extension:

```
class MyApp : FlutterApplication() {
    override fun onCreate() {
        super.onCreate()
    }
}
```
Finally, here is my flutter doctor -v output:
```
[✓] Flutter (Channel beta, 1.20.2, on Mac OS X 10.15.5 19F96, locale en-US)
    • Flutter version 1.20.2 at /Users/tom/development/flutter
    • Framework revision bbfbf1770c (5 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/tom/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Pixel 3 (mobile) • 89HX09YAJ  • android-arm64  • Android 11 (API 30)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.125
```

As far as I can tell I have done everything correctly according to the docs.
