### ISSUE TITLE
[firebase_crashlytics] Non fatal errors are all grouped together in Crashlytics console

### ISSUE THREAD

**Issue by mvolpato** [FirebaseExtended/flutterfire#3310]
**Describe the bug**
When I call `Crashlytics.instance.recordError("message", StackTrace.current);` from different places in my code, the non-fatal errors in Crashlytics are all grouped under the same error `firebase_crashlytics.dart line 244 - _recordError`.

**To Reproduce**
1. Add 2 calls to `Crashlytics.instance.recordError("message", StackTrace.current);` with different messages in 2 different places;
2. Check Firebase Crashlytics console, after 24 hours.
3. There is 1 non-fatal error with 2 instances with different stack traces.

**Expected behavior**
There are 2 different non-fatal errors.

**Additional context**
I followed the official guide to setup Crashlytics in my Flutter app. The method `Crashlytics.instance.recordError` has also an optional `context` parameter, but there is no information in the documentation on what should be used there.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale
    en)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[!] Android Studio (not installed)
[✓] VS Code (version 1.48.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment]
Hi @mvolpato 
Can you please provide your `pubspec.yaml`
Thank you

**Comment by mvolpato** [comment]
Hi @TahaTesser 
You bet I can!

```
name: AppName
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1 

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # Firebase related packages.
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.15
  firebase_crashlytics: ^0.1.3+3
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.7
  cloud_functions: ^0.5.0

  # Provider is a wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^4.1.3

  # Useful wrapper around Streams
  rxdart: ^0.24.1

  # Open website from app
  url_launcher: ^5.4.11

  # Linear percent indicator
  percent_indicator: "^2.1.5"

  # Localized formatting
  intl: ^0.16.1

  # Provide paths to directories
  path_provider: ^1.6.11

  # App information like version
  package_info: ^0.4.1

  # Shimmer loading effect
  shimmer: ^1.1.1

  # Send email using native email client
  flutter_email_sender: ^3.0.1

  # Information on the device
  device_info: '>=0.4.2+4 <2.0.0'

  # Notifications
  flutter_local_notifications: ^1.4.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

  # Autogenerate launcher icons  
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  ios: false
  android: true
  image_path: "assets/launcher/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/strings/ # localization
```

I also use [this trick to reduce build time](https://github.com/FirebaseExtended/flutterfire/issues/2751), so my `Podfile` includes this line (in case this is relevant):

```
 pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.26.0'
```
