### ISSUE TITLE
[firebase_crashlytics] Cannot see the latest version in Firebase panel

### ISSUE THREAD

**Issue by alnitak** [FirebaseExtended/flutterfire#3325]
I cannot see the latest version under Quality->Crashlitics in Firebase panel.

A while back I have ported my app from native android java to Flutter.
The old version was named 2.6.2.91 (20091 and 30091 abi codes for armeabi-v7a and arm64-v8a) in the build.gradle. The new version is named 3.3.2+114 in pubspec.yaml.

I have followed all the Crashlitics plugin doc, but the only issues I can see in Firebase console are those related to the old 2.6.2.91 version.
I can see the new 3.3.2 version for example under Analytics->Latest Release.

I could think the problem is the 4 numbers in the old version, but I don't know how I can solve this because pubspec.yaml doesn't permit to have 4 numbers version.

Thanks for your time

**Comment by TahaTesser** [comment]
Hi @alnitak 
Did you 24 hours to reflect changes? 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`  and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by alnitak** [comment]
Hi Taha, thanks for your reply.
Yes, weeks have passed since I published the app. Anyway, I just saw the new 0.1.4 version is out, but I didn't test it yet.
Here my `flutter doctor -v` but the published app was made with Flutter version 1.20.0 IIRC
<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at /opt/flutter
    • Framework revision bbfbf1770c (13 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/android-sdk/
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio
    • Android Studio at /opt/android-studio/
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /opt/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

<details>
  <summary>pubspec.yaml</summary>

```
name: selenium
description: Selenium Music Player

version: 3.3.2+114

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_crashlytics: ^0.1.3+3
  in_app_purchase: ^0.3.1+1
  firebase_admob: ^0.9.0+10
  provider: ^3.1.0
  dio: ^3.0.9
  connectivity: ^0.4.8
  image: ^2.1.14
  easy_localization: ^1.3.1
  reorderables: ^0.3.2
   timeago: 2.0.18
  flare_flutter: ^1.5.4
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.8
  liquid_pull_to_refresh: ^1.1.1
  device_simulator: ^0.9.5
  package_info: ^0.4.0+10
  url_launcher: ^5.0.2
  launch_review: ^2.0.0
  share_extend: ^1.1.0
  expandable: ^4.0.1
  in_app_update: ^1.1.11

  flutter_duration_picker:
    path: ../libs/flutter_duration_picker

  shared_preferences_settings:
    path: ../libs/shared_preferences_settings

  audio_service:
    path: ../libs/audio_service

  flutteropengl:
    path: ../libs/flutteropengl

  flutter_media_db:
    path: ../libs/flutter_media_db

  flutter_mb_knob:
    path: ../libs/flutter_mb_knob

  star_menu:
    path: ../libs/star_menu

  flutter_mb_slider:
    path: ../libs/flutter_mb_slider

  flutter_taglib:
    path: ../libs/flutter_taglib

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/my_banner.png
    - assets/images/vinyl.png
    - assets/ic_launcher_round.png
    - assets/ic_launcher_round_transparent.png
    - assets/icons/warning.png
    - assets/icons/checked.png
    - assets/icons/themes.png
    - assets/icons/zpm_logo.png
    - assets/icons/wave.png
    - assets/lang/en-US.json
    - assets/lang/es-ES.json
    - assets/lang/fr-FR.json
    - assets/lang/it-IT.json
    - assets/lang/id-ID.json
    - assets/lang/de-DE.json
    - assets/lang/hi-HI.json
    - assets/lang/ru-RU.json
    - assets/lang/tr-TR.json
    - assets/lang/th-TH.json
    - assets/lang/vi-VN.json
    - assets/flare/menu_to_vert.flr
    - assets/flare/play_pause.flr
    - assets/flare/skip.flr
    - assets/flare/shuffle.flr
    - assets/flare/loop.flr
    - assets/flare/playing.flr
    - assets/Presets.json
    - assets/autowahPreset.json
    - assets/chorusPreset.json
    - assets/echoPreset.json
    - assets/phaserPreset.json
    - assets/images/theme_blue.webp
    - assets/images/theme_dark.webp
    - assets/images/theme_light.webp
    - assets/images/theme_red.webp
    - assets/images/theme_yellow.webp
    - assets/images/mirror2.webp
    - assets/images/effects/
    - assets/themes/light/knob.webp
    - assets/themes/light/handler.webp
    - assets/themes/light/handler_on.webp
    - assets/themes/light/handler_seek_on.webp
    - assets/themes/light/handler_seek_off.webp
    - assets/themes/dark/knob.webp
    - assets/themes/dark/handler.webp
    - assets/themes/dark/handler_on.webp
    - assets/themes/dark/handler_seek_on.webp
    - assets/themes/dark/handler_seek_off.webp
    - assets/themes/blue/background.webp
    - assets/themes/blue/knob.webp
    - assets/themes/blue/handler.webp
    - assets/themes/blue/handler_on.webp
    - assets/themes/blue/handler_seek_on.webp
    - assets/themes/blue/handler_seek_off.webp
    - assets/themes/red/knob.webp
    - assets/themes/red/handler.webp
    - assets/themes/red/handler_on.webp
    - assets/themes/red/handler_seek_on.webp
    - assets/themes/red/handler_seek_off.webp
    - assets/themes/yellow/background.webp
    - assets/themes/yellow/knob.webp
    - assets/themes/yellow/handler.webp
    - assets/themes/yellow/handler_on.webp
    - assets/themes/yellow/handler_seek_on.webp
    - assets/themes/yellow/handler_seek_off.webp

  fonts:
    - family: Leds
      fonts:
        - asset: assets/fonts/ledboard.ttf
    - family: LedsRev
      fonts:
        - asset: assets/fonts/ledbdrev.ttf
    - family: LedsBoard7
      fonts:
        - asset: assets/fonts/led_board-7.ttf
```

</details>

if you need more info I'll be glad to provide them. Thanks again
