### ISSUE TITLE
🐛 [firebase_core] Failed to build the firebase_core plugin in windows-10

### ISSUE THREAD

**Issue by invingagan1** [FirebaseExtended/flutterfire#3598]
## Bug report

**Describe the bug**
I added the firebase core plugin to add the google login support  for the application. Plugin is failing the build.

### Steps to reproduce

1. Add the firebase_core and firebase_auth in depenedcies.
2. Build is failing

### Expected behavior

Application should build properly.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Gagan@LAPTOP-PJDDU4TA MINGW64 /d/github/app-challenge/file_manager (gagan/google-drive)
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2
  get_it: ^4.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # package for listing android files
  file_utils: ^0.1.4
  path_provider: ^1.6.11
  simple_permissions: ^0.1.9
  path_provider_ex: ^1.0.1

  # Firebase auth to access the firebase auth plugin
  #firebase_auth: ^0.18.0+1

  # Firebase core to setup connection with firebase
  firebase_core: ^0.5.0

  # google sign in to provide login handling for the google account
  google_sign_in: ^4.5.1

  # google apis to access the google provided apis.
  googleapis: ^0.55.0

  # To access the http power
  http: ^0.12.2

  # to convert size into human readable format
  filesize: ^1.0.4

  # To store app specific data to local disk
  sqflite: ^1.3.1+1
```

</details>

---
