### ISSUE TITLE
🐛 [firebase_core/cloud_firestore] InitializeApp Error When Hot Restart

### ISSUE THREAD

**Issue by ivanchaukn** [FirebaseExtended/flutterfire#3602]
## Bug report

Running my flutter on android emulator and I'm getting an error whenever I try to hot restart the app. It's working fine on iOS emulator. I'm not sure whether I'm initializing firebase correctly but that's what I saw in other examples.

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  // Set `enableInDevMode` to true to see reports while in debug mode
  // This is only to be used for confirming that reports are being
  // submitted as expected. It is not intended to be used for everyday
  // development.
  Crashlytics.instance.enableInDevMode = false;

  // Pass all uncaught errors to Crashlytics.
  FlutterError.onError = Crashlytics.instance.recordFlutterError;

  setupLocator();

  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    systemNavigationBarColor: Colors.transparent,
    systemNavigationBarIconBrightness: Brightness.dark,
  ));

  runApp(new MyApp());
}
```

```
E/flutter (12751): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(firebase_core, java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.firebase.firestore.ListenerRegistration.remove()' on a null object reference, null)
E/flutter (12751): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter (12751): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (12751): <asynchronous suspension>
E/flutter (12751): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (12751): #3      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:347:40)
E/flutter (12751): #4      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:36)
E/flutter (12751): #5      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75:13)
E/flutter (12751): #6      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:25)
E/flutter (12751): #7      main (package:fella/main.dart:36:18)
E/flutter (12751): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:233:25)
E/flutter (12751): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (12751): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (12751): #11     _runZoned (dart:async/zone.dart:1630:10)
E/flutter (12751): #12     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (12751): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:225:5)
E/flutter (12751): #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (12751): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (12751): 
```
---

## Additional context

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.0
  intl_translation: ^0.17.0

  # Google/Firebase packages
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  cloud_firestore: ^0.14.0+2
  firebase_performance: ^0.3.2
  firebase_crashlytics: ^0.1.3+3
  firebase_dynamic_links: ^0.5.1
  shared_preferences: ^0.5.10
  google_maps_flutter: ^0.5.32
  google_fonts: ^1.1.0

  # Charts packages
  charts_flutter: ^0.9.0
  flutter_circular_chart: ^0.1.0

  # Image packages
  image: ^2.1.4
  cached_network_image: ^2.2.0+1
  transparent_image: ^0.1.0

  # QR packages
  qr_flutter: ^3.2.0

  # Picker packages
  file_picker: ^2.0.0
  open_file: ^2.1.1
  flutter_material_color_picker: ^1.0.5
  photo_view: ^0.10.2

  # String packages
  recase: ^2.0.1
  random_string: ^0.0.2
  flutter_linkify: ^3.0.0
  linkify: ^2.0.1
  selectable_autolink_text: ^1.3.4

  # Other packages
  device_calendar: ^1.0.0+2
  provider: ^4.0.3
  get_it: ^3.1.0
  flutter_launcher_icons: ^0.7.4
  flushbar: 1.10.4
  async: ^2.2.0
  http: ^0.12.0+1
  url_launcher: ^5.6.0
  path_provider: ^1.5.1
  package_info: ^0.4.0+13
  device_info: ^0.4.1+4
  font_awesome_flutter: ^8.8.1
  screen: ^0.0.5
  tutorial_coach_mark: ^0.5.1
  share: '>=0.6.4+3 <2.0.0'
  share_extend: ^1.1.9
  flutter_staggered_grid_view: ^0.3.2
  timeline_tile: ^0.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E287, locale en-CA)
    • Flutter version 1.20.4 at /Users/ivanchau/Documents/flutter
    • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ivanchau/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/ivanchau/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.9.2
Flutter SDK 1.20.4
fella 3.0.0+129

dependencies:
- async 2.4.2 [collection]
- cached_network_image 2.2.0+1 [flutter flutter_cache_manager]
- charts_flutter 0.9.0 [charts_common collection flutter intl logging meta]
- cloud_firestore 0.14.0+2 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 0.1.3
- device_calendar 1.0.0+3 [flutter meta]
- device_info 0.4.1+4 [flutter]
- file_picker 2.0.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 6.0.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.1.3+3 [flutter stack_trace]
- firebase_dynamic_links 0.5.1 [flutter]
- firebase_messaging 7.0.0 [meta platform flutter firebase_core]
- firebase_performance 0.3.2 [flutter]
- firebase_storage 4.0.0 [flutter firebase_core]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_circular_chart 0.1.0 [flutter]
- flutter_launcher_icons 0.7.4 [image args yaml]
- flutter_linkify 3.0.0 [flutter linkify]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_material_color_picker 1.0.5 [flutter]
- flutter_staggered_grid_view 0.3.2 [flutter]
- font_awesome_flutter 8.8.1 [flutter]
- get_it 3.1.0 [meta]
- google_fonts 1.1.0 [flutter http path_provider crypto pedantic]
- google_maps_flutter 0.5.32 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- http 0.12.0+4 [async http_parser path pedantic]
- image 2.1.12 [archive xml]
- intl 0.16.1 [path]
- intl_translation 0.17.8 [analyzer args dart_style intl path petitparser]
- linkify 2.0.3
- open_file 2.1.1 [flutter]
- package_info 0.4.0+13 [flutter]
- path_provider 1.5.1 [flutter platform meta]
- photo_view 0.10.2 [flutter]
- provider 4.3.1 [flutter nested collection]
- qr_flutter 3.2.0 [flutter qr]
- random_string 0.0.2
- recase 2.0.1
- screen 0.0.5 [flutter]
- selectable_autolink_text 1.3.4 [flutter]
- share 0.6.4+3 [meta flutter]
- share_extend 1.1.9 [meta flutter]
- shared_preferences 0.5.10 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web]
- timeline_tile 0.1.2 [flutter]
- transparent_image 0.1.0
- tutorial_coach_mark 0.5.1 [flutter]
- url_launcher 5.6.0 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _fe_analyzer_shared 1.0.3 [meta]
- analyzer 0.39.4 [_fe_analyzer_shared args charcode collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- boolean_selector 2.0.0 [source_span string_scanner]
- characters 1.0.0
- charcode 1.1.3
- charts_common 0.9.0 [collection intl logging meta vector_math]
- clock 1.0.1 [meta]
- cloud_firestore_platform_interface 2.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+1 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- collection 1.14.13
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.4 [collection convert typed_data]
- csslib 0.16.1 [source_span]
- dart_style 1.3.3 [analyzer args path source_span]
- fake_async 1.1.0 [clock collection]
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.1 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.0+1 [flutter flutter_web_plugins firebase meta http_parser intl firebase_core firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_cache_manager 1.4.1 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_plugin_android_lifecycle 1.0.8 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_maps_flutter_platform_interface 1.0.4 [flutter meta plugin_platform_interface stream_transform]
- html 0.14.0+3 [csslib source_span]
- http_parser 3.1.3 [charcode collection source_span string_scanner typed_data]
- js 0.6.1+1
- logging 0.11.3+2
- matcher 0.12.8 [stack_trace]
- meta 1.1.8
- nested 0.0.4 [flutter]
- node_interop 1.0.3 [js]
- node_io 1.0.1+2 [node_interop path]
- package_config 1.1.0 [charcode path]
- path 1.7.0
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- pedantic 1.8.0+1
- petitparser 2.4.0 [meta]
- platform 2.2.1
- platform_detect 1.4.0 [meta pub_semver]
- plugin_platform_interface 1.0.2 [meta]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.2 [collection]
- qr 1.2.0 [meta]
- quiver 2.1.3 [matcher meta]
- rxdart 0.24.1
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+3 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.1 [meta flutter]
- shared_preferences_web 0.1.2+2 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- sky_engine 0.0.99
- source_span 1.7.0 [charcode collection meta path term_glyph]
- sqflite 1.2.0 [flutter synchronized path]
- stack_trace 1.9.5 [path]
- stream_channel 2.0.0 [async]
- stream_transform 1.2.0
- string_scanner 1.0.5 [charcode meta source_span]
- synchronized 2.1.1
- term_glyph 1.1.0
- test_api 0.2.17 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.2.0 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+2 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.3+2 [url_launcher_platform_interface platform_detect flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- uuid 2.0.4 [crypto convert]
- vector_math 2.0.8
- watcher 0.9.7+13 [async path pedantic]
- xdg_directories 0.1.0 [path process flutter]
- xml 3.6.1 [collection convert meta petitparser]
- yaml 2.2.0 [charcode collection string_scanner source_span]

```

</details>

---
