### ISSUE TITLE
🐛 FirebaseCore Crashes the iOS apps

### ISSUE THREAD

**Issue by scarranca** [FirebaseExtended/flutterfire#3852]
## Bug report

Suddenly crashes my builds in iOS with a lot of errors, when I delete firebase-core from pubspec.yaml it works fine.

### Steps to reproduce
1.-Create project.
2.-Install firebase-core in v ^0.5.0+1.
3.-Run in iOS.

### Expected behavior

Run the app in iOS

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details>

[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.0)
[✓] Connected device (1 available)
<summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
  lottie: ^0.6.0
  salomon_bottom_bar: ^1.0.6
  flutter_icons: ^1.1.0
  modal_bottom_sheet: ^0.2.0+1
  freshchat: ^0.1.6
  url_launcher: ^5.5.3
  flutter_datetime_picker: ^1.4.0
  image_picker: ^0.6.7+7
  firebase_core: ^0.4.5
  international_phone_input: ^1.0.4
  pin_code_fields: ^5.0.1
  http: ^0.12.2
  flutter_rating_bar: ^3.0.1+1
  flutter_html:
  animate_do: ^1.7.3
  credit_card_input_form: ^2.0.3
```

</details>

---

<img width="632" alt="Screen Shot 2020-10-12 at 20 50 27" src="https://user-images.githubusercontent.com/22356118/95808908-1aab5180-0cd3-11eb-8775-02313dc3a27c.png">
