### ISSUE TITLE
[firebase_messaging 8.0.0-dev.7] Invalid notification content

### ISSUE THREAD

**Issue by Johann13** [FirebaseExtended/flutterfire#4070]
## Bug report

**Describe the bug**
I added firebase_messaging to my flutter app and added the background handler functions. When I send a message to a device (I only tested android so far) the message is recieved but and error is thrown as well.
```
D/FLTFireMsgReceiver(18743): broadcast received for message
D/FCMService(18743): FCM received
D/FCMService(18743): Invalid notification content
```

### Steps to reproduce

1. Add firebase_messaging 8.0.0-dev.7 to the pubspec

2. initialized firebase_messaging 8.0.0-dev.7 in the app
main.dart 

```
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print("Handling a background message ${message.messageId}");
  print("Handling a background message ${message.data}");
}
void main(List<String> args) async {
  WidgetsFlutterBinding.ensureInitialized();
 
FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  
FirebaseMessaging.onMessage.listen(firebaseMessagingBackgroundHandler);  
runApp(App());
}
```

3. Send a notification
I used a python script

```
token: str = "<TOKEN>"
cred = credentials.Certificate('cred.json')
app = firebase_admin.initialize_app(cred)
message = messaging.Message(
    android=messaging.AndroidConfig(
        ttl=1,
    ),
    data={
        'score': '850',
        'time': '2:45',
    },
    notification=messaging.Notification(
        title="title",
        body="body",
    ),
    token=token,
)
result = messaging.send(message, app=app)
print(result)
```
And prints
`projects/<firebase-app-id>/messages/<message-id>`

When I remove the data part only this ist logged
`D/FLTFireMsgReceiver(20284): broadcast received for message`

### Expected behavior

For now I just wanted to print the data part of the message and later on to use it to display a notification using [flutter_local_notifications ](https://pub.dev/packages/flutter_local_notifications)or [awesome_notifications](https://pub.dev/packages/awesome_notifications).
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] VS Code (version 1.51.0)
[√] Connected device (4 available)

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>
I removed some imports. I'm also testing 2 notification plugins but have not initialized them in the app.

```
dependency_overrides:
  meta: 1.3.0-nullsafety.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^8.0.0-dev.7

  cloud_firestore: ^0.14.3
  firebase_remote_config: ^0.4.2
  firebase_database: ^4.0.0
  firebase_crashlytics: ^0.2.3

  flutter_local_notifications: ^3.0.1+2
  awesome_notifications: ^0.0.4+4

flutter:

  uses-material-design: true

  fonts:
    - family: YcAppIcons
      fonts:
        - asset: fonts/YcAppIcons.ttf
  assets:
    - assets/2.0x/
    - assets/3.0x/
    - assets/
    - google_fonts/
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

```

</details>

---
