### ISSUE TITLE
🐛 [firebase_core] Android RELEASE Build Stuck On Splash Screen/CRASH

### ISSUE THREAD

**Issue by danielgchap** [FirebaseExtended/flutterfire#4410]
## Bug report

**Describe the bug**

Installing a release Android build with Flutter from Visual Studio Code results in hanging on splash screen and error output.
This ONLY occurs on release builds.

### Steps to reproduce

1. Install app on Android device (flutter run --release)
2. Hangs on splash screen

### Expected behavior

App runs to login screen.

---

## Additional context

Main file:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await SharedPreferences.getInstance();
  Admob.initialize();
  await Admob.requestTrackingAuthorization();

  DynamicLinkService.handleDynamicLinks();
  SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitDown, DeviceOrientation.portraitUp]).then(
    (_) {
      runApp(
        StringConstants(
          child: AuthProvider(auth: Auth(), child: MyApp()),
        ),
      );
    },
  );
}
```

Error Output:
```
E/flutter (27229): [ERROR:flutter/lib/ui/ui_dart_state.cc(184)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (27229): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:160)
E/flutter (27229): <asynchronous suspension>
E/flutter (27229): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:348)
E/flutter (27229): <asynchronous suspension>
E/flutter (27229): #2      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30)
E/flutter (27229): <asynchronous suspension>
E/flutter (27229): #3      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75)
E/flutter (27229): <asynchronous suspension>
E/flutter (27229): #4      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43)
E/flutter (27229): <asynchronous suspension>
E/flutter (27229): #5      main (package:instapray/main.dart:20)
E/flutter (27229): <asynchronous suspension>
E/flutter (27229): 
```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.88, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
    • Flutter version 1.25.0-9.0.pre.88 at /Users/danielchapman/Dev/flutter
    • Framework revision e24e763872 (4 hours ago), 2020-12-16 07:33:03 -0500
    • Engine revision e9f2f0eaea
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/danielchapman/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • motorola one (mobile) • ZY323HWSM7 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: "^0.5.3"
  # Newly reworked plugins covered by this migration guide:
  firebase_auth: "^0.18.4"
  cloud_firestore: "^0.14.4"
  cloud_functions: "^0.7.2"
  firebase_storage: "^5.2.0"
  firebase_messaging: ^7.0.3  # Updated to work with new core only plugins (no new changes):
  firebase_admob: "^0.10.3"
  firebase_analytics: "^6.3.0"
  firebase_database: "^4.4.0"
  firebase_dynamic_links: "^0.6.3"
  firebase_in_app_messaging: "^0.2.3"
  firebase_performance: "^0.4.3"
  flutter_local_notifications: ^3.0.2
```

</details>

---

THANK YOU!!!
