### ISSUE TITLE
🐛 [firebase_auth] In verifyPhoneNumber, codeSent seems to be called back without a resendToken

### ISSUE THREAD

**Issue by sarbogast** [FirebaseExtended/flutterfire#4542]
## Bug report

When I call `verifyPhoneNumber` as documented [here](https://firebase.flutter.dev/docs/auth/phone), the `codeSent` callback is triggered with a non-null `verificationId` but a null `forceResendingToken`, which prevents me from triggering a resend of the code in case the user didn't receive it.
And I didn't find anywhere in the doc reasons why this argument might be null.

### Steps to reproduce

```dart
await _auth.verifyPhoneNumber(
        phoneNumber: _phoneNumber.toString(),
        verificationCompleted: (PhoneAuthCredential credential) async {},
        verificationFailed: (FirebaseAuthException e) {},
        codeSent: (String verificationId, int resendToken) {
          //here resendToken is null, but why?
        },
        codeAutoRetrievalTimeout: (String verificationId) {},
      );
    }
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale fr-FR)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)
    ! Error: Séjour is busy: Waiting for Device. Xcode will continue when Séjour is finished. (code -10)

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

I get this weird error message I don't know how to solve. So I will add a copy of my `pubspec.yaml` too.

<details><summary>Click To Expand</summary>

```
The ".dart_tool/package_config.json" file is not recognized by "pub" version, please run "pub get".
pub finished with exit code 65
```

</details>

<details><summary>pubspec.yaml</summary>

```
name: blindly
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.16.1

  cupertino_icons: ^1.0.0
  firebase_core: 0.5.3
  firebase_auth: ^0.18.4+1
  firebase_database: ^4.4.0
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4
  firebase_performance: ^0.4.3
  cloud_firestore: ^0.14.4
  google_fonts: ^1.1.1
  logger: ^0.9.4
  flutter_bugfender: ^1.2.2
  url_launcher: ^5.7.10
  flutter_markdown: ^0.5.1
  intl_phone_number_input: #^0.6.0
    git:
      url: git://github.com/natintosh/intl_phone_number_input.git
  pin_code_fields: ^6.0.2
  json_annotation: ^3.1.1
  validators: ^2.0.1
  form_validators: ^0.2.1
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  json_serializable: ^3.5.1

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

```

</details>

---
