### ISSUE TITLE
Firebase / FireStore packages not working

### ISSUE THREAD

**Issue by jerryhamby** [FirebaseExtended/flutterfire#4655]
Has anyone else been having the same issues?
Testing IOS only for now.

How I created the problem:
1- create a new project
2- add the Google packages to the pubspec.yaml file
3- Run "start debugging"
4- errors show up right away

I can't get these Google packages to work with my very basic project.
```yaml
firebase_core: ^0.5.2
cloud_firestore: ^0.14.3
firebase_storage: ^4.0.1
firebase_admob: ^0.10
```
These packages work fine in my project.
```yaml
package_info: ^0.4.3+2
in_app_purchase: ^0.3.4+16
shared_preferences: ^0.5.12+4
image_picker: ^0.6.7+14
camera: ^0.5.8+11
provider: ^4.3.2+2
google_sign_in: ^4.5.6
rflutter_alert: ^1.1.0
image: ^2.1.19
path: ^1.7.0
path_provider: ^1.6.24
cached_network_image: ^2.3.3
back_button_interceptor: ^4.4.0
webview_flutter: ^1.0.7
url_launcher: ^5.7.10
share: ^0.6.5+4
flutter_native_image: ^0.0.5+3
flutter_image_compress: ^0.7.0
flutter_cache_manager: ^2.0.0
dropdown_formfield: ^0.1.3
```

My System:
Xcode: 12.3
VS Code: 1.52.1
Flutter: 1.22.5
Dart: 3.18.1

macOS Catalina - 10.15.7
iMac 2019 27"
