### ISSUE TITLE
when I am using firebase firestore in the flutter web it shows me an error.

### ISSUE THREAD

**Issue by lkrjangid1** [FirebaseExtended/flutterfire#4809]
when I am using firebase firestore in the flutter web it shows me an error.

```
FirebaseError: Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app). 
Error: Failed assertion: boolean expression must not be null 
at Object.throw_ [as throw] (http://localhost:62696/dart_sdk.js:4361:11) 
at Object.test (http://localhost:62696/dart_sdk.js:4651:32) 
at Object.dtest (http://localhost:62696/dart_sdk.js:4656:55) 
at main$ (http://localhost:62696/packages/flutter_appfirebase/main.dart.lib.js:375:17)
at main$.next (<anonymous>) at runBody (http://localhost:62696/dart_sdk.js:38027:34) 
at Object._async [as async] (http://localhost:62696/dart_sdk.js:38058:7) 
at main$ (http://localhost:62696/packages/flutter_appfirebase/main.dart.lib.js:374:18) 
at main (http://localhost:62696/web_entrypoint.dart.lib.js:35:27) at main.next (<anonymous>) 
at http://localhost:62696/dart_sdk.js:38007:33 
at _RootZone.runUnary (http://localhost:62696/dart_sdk.js:37861:58) 
at _FutureListener.thenAwait.handleValue (http://localhost:62696/dart_sdk.js:32822:29) 
at handleValueCallback (http://localhost:62696/dart_sdk.js:33370:49) at Function._propagateToListeners (http://localhost:62696/dart_sdk.js:33408:17) 
at async._AsyncCallbackEntry.new.callback (http://localhost:62696/dart_sdk.js:33133:27) 
at Object._microtaskLoop (http://localhost:62696/dart_sdk.js:38122:13) 
at _startMicrotaskLoop (http://localhost:62696/dart_sdk.js:38128:13) 
at http://localhost:62696/dart_sdk.js:33625:9
```

my HTML file
```
<!DOCTYPE html>
<html>
<head>

  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter application.">
  <script src="/__/firebase/init.js"></script>

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="mbmelearning">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>mbmelearning</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
<!-- This script installs service_worker.js to provide PWA functionality to
     application. For more information, see:
     https://developers.google.com/web/fundamentals/primers/service-workers -->
<script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
<!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/8.2.4/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.4/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>

<script>
  // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  var firebaseConfig = {
     apiKey: "key",
    authDomain: "app.firebaseapp.com",
    databaseURL: "https://app.firebaseio.com",
    projectId: "app",
    storageBucket: "app.appspot.com",
    messagingSenderId: "id",
    appId: "id",
    measurementId: "myid"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();
</script>
<script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```
pubspec.yaml file
```
name: flutter_appfirebase
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  firebase: ^8.0.0
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
