### ISSUE TITLE
🐛 [firebase_messaging: 8.0.0-dev.14] Official example get dependency conflicts

### ISSUE THREAD

**Issue by eldarkk** [FirebaseExtended/flutterfire#4834]
## Bug report

Im trying to run official example https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib, but getting errors about dependency conflicts when run flutter pub get.

```
[firebase_check] flutter pub get
Running "flutter pub get" in firebase_check...                  
Because firebase_messaging_web >=0.1.0-dev.4 depends on firebase_core ^0.7.0 and firebase_check depends on firebase_core >=0.8.0-1.0.nullsafety.0 <0.8.0-2.0.nullsafety.0, firebase_messaging_web >=0.1.0-dev.4 is forbidden.

So, because firebase_check depends on firebase_messaging_web ^0.1.0-dev.5, version solving failed.
pub get failed (1; So, because firebase_check depends on firebase_messaging_web ^0.1.0-dev.5, version solving failed.)
exit code 1
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale ru-KZ)
    • Flutter version 1.25.0-8.3.pre at /Users/eldar/flutter
    • Framework revision 5d36f2e7f5 (13 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • D2F6CFC4-1622-483F-B3CA-B2BAF5038FAE • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-0 (simulator)

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
name: firebase_check
description: A new Flutter project.

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  meta: ^1.0.4
  flutter:
    sdk: flutter
  firebase_core: ">=0.8.0-1.0.nullsafety.0 <0.8.0-2.0.nullsafety.0"
  firebase_core_platform_interface: ">=4.0.0-1.0.nullsafety.0 <4.0.0-2.0.nullsafety.0"
  firebase_messaging_platform_interface: ^1.0.0-dev.10
  firebase_messaging_web: ^0.1.0-dev.5

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^5.0.0-nullsafety.2
  plugin_platform_interface: ^1.0.2
  async: ^2.4.2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.messaging
        pluginClass: FlutterFirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin
      macos:
        pluginClass: FLTFirebaseMessagingPlugin
      web:
        default_package: firebase_messaging_web
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @eldarkk 
Are you running the same `pubspec.yaml` as in the example?
The messaging dev version doesn't have a nullsafety version yet, you can just use:
```yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flutter_local_notifications: ^3.0.3
  http: ^0.12.2
```
Does this solve the issue for you?
Thank you
