### ISSUE TITLE
Android Firebase dependencies after Dependency Upgrade 0.5.0 to 0.7.0

### ISSUE THREAD

**Issue by Beautylivery** [FirebaseExtended/flutterfire#4848]
Hello together,

i updated a lot of my pubspec.yaml recently. In the Firebase area i moved up the following components from #version to version 

```
firebase_core: ^0.7.0 # ^0.5.0 
  firebase_auth: ^0.20.0+1 # ^0.18.0+1
  firebase_storage: ^7.0.0 # ^4.0.0
  cloud_firestore: ^0.16.0 #^0.14.0+2
```

After this my Android build does not work any longer (iOS) is ok ... after some POD handling.
I assume something similar is for Android Graddle necessary but all the basics i followed did not lead me anywhere.

This is the Error i receive in VS Code

```
Gradle sync failed: Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
            Problems reading data from Binary store in /private/var/folders/mw/s9362rr10qv43x_yh6qgm17w0000gn/T/gradle8805841490318013448.bin offset 286370 exists? true
            Consult IDE log for more details (Help | Show Log) (25 s 303 ms)
```

And a little better one in Android Studio 4.1

```
Gradle sync failed: Problems reading data from Binary store in /private/var/folders/mw/s9362rr10qv43x_yh6qgm17w0000gn/T/gradle1329056569736096566.bin offset 296201 exists? true
                Corrupt serialized resolution result. Cannot find selected module (224) for constraint platform-runtime -> com.google.firebase:firebase-iid:21.0.1
                Consult IDE log for more details (Help | Show Log) (10 m 18 s 294 ms)
```
Getting also a different issue after another attempt with VS Code

```
 Note: /Users/kaibaier/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.7.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Problems reading data from Binary store in /private/var/folders/mw/s9362rr10qv43x_yh6qgm17w0000gn/T/gradle3299415366350440389.bin offset 0 exists? true

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

Here are some additional information on my setup that might can help.
Flutter Doctor 

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale de-DE)
    • Flutter version 1.22.6 at /Users/kaibaier/development/flutter
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/kaibaier/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/kaibaier/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Redmi Note 8 (mobile) • 18d3ce30 • android-arm64 • Android 10 (API 29)
```

All depdendencies

```
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^5.0.1+1
  cupertino_icons: ^1.0.0 #^0.1.3
  firebase_core: ^0.7.0 # ^0.5.0 
  firebase_auth: ^0.20.0+1 # ^0.18.0+1
  firebase_storage: ^7.0.0 # ^4.0.0
  cloud_firestore: ^0.16.0 #^0.14.0+2
  provider: ^4.3.3 #^4.3.2
  flutter_spinkit: ^4.1.2+1
  flutter_vector_icons: ^0.2.1
  intl: ^0.16.1
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21 #^0.6.7+11
  searchable_dropdown: ^1.1.3
  flutter_colorpicker: ^0.3.5 #^0.3.4
  flutter_masked_text: ^0.8.0
  shared_preferences: ^0.5.12+4 #^0.5.8
  path_provider: ^1.6.27 #^1.6.11
  table_calendar: ^2.3.3 #^2.2.3
  url_launcher: ^5.7.10 #^5.6.0
  google_maps_flutter: ^1.1.1 #^0.5.32
  flutter_google_places: ^0.2.6
  http: ^0.12.2 #^0.12.1
  uuid: ^2.2.2 #^2.0.4
  flutter_appcenter_bundle: ^3.2.0+2
  preload_page_view: ^0.1.4
  device_preview: ^0.5.5 #^0.4.8
  wakelock: ^0.2.1+1 #^0.1.4+2
```

And here are also some insights on my gradle files

```
dependencies {
    classpath 'com.android.tools.build:gradle:4.1.2' // 3.5.1
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath 'com.google.gms:google-services:4.3.4' // 4.3.3
}
```

Here is my Gradle Version and i use currently build tools 4.1.2

```
------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          9.0.4 (Oracle Corporation 9.0.4+11)
OS:           Mac OS X 10.16 x86_64
```

I also posted the issue in Stackoverflow
[Question here](https://stackoverflow.com/questions/65928860/flutter-issues-with-android-firebase-dependencies-after-dependency-upgrades
)
but i assume it fits here better.

Thank you

Greetings

Kai
