### ISSUE TITLE
[📚] Broken migration guide depencies

### ISSUE THREAD

**Issue by glenfordwilliams** [FirebaseExtended/flutterfire#4885]
https://firebase.flutter.dev/docs/migration/#2-update-firebase-plugins

Migration guide currently has 

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.8.0-nullsafety.1"
  # Newly reworked plugins covered by this migration guide:
  firebase_auth: "^0.21.0-nullsafety.0"
  firebase_crashlytics: "^0.5.0-1.0.nullsafety.1"
  cloud_firestore: "^0.16.0"
  cloud_functions: "^0.9.1-nullsafety.1"
  firebase_storage: "^7.0.0"
  firebase_messaging: "^8.0.0-dev.14"
  firebase_remote_config: "^0.8.0-dev.0"
  # Updated to work with new core only plugins (no new changes):
  firebase_admob: "^0.11.0+1"
  firebase_analytics: "^7.0.1"
  firebase_database: "^6.0.0"
  firebase_dynamic_links: "^0.7.0+1"
  firebase_in_app_messaging: "^0.3.0+1"
  firebase_performance: "^0.5.0+1"
```

but using that exact combination results in a new project

```
Because no versions of firebase_core match >0.8.0-nullsafety.1 <0.9.0 and firebase_core 0.8.0-nullsafety.1 depends on firebase_core_platform_interface ^4.0.0-nullsafety.0, firebase_core ^0.8.0-nullsafety.1 requires firebase_core_platform_interface ^4.0.0-nullsafety.0.
And because firebase_messaging >=8.0.0-dev.13 depends on firebase_core_platform_interface ^3.0.1, firebase_core ^0.8.0-nullsafety.1 is incompatible with firebase_messaging >=8.0.0-dev.13.
So, because testy depends on both firebase_messaging ^8.0.0-dev.14 and firebase_core ^0.8.0-nullsafety.1, version solving failed.
Running "flutter pub get" in testy...                                   
pub get failed (1; So, because testy depends on both firebase_messaging ^8.0.0-dev.14 and firebase_core ^0.8.0-nullsafety.1,
version solving failed.)

```

flutter doctor

```
04:27:48 kingwill101@kingwill101-Inspiron-5491-2n1 testy ±|dev ✗|→ flutter doctor -v
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-8.3.pre at /home/kingwill101/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

⣻Error 1 retrieving device properties for ro.product.cpu.abi:
adb: insufficient permissions for device: missing udev rules? user is in the plugdev group
See [http://developer.android.com/tools/device.html] for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/kingwill101/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/kingwill101/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Android Studio
    • Android Studio at /home/kingwill101/Documents/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/kingwill101/Documents/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-ultimate/269
    • Flutter plugin version 53.0.5
    • Dart plugin version 203.6912

[✓] Connected device (2 available)
    • G0011J0594631QKK (mobile) • G0011J0594631QKK • android-arm    • Android null (API null)
    • Chrome (web)              • chrome           • web-javascript • Chromium 88.0.4324.96 snap

• No issues found!
```
