### ISSUE TITLE
[cloud_firestore] Stream connectionState stay waiting until app crashes in iOS Simulator

### ISSUE THREAD

**Issue by rsixel** [FirebaseExtended/flutterfire#4999]
Same on iOS 13.3 iPhone Promax 11 Simulator

flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on Mac OS X 10.14.6 18G103 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.53.0)
[✓] Connected device (2 available)
   ....
! Doctor found issues in 2 categories.
```
Snippet:
```
return new StreamBuilder<QuerySnapshot>(
    stream: FirebaseFirestore.instance
        .collection('users/${user.uid}/pedidos')
        .orderBy('entrega')
        .snapshots(),
    builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
      if (snapshot.hasError) {
        return PlatformText('Something went wrong');
      }

      // Stay entering this if statement several times until crash
      if (snapshot.connectionState == ConnectionState.waiting) {
        return Center(child: PlatformCircularProgressIndicator());
      }


```
pubspec.yml:
```
...
environment:
  sdk: '>=2.12.0-259.8.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.8.0-1.0.nullsafety.0
  firebase_core_platform_interface: ^4.0.0-1.0.nullsafety.0
  firebase_auth: ^0.21.0-1.1.nullsafety.1
  cloud_firestore: ^0.17.0-1.0.nullsafety.0

...
```
_Originally posted by @rsixel in https://github.com/FirebaseExtended/flutterfire/issues/4749#issuecomment-774819245_
