### ISSUE TITLE
🐛 [firebase_analytics] dependency issues

### ISSUE THREAD

**Issue by erf** [FirebaseExtended/flutterfire#5271]
## Bug report

**Describe the bug**

I get an dependency error with google_fonts 2.0.0 and firebase_analytics 7.1.0.

Because no versions of google_fonts match >2.0.0 <3.0.0 and google_fonts 2.0.0 depends on http ^0.13.0, google_fonts ^2.0.0 requires http ^0.13.0.
And because firebase >=5.0.3 <9.0.0 depends on http >=0.11.3 <0.13.0, google_fonts ^2.0.0 is incompatible with firebase >=5.0.3 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, google_fonts ^2.0.0 is incompatible with firebase_analytics >=7.1.0.
So, because xxx depends on both firebase_analytics ^7.1.0 and google_fonts ^2.0.0, version solving failed.
Running "flutter pub get" in xxx...
pub get failed (1; So, because xxx depends on both firebase_analytics ^7.1.0 and google_fonts ^2.0.0,
version solving failed.)

Is there a way to solve this, or could you improve the dependencies?

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.1 20D74 darwin-arm, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] Connected device (1 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.0
  firebase_crashlytics: ^1.0.0
  firebase_analytics: ^7.1.0
  firebase_auth: ^1.0.0
  firebase_messaging: ^9.0.0
  cloud_firestore: ^1.0.0
  shared_preferences: ^2.0.3
  rxdart: ^0.26.0
  package_info: ^2.0.0
  google_fonts: ^2.0.0
  geolocator: ^7.0.1
  path_provider: ^2.0.1
  intl: ^0.17.0
  charts_flutter: ^0.9.0
  csv_localizations: ^1.0.0
  google_maps_flutter: ^2.0.1
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_native_timezone: ^1.0.10
  sign_in_with_apple: ^3.0.0
  google_sign_in: ^5.0.0
  app_review:
    git:
      url: git@github.com:erf/app_review.git
      ref: package_info
  purchases_flutter: ^3.0.0
  flutter_icons: ^1.1.0
  flutter_markdown: ^0.6.0
  toml_localizations: ^1.0.0
  flutter_riverpod: ^0.13.1
  flutter_mailer: ^1.0.1
  share: ^2.0.0
  json_annotation: ^4.0.0

dependency_overrides:
  intl: ^0.17.0
  #firebase: ^9.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  build_runner: ^1.11.5
  json_serializable: ^4.0.2

```

</details>

---
