### ISSUE TITLE
🐛 [cloud_firestore] A problem occurred evaluating root project 'cloud_firestore' (cannot build appbundle)

### ISSUE THREAD

**Issue by MilesAdamson** [FirebaseExtended/flutterfire#5285]
## Bug report

Since upgrading to the most recent version of flutter stable, I cannot build an appbundle with cloud firestore. 

```
* What went wrong:
A problem occurred evaluating root project 'cloud_firestore'.
> Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'cloud_firestore'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1s


The plugin cloud_firestore could not be built due to the issue above.

C:\Users\miles\IdeaProjects\ironsight_mobile>

```

### Steps to reproduce

`flutter build appbundle` on flutter version 2.0.1 (most recent stable release)

---

### Flutter doctor

```
C:\Users\miles\IdeaProjects\ironsight_mobile>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.804], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.53.2)
[√] Connected device (3 available)

```

---

**Comment by markusaksli-nc** [comment]
Hi @MilesAdamson 
Could you please use the latest version `cloud_firestore: ^1.0.1` and run `flutter clean` before you build?
Thank you

**Comment by MilesAdamson** [comment]
I can reproduce this from the empty example project. Pubspec is as follows:

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.1
  firebase_auth: ^1.0.1
  flutter_spinkit: ^3.1.0
  provider: ^4.3.3
  meta: ^1.1.6
  package_info: ^0.4.0+3
  equatable: ^0.2.3
  flutter_secure_storage: ^3.2.0
  json_serializable: ^3.1.0
  signature: ^2.0.0
  intl: ^0.17.0
  pull_to_refresh: 1.2.0
  flutter_svg: 0.19.0
  sentry: ^4.0.6
  google_maps_flutter: ^0.5.21+15
  permission_handler: ^6.0.1+1
  device_info: 0.4.0+2
  image_picker: ^0.7.2
  photo_view: 0.8.0
  flutter_typeahead: 1.7.0
  retry: 3.0.0+1
  connectivity: ^3.0.2
  flutter_markdown: ^0.5.0
  firebase_remote_config: 0.3.1+1
  flutter_redux: 0.7.0
  path_provider: ^2.0.1
  file_picker: ^3.0.0
  open_file: ^3.1.0
  uuid: ^3.0.1
  community_material_icon: ^5.4.55
  json_at: 1.0.4
  synchronized: ^2.2.0+2
```

Build an appbundle fails with the following (a different error than my actual project for some reason). I am not able to upgrade to `cloud_firestore: ^1.0.1` on my actual project due to some dependency hell. 

```
C:\Users\miles\IdeaProjects\untitled6>flutter clean
Deleting build...                                                   12ms
Deleting .dart_tool...                                               6ms
Deleting .packages...                                                1ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms

C:\Users\miles\IdeaProjects\untitled6>flutter build appbundle
Running "flutter pub get" in untitled6...                          952ms

 Building with sound null safety 


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\miles\IdeaProjects\untitled6\build\app\intermediates\bundle_manifest\release\processReleaseManifest\bundle-manifest\AndroidManifest.xml:13: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        19.5s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...                            /
C:\Users\miles\IdeaProjects\untitled6>
```

If I delete all the other plugins from my pubspec, it succeeds in building an appbundle:

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.1
  firebase_auth: ^1.0.1
```

```
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        29.1s
√ Built build\app\outputs\bundle\release\app-release.aab (16.7MB).
```

So I suspect this is some issue with cloud firestore and another plugin. For now I am going to downgrade flutter back to where it was because some other plugins I depend on cannot be used with the latest versions of the firebase plugins.
