### ISSUE TITLE
🐛 [firebase_messaging] Error calling Firebase.initializeApp running iOS using firebase_messaging 9.0.0

### ISSUE THREAD

**Issue by tkeithblack** [FirebaseExtended/flutterfire#5286]
## Bug report

Error calling Firebase.initializeApp running under iOS. This error began happening after upgrading to firebase_messaging 9.0.0.

This error does not occur running under Android.

NOTE: The actual failure is when initializeApp calls initializeCore.

Error Log:
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
[38;5;244m#0      MethodChannel._invokeMethod[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#1      MethodChannel.invokeListMethod[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#2      MethodChannelFirebase._initializeCore[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#3      MethodChannelFirebase.initializeApp[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#4      Firebase.initializeApp[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#5      _appInitializations[39;49m
[38;5;244m<asynchronous suspension>[39;49m
#6      main (package:phonelynkflutter/main.dart:24<…>

### Steps to reproduce

Build flutter app with firebase_messaging 9.0.0.

```
void main() async {
  await Firebase.initializeApp();
 runApp(MyApp());
}
```

This creates the crash show above.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Flutter doctor:
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-US)
    • Flutter version 2.0.1 at /Users/keithblack/GitHub/flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/keithblack/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 12 Pro (mobile)       • A19880B0-9C8C-4511-A724-BB7F7710B466 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 88.0.4324.192

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^6.0.1
  contacts_service: ^0.4.6
  flutter_contact:
    path: /Users/keithblack/GitHub/flutter_contact # updated dependencies: sunny_dart: ^0.6.0+4 & uuid: ^3.0.1
  provider: ^5.0.0
  json_annotation: ^4.0.0
  intl: ^0.16.1
  get_it: ^6.0.0
  dio: ^4.0.0-beta7
  dio_cookie_manager: ^2.0.0-beta1
  flutter_secure_storage: ^4.1.0
  shared_preferences: ^2.0.3
  incrementally_loading_listview: ^0.3.0
  audioplayers: ^0.17.4
  sprintf: ^6.0.0
  badges: ^1.2.0
  jwt_decode: ^0.2.0
  logging: ^0.11.4
  package_info: ^2.0.0
  device_id: ^0.2.0
  flutter_layout_grid: ^0.11.5
  adaptive_dialog: ^0.10.0+5
  link_text: ^0.2.0
  flutter_local_notifications: ^5.0.0-nullsafety.1
  fluttertoast: ^7.1.5
  cached_network_image: ^2.5.1
  photo_view: ^0.10.3
  bubble: ^1.1.9+1
  image_picker: ^0.7.2
  pedantic: ^1.11.0
  synchronized: ^3.0.0
  url_launcher: ^6.0.2
  purchases_flutter: ^3.0.0
  flutter_masked_text: ^0.8.0
  flutter_dtmf: ^1.0.0
  share: ^2.0.0
  popup_menu: ^1.0.5
  flutter_sound: ^8.0.0+2
  toggle_switch: ^0.1.8
  linkwell:
    path:  /Users/keithblack/GitHub/linkwell
  bubble_tab_indicator: ^0.1.6
  firebase_messaging: ^9.0.0
  flutter_apns: 
    path:  /Users/keithblack/GitHub/flutter-apns

  # Custom packages
  flutter_apns_env:
    path:  /Users/keithblack/GitHub/flutter_apns_env
  flutter_twilio_voice:
    path:  /Users/keithblack/GitHub/flutter_twilio_voice

```

</details>

---
