### ISSUE TITLE
🐛 [cloud_firestore] 'Object.==' and Mockito

### ISSUE THREAD

**Issue by radvansky-tomas** [FirebaseExtended/flutterfire#5288]
I am trying to mock flutter fire plugin using Mockito, however generation fails because of using 'Object.==' inside many flutter fire classes. I reported it to Mockito plugin, however they doubt you should be using it.

Any input from your end ?

https://github.com/dart-lang/mockito/issues/354

**Comment by mockturtl** [comment]
This is also relevant to `firebase_auth`.

With `@GenerateMocks([FirebaseAuth])`, the code generation succeeds, but the analyzer finds an `invalid_implementation_override` error in the generated class for `FirebaseApp`.

```yaml
# pubspec.yaml
dependencies:
  flutter:
    sdk: flutter  # 2.0.2
  firebase_auth: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  mockito: ^5.0.2
```

```sh
$ dart run build_runner build
```

```dart
// my_test_mocks.dart
// Mocks generated by Mockito 5.0.2 from annotations
// in my_test.dart.
// Do not manually edit this file.
...
class _FakeFirebaseApp extends _i1.Fake implements _i2.FirebaseApp {}
```

```
error • 'Object.==' ('bool Function(Object)') isn't a valid concrete implementation of 'FirebaseApp.==' ('bool Function(dynamic)') at ... • (invalid_implementation_override)
```

https://github.com/dart-lang/mockito/issues/354#issuecomment-794872821

> I suggest opening bugs against those packages, perhaps asking why they expanded the parameter type on the == operator. It may be accidental.
