### ISSUE TITLE
🐛 [ Firebase Message] Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.

### ISSUE THREAD

**Issue by Bac-Pham** [FirebaseExtended/flutterfire#5320]
Describe the bug
I was having trouble updating firebase message
```
E/flutter (29231): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.
E/flutter (29231): Receiver: null
E/flutter (29231): Tried calling: toRawHandle()
E/flutter (29231): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (29231): #1      MethodChannelFirebaseMessaging.registerBackgroundMessageHandler (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:181:42)
E/flutter (29231): #2      FirebaseMessagingPlatform.onBackgroundMessage= (package:firebase_messaging_platform_interface/src/platform_interface/platform_interface_messaging.dart:107:14)
E/flutter (29231): #3      FirebaseMessaging.onBackgroundMessage (package:firebase_messaging/src/messaging.dart:103:31)
```
--------------------
file `pubspec.yaml`
```yaml 
environment:
  sdk: ">=2.7.0 <3.0.0"

module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.0
  google_maps_flutter: 1.0.3
  google_map_location_picker: 4.0.0
  mvc_pattern: 6.3.0
  global_configuration: 1.6.0
  http: 0.12.2
  html: 0.14.0+4
  shared_preferences: ^2.0.4
  flutter_html: 1.2.0
  #laichi change 2020/2/25
  #flutter_svg: 0.18.1
  location: 3.0.2
  webview_flutter: ^1.0.7
  url_launcher: 5.7.7
  cached_network_image: ^2.5.0
  fluttertoast: 4.0.1
  flutter_staggered_grid_view: 0.3.2
  intl_utils: ^1.8.0
  carousel_slider: 2.3.1
  cloud_firestore: ^0.16.0
  image_picker: ^0.6.7+21
  firebase_storage: ^7.0.0
  photo_view: ^0.10.3
  numberpicker: ^1.3.0
  intl_translation: ^0.17.8
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_messaging: any #^8.0.0-dev.15
  google_sign_in: ^4.5.9
  sign_in_with_apple: ^2.5.2
  crypto: ^2.1.5
  flutter_facebook_auth: ^2.0.2
  flutter_svg: ^0.19.3
  #flutter_local_notifications: ^4.0.1+2
  flutter_local_notifications: ^3.0.0
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  #firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
```
-----------
please help me
