### ISSUE TITLE
🐛 [firebase_crashlytics] 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by MATTYGILO** [FirebaseExtended/flutterfire#5440]
## Bug report

When I run on iOS I get this error from Crashlytics

FLTFirebaseCrashlyticsPlugin.h:8:9: 'Flutter/Flutter.h' file not found
FLTFirebaseCorePlugin.h:8:9: 'Flutter/Flutter.h' file not found

### Steps to reproduce

I am using the master channel version of flutter
I am using the master channel version of crashlytics
I am using a real device

`  
firebase_crashlytics:
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_crashlytics/firebase_crashlytics
`
### Expected behavior

To run

## Additional context

![Screenshot 2021-03-23 at 17 51 25](https://user-images.githubusercontent.com/34808802/112194152-7ffb5b00-8c00-11eb-835e-a8ddeb4949ff.png)

### Flutter doctor
<details><summary>

</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.199, on Mac OS X 10.15.6 19G2021
    darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>

</summary>

```
  cloud_firestore: #^1.0.1
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      path: packages/cloud_firestore/cloud_firestore
  cloud_functions: #^1.0.0
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      path: packages/cloud_functions/cloud_functions
  firebase_auth: #^1.0.1
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_auth/firebase_auth
  firebase_analytics: ^7.1.1
  firebase_storage: #^8.0.0
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_storage/firebase_storage
  firebase_messaging: #^9.0.0
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_messaging/firebase_messaging
  firebase_core: ^1.0.1
  firebase_dynamic_links: #^0.8.0
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_dynamic_links
  firebase_remote_config: #^0.6.0
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_remote_config/firebase_remote_config
  firebase_crashlytics: #^1.0.0
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_crashlytics/firebase_crashlytics
```

</details>

---
