### ISSUE TITLE
firebase_messaging 9.0.1: error with Firebase.initializeApp()

### ISSUE THREAD

**Issue by moderncodr** [FirebaseExtended/flutterfire#5460]
Hi guys,

according to https://pub.dev/packages/firebase_messaging, with **9.0.1**, there is no extra step to integrate it in flutter, it didn't mention to call Firebase.initializeApp().

but however, when I try to launch the app, it gives the error:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()`

then if I add the call, I have the error saying:
`Firebase has not been correctly initialized. Have you added the "google-services.json" file to the project?
`
I also tried to put the file in the android/app folder, same error.

I have created the project with flutter 2.0.1 and latest android studio. 

cheers

**Comment by markusaksli-nc** [comment]
Hi @moderncodr 
As mentioned at https://pub.dev/packages/firebase_messaging#getting-started

> To use this plugin, please visit the [Cloud Messaging Usage documentation](https://firebase.flutter.dev/docs/messaging/overview/)

Please see
https://firebase.flutter.dev/docs/overview
https://firebase.flutter.dev/docs/messaging/overview
https://firebase.flutter.dev/docs/messaging/apple-integration

Thank you

**Comment by moderncodr** [comment]
Hi @mark-veenstra thanks for your reply! yes, I have indeed followed the links. In our case, we tried both with android studio to launch and use "flutter run --no-sound-null-safety", as we have mixed code.

I still have the problem. here are the dependencies:
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.1
  cached_network_image: ^2.5.1
  flutter_html: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.2
  date_format: ^2.0.2
  http: ^0.13.1
  intl: ^0.17.0
  firebase_core: ^1.0.2
  oauth2: ^2.0.0
  google_sign_in: ^5.0.1
  shared_preferences: 2.0.5
  share: ^2.0.1
  mdi: 4.0.0
  sign_in_with_apple: ^3.0.0
  device_info: 2.0.0
  firebase_analytics: ^7.1.1
  web_socket_channel: ^2.0.0
  uuid: 3.0.1
  connectivity: ^3.0.3
  firebase_messaging: ^9.0.1
  carousel_slider: ^3.0.0
  page_indicator: ^0.4.1
  package_info: ^2.0.0
  in_app_review: ^2.0.1
  vibration: ^1.7.3
  charts_flutter: ^0.10.0
  provider: ^5.0.0
  shimmer: ^1.1.2
```
