### ISSUE TITLE
🐛 [Firebase_Messaging] Android - onLaunch callback not working for Data Messages received in onBackgroundMessage callback

### ISSUE THREAD

**Issue by K247Sagar** [FirebaseExtended/flutterfire#5643]
## Bug report

**[Android] Only, onLaunch not getting called on notification tap when app is in background for notification type is of type Data Messages .
**

### Steps to reproduce

1. Send notification of type Data Messages 
2. e.g. {data: {account_id: 373, reference_no: 301, id: xyz, no: 2249, body: Item has been edited as of 04/02/2021 15:51:40., title: Item Edited, click_action: FLUTTER_NOTIFICATION_CLICK, created_on: 2021-04-02 10:21:43}}
3. Kill the app and again send notification.
4. click on notification in drawer. 
5. onLaunch() not getting called

### Expected behavior

on Launch callback should get called on notification tap when app is in background.
---

## Additional context

onLaunch is working when app is in foreground.

---

### Flutter doctor

```
doctor --verbose
[✓] Flutter (Channel stable, 1.22.3, on Linux, locale en_IN)
    • Flutter version 1.22.3 at /home/sagar/flutter
    • Framework revision 8874f21e79 (5 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/sagar/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Moto G Play (mobile) • ZY223J4GN7 • android-arm • Android 7.1.1 (API 25)

```

</details>

---

### Flutter dependencies

```
 firebase_messaging:
    git:
      url: https://github.com/amarthombare/flutterfire.git
      path: packages/firebase_messaging
      ref: firebase_messaging-v7.0.3_unregister

  flutter_local_notifications: ^4.0.1+1

  implementation 'com.google.firebase:firebase-messaging:20.1.0'
```

</details>

---
