### ISSUE TITLE
when build on iOS  i get firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 9.1.2, which depends on           Firebase/Messaging (= 7.3.0)

### ISSUE THREAD

**Issue by fnoceda** [FirebaseExtended/flutterfire#6143]
When i build on iOS i get the error 
```
CocoaPods could not find compatible versions for pod "Firebase/Messaging":
      In Podfile:
        firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 9.1.2, which depends on
          Firebase/Messaging (= 7.3.0)
```
## Fluter Doctor
```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.5 19F101 darwin-x64, locale es-419)
    • Flutter version 2.0.4 at /Users/francisconoceda/Documents/flutter
    • Framework revision b1395592de (6 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/francisco/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone (mobile) • bba6da26e86b8da102d3220edf7133eef4af5f74 • ios            • iOS 14.4.2
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```
## pubspec.yaml
```yaml
name: esprestadores
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  tflite_flutter: ^0.8.0
  camera: ^0.5.8+5
  path_provider: ^2.0.1
  path:
  
  firebase_core: ^1.0.4
  firebase_ml_vision: ^0.12.0+1
  firebase_messaging: ^9.1.2
  image:
  rounded_loading_button: ^1.0.0
  get: ^4.1.4
  get_storage: ^2.0.2
  shared_preferences: ^0.5.6+3
  flutter_swiper: ^1.1.6
  flutter_secure_storage: ^3.3.3
  http: ^0.13.1
  url_launcher: ^6.0.3
  font_awesome_flutter: ^8.8.1
  map_launcher: ^0.12.2
  flutter_phoenix: "^0.1.0" 
  cached_network_image: ^2.3.2+1
  find_dropdown: ^0.2.1
  flutter_local_notifications: ^5.0.0+1
  rxdart: ^0.23.1
  timezone: ^0.7.0
  sqflite: ^1.3.0
  

  table_calendar: ^2.3.1
  expandable: ^4.1.4
  
  timeline_list: ^0.0.3
  dropdown_search: ^0.5.0
  crypto: any
  barcode_scan2: ^4.1.3


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
 android: "launcher_icon"
 ios: true
 image_path: "assets/img/logo.png"
 adaptive_icon_background: "assets/img/logo.png"
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/img/
    - assets/json/
    - assets/facenet/mobilefacenet.tflite
```
## PodFile
```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
pod 'Firebase/MLVisionFaceModel'
```
