### ISSUE TITLE
Runtime Exception while getting firebase notification.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#615]
I was planning to add messaging to my Flutter app, I added the fire Flutter package. Added `google-services.json` to Android project and build the project. The project ran on android properly except I got runtime exception when app receives notification. I think this is because of different  dependency versions.

Here is the list of the packages that I am using on my project, I think all are up to date.

```yml
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: "^0.5.20"
  firebase_messaging: "^2.0.0"
  firebase_analytics: "^1.0.3"
  firebase_admob: "^0.6.1"
  firebase_core: "^0.2.5+1"
  firebase_database: "^1.0.4"
  firebase_storage: "^1.0.3"
  google_sign_in: "^3.2.1"
  image_picker: "^0.4.10"
  url_launcher: "^4.0.1"
  sqflite: "^0.12.1"
  path: "^1.6.2"
  path_provider: "^0.4.1"
  async_loader: "^0.1.2"
  flutter_image: "^1.0.0"
  flutter_search_bar: "^2.0.7"
  shared_preferences: "^0.4.3"
  groovin_material_icons: ^1.1.5`
```

Here is the issue that I am getting when I receive notification.

```
java.lang.NoSuchMethodError: No static method zzah()Lcom/google/firebase/iid/zzau; in class Lcom/google/firebase/iid/zzau; or its super classes (declaration of 'com.google.firebase.iid.zzau' appears in /data/app/com.brainants.meroshare-PlTXYg9vGisDS0Gq8tbcVA==/base.apk)
E/AndroidRuntime(23824):        at com.google.firebase.messaging.FirebaseMessagingService.zzb(Unknown Source:7)
E/AndroidRuntime(23824):        at com.google.firebase.iid.zzb.onStartCommand(Unknown Source:16)
E/AndroidRuntime(23824):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3802)
E/AndroidRuntime(23824):        at android.app.ActivityThread.access$1800(ActivityThread.java:207)
E/AndroidRuntime(23824):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
E/AndroidRuntime(23824):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23824):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(23824):        at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(23824):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23824):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(23824):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/OPDiagnose(23824): getService:OPDiagnoseService NULL
D/OSTracker(23824): OS Event: crash
I/Process (23824): Sending signal. PID: 23824 SIG: 9
Lost connection to device.
```
