### ISSUE TITLE
FirebaseMessaging.instance.getToken - FATAL EXCEPTION

### ISSUE THREAD

**Issue by davidp918** [FirebaseExtended/flutterfire#6150]
When I execute FirebaseMessaging.instance.getToken()
```
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
lib\main.dart:1
√ Built build\app\outputs\flutter-apk\app-debug.apk.
I/Choreographer( 4022): Skipped 114 frames!  The application may be doing too much work on its main thread.
Connecting to VM Service at ws://127.0.0.1:7376/yWup3MxyeT0=/ws
I/FLTFireBGExecutor( 4022): Creating background FlutterEngine instance, with args: [--start-paused, --enable-dart-profiling]
D/EGL_emulation( 4022): eglCreateContext: 0xeac01ba0: maj 2 min 0 rcv 2
D/EGL_emulation( 4022): eglCreateContext: 0xeac19990: maj 2 min 0 rcv 2
D/HostConnection( 4022): HostConnection::get() New Host Connection established 0xeac1dc80, tid 4382
D/HostConnection( 4022): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_2
D/EGL_emulation( 4022): eglMakeCurrent: 0xeac19990: ver 2 0 (tinfo 0xab5531b0) (first time)
E/AndroidRuntime( 4022): FATAL EXCEPTION: pool-19-thread-1
E/AndroidRuntime( 4022): Process: com.dp.kzstats, PID: 4022
E/AndroidRuntime( 4022): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/Metadata;
E/AndroidRuntime( 4022): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin.lambda$getToken$1$FlutterFirebaseMessagingPlugin(FlutterFirebaseMessagingPlugin.java:165)
E/AndroidRuntime( 4022): 	at io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingPlugin$CIEVVSZZupyLaxqSu4HKcRkuppw.call(Unknown Source:4)
E/AndroidRuntime( 4022): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/AndroidRuntime( 4022): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 4022): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 4022): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 4022): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.Metadata" on path: DexPathList[[zip file "/data/app/~~yd28OBSBYxFU9hWVgmvl6w==/com.dp.kzstats-iexxqZTlAfuOZ6C_QhnQZg==/base.apk"],nativeLibraryDirectories=[/data/app/~~yd28OBSBYxFU9hWVgmvl6w==/com.dp.kzstats-iexxqZTlAfuOZ6C_QhnQZg==/lib/x86, /data/app/~~yd28OBSBYxFU9hWVgmvl6w==/com.dp.kzstats-iexxqZTlAfuOZ6C_QhnQZg==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime( 4022): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime( 4022): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
```
Flutter doctor
```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\davidp\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\davidp\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\davidp\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7142.45
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\davidp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
```
pubspec.yaml
```
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  flutter_svg: ^0.22.0
  flutter_bloc: ^7.0.0
  flutter_easyrefresh: ^2.2.1
  hydrated_bloc: ^7.0.0
  hive: ^2.0.3
  crypto: ^3.0.1
  archive: ^3.1.2
  xml: ^5.1.0
  path_provider: ^2.0.1
  characters: ^1.1.0
  flutter_pagewise: ^2.0.1
  shared_preferences: ^2.0.5
  google_fonts: ^2.0.0
  url_launcher: ^6.0.3
  fl_chart: ^0.36.0
  provider: ^5.0.0
  material_floating_search_bar: ^0.3.4
  implicitly_animated_reorderable_list: ^0.4.0
  substring_highlight: ^1.0.26
  percent_indicator: ^3.0.1

  firebase_messaging: ^9.1.4
  firebase_core: ^1.1.0
  flutter_local_notifications: ^5.0.0+4
  
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1
  community_material_icon: ^5.9.55
  evil_icons_flutter: ^0.5.0
  flutter_launcher_icons: ^0.9.0
```
