### ISSUE TITLE
🐛 [FirebaseCrashlytics]  Undefined symbol: _OBJC_CLASS_$_GULAppEnvironmentUtil

### ISSUE THREAD

**Issue by YowFung** [FirebaseExtended/flutterfire#6185]
I cannot build my flutter APP for ios and I got the error `Undefined symbol: _OBJC_CLASS_$_GULAppEnvironmentUtil` after I update the firebase_core and firebase_crashlytics plugins.

![image](https://user-images.githubusercontent.com/26346560/118775825-ed063680-b8b9-11eb-9301-65a3e8b57ab5.png)

**Comment by YowFung** [comment]
<details>
<summary>flutter doctor -v</summary>

```txt
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.6 at /Users/yowfung/Library/Flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yowfung/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/yowfung/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • yowfung (mobile)           • 00008101-00155CE23A50001E            • ios            • iOS 14.4.2
    • iPhone 12 Pro Max (mobile) • 61DABEEF-D0A3-412E-8594-E9A7E2F62B5C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!
```
</details>

<details>
<summary>pubspec.yaml</summary>

```yaml
name: vdirector
description: IP matrix controllor.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: "1.5.8+11"

environment:
  sdk: ">=2.7.0 <3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_interfaces_plus:
    path: plugins/flutter_interfaces_plus
  intl: ^0.16.1
  provider: ^4.0.0
  path_provider: ^1.6.11
  toast: ^0.1.5
  drag_list: ^1.0.8
  sprintf: ^4.0.0
  flutter_webview_plugin: ^0.3.11
  http: ^0.13.1
  video_player: ^2.1.1
  url_launcher: ^5.7.8 
  package_info: ^0.4.0+2
  _fe_analyzer_shared: ^7.0.0
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.0.4
  flutter_widgets: ^0.1.12
  flutter_mailer: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  plugin_platform_interface: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/video/
    - assets/config.json
```
</details>
