### ISSUE TITLE
'GoogleUtilities/GULURLSessionDataResponse.h' file not found error

### ISSUE THREAD

**Issue by isuru18113** [FirebaseExtended/flutterfire#6346]
**I am facing this issue when I hit the run button. This problem occurred after I added Firebase features(Auth.firestore,core) to my app.** **How to fix this issue?**
```
Running Xcode build...
Xcode build done.                                           12.1s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[22659]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f72f5160) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1197c82b8). One of the two will be used. Which one is undefined.
    objc[22659]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f72f51b0) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1197c8308). One of the two will be used. Which one is undefined.
    2021-06-08 16:17:26.451 xcodebuild[22659:268104] warning:  The file reference for "Firebase.debug.xcconfig" is a member of multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    2021-06-08 16:17:26.451 xcodebuild[22659:268104] warning:  The file reference for "Firebase.release.xcconfig" is a member of multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    2021-06-08 16:17:26.456 xcodebuild[22659:268104] warning:  The file reference for "GoogleUtilities.debug.xcconfig" is a member of multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    2021-06-08 16:17:26.456 xcodebuild[22659:268104] warning:  The file reference for "GoogleUtilities.release.xcconfig" is a member of multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    ** BUILD FAILED **


Xcode's output:
↳
    gRPC-C++-gRPCCertificates-Cpp-hjozdpdaawootyfxculirogmlnok
    4 warnings generated.
    /Users/isuru/AndroidStudioProjects/crush_smile/ios/Pods/libwebp/src/enc/backward_references_enc.c:694:12: warning: variable 'best_offset' may be uninitialized when used here [-Wconditional-uninitialized]
              (best_offset << MAX_LENGTH_BITS) | (uint32_t)best_length;
               ^~~~~~~~~~~
    /Users/isuru/AndroidStudioProjects/crush_smile/ios/Pods/libwebp/src/enc/backward_references_enc.c:626:20: note: initialize the variable 'best_offset' to silence this warning
        int best_offset;
                       ^
                        = 0
    1 warning generated.
    /Users/isuru/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.4.0/ios/Classes/EmptyLogDelegate.m:25:17: warning: class 'EmptyLogDelegate' does not conform to protocol 'LogDelegate' [-Wprotocol]
    @implementation EmptyLogDelegate
                    ^
    /Users/isuru/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.4.0/ios/Classes/EmptyLogDelegate.m:25:17: note: add stubs for missing protocol requirements
    @implementation EmptyLogDelegate
                    ^
    1 warning generated.
    gRPC-C++-gRPCCertificates-Cpp-hjozdpdaawootyfxculirogmlnok
    /Users/isuru/AndroidStudioProjects/crush_smile/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m:36:9: fatal error: 'GoogleUtilities/GULURLSessionDataResponse.h' file not found
    #import <GoogleUtilities/GULURLSessionDataResponse.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    gRPC-C++-gRPCCertificates-Cpp-hjozdpdaawootyfxculirogmlnok
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

```

**Comment by isuru18113** [comment]
Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.3 20E232 darwin-arm, locale en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
    ! Error: Isuru’s iPhone is not connected. Xcode will continue when Isuru’s iPhone is connected. (code -13)
    ! Error: Sewmini’s iPhone is not connected. Xcode will continue when Sewmini’s iPhone is connected. (code -13)

• No issues found!
```

dependencies

```
dependencies:

  easy_localization: ^3.0.0 # localization for languages
  intl_phone_field: ^2.0.0
  pin_code_fields: ^7.0.0 #Pin code enter fields
  shared_preferences: ^2.0.5 # Flutter Shared preferences
  loading_indicator: ^2.0.1 # loading indicators
  font_awesome_flutter: ^9.0.0 #Icon packs
  video_player: ^2.1.1 # Flutter Video Player
  connectivity: ^3.0.3 # Flutter Connectivity checks
  data_connection_checker: ^0.3.4 #Check internet connection works
  image_picker: ^0.7.5+3 #Flutter Image Picker
  video_trimmer: ^0.4.0 # Video Trimmer
  translator: ^0.1.7 # Google Translator
  photo_view: ^0.11.1 #Image Viewer
  shimmer: ^2.0.0 # Loading Shimmer
  google_mobile_ads: 0.12.2+1 #Google ads
  flutter_slidable: ^0.6.0 #slidable for chat view
  flutter_swipe_action_cell: ^2.0.6 # Slide for chats
  swipe_to: ^0.0.1+8 # Swipe to reply
  pull_to_refresh: ^1.6.5 # Pull up Refresh
  flutter_spinkit: ^5.0.0 # Loading Indicator with controller
  flutter_chat_bubble: ^1.0.2 #Chat bubble
  tenor: ^1.0.8 #GIF Tenorflt
  flutter_staggered_grid_view: ^0.4.0 #Grid view
  smooth_page_indicator: ^0.2.3 #Page Indicator
  firebase_core: ^1.2.1 #firebase core
  firebase_auth: ^1.3.0 #firebase auth
  cloud_firestore: ^2.2.1 # firebase firestore
  extended_image: ^4.1.0 #PhotoEditor
  image_editor: ^1.0.0 #image editor
  image_crop: ^0.4.0 # image crop
```
