### ISSUE TITLE
[remote_config] values are empty on andorid

### ISSUE THREAD

**Issue by naumanahmed19** [FirebaseExtended/flutterfire#6801]
I am using remote config in my project but the values are empty. 

- I have tested with the old version of my project with`firebase_remote_config: ^0.0.6` and it's working fine. 
- I have also tried with a new project without installing extra packages,  and still the same issue although I am getting Firestore data just fine.
- Tested on both android emulators, phon with debugging and with build version.

```
   final RemoteConfig remoteConfig = RemoteConfig.instance;
    await remoteConfig.setConfigSettings(RemoteConfigSettings(
      fetchTimeout: const Duration(seconds: 10),
      minimumFetchInterval: const Duration(hours: 1),
    ));

   print(remoteConfig.getString('MYKEY');
```

### Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.5.0-6.0.pre.49, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.46.1)
[√] Connected device (3 available)

• No issues found!

```
</details>

---

### Flutter dependencies

```

environment:
  sdk: ">=2.7.0 <3.0.0"
  

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

 firebase_core: ^1.4.0
  firebase_remote_config: ^0.10.0+3
```
</details>

---
