### ISSUE TITLE
[firebase_core] [iOS] could not build module 'firebase_core'

### ISSUE THREAD

**Issue by DarkKnight1005** [FirebaseExtended/flutterfire#7183]
Error after firebase integration:
```
Xcode's output:
↳
    While building module 'firebase_core' imported from /Users/ayazpanahov/Documents/cap_mobile-master/ios/Runner/GeneratedPluginRegistrant.m:22:
    In file included from <module-includes>:1:
    In file included from /Users/ayazpanahov/Documents/cap_mobile-master/build/ios/Debug-iphoneos/firebase_core/firebase_core.framework/Headers/firebase_core-umbrella.h:13:
    In file included from /Users/ayazpanahov/Documents/cap_mobile-master/build/ios/Debug-iphoneos/firebase_core/firebase_core.framework/Headers/FLTFirebaseCorePlugin.h:11:
    /Users/ayazpanahov/Documents/cap_mobile-master/build/ios/Debug-iphoneos/firebase_core/firebase_core.framework/Headers/FLTFirebasePlugin.h:9:9: error: include of non-modular header inside framework module
    'firebase_core.FLTFirebasePlugin': '/Users/ayazpanahov/Documents/cap_mobile-master/build/ios/Debug-iphoneos/FirebaseCore/FirebaseCore.framework/Headers/FirebaseCore.h'
    [-Werror,-Wnon-modular-include-in-framework-module]
    #import "FirebaseCore.h"
            ^
    1 error generated.
    /Users/ayazpanahov/Documents/cap_mobile-master/ios/Runner/GeneratedPluginRegistrant.m:22:9: fatal error: could not build module 'firebase_core'
    #import <firebase_core/FLTFirebaseCorePlugin.h>
     ~~~~~~~^
    2 errors generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    note: Removed stale file
    '/Users/ayazpanahov/Library/Developer/Xcode/DerivedData/Runner-fsbkgrvkbqooehagsdflyjgomodn/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-E8A0874E9F12B2C01AF6E81F.sh'
```

The issue can be resolved if in ```GeneratedPluginRegistrant.m``` the 3rd line of the following block:
```objective-c
...
#if __has_include(<firebase_core/FLTFirebaseCorePlugin.h>)
#import <firebase_core/FLTFirebaseCorePlugin.h>
#else
@import firebase_core;
#endif
...
```
will be changed to
```objective-c
#import "FLTFirebaseCorePlugin.h"
```

However, editing the ```GeneratedPluginRegistrant.m``` is only possible if building purely with XCode, when building with flutter by ```flutter run``` command, then the previous file being overwritten by flutter and build error occurring again. 

**Expected behavior:**
A successful build for the iOS simulator

**All Flutter Packages:**
```yaml
dependencies:
  flutter_svg: ^0.22.0
  flutter_inappwebview: ^5.3.2
  getwidget: ^2.0.3
  otp_text_field: ^1.1.1
  pin_code_fields: ^7.3.0
  dio: ^4.0.0
  provider: ^5.0.0
  fule_scaffold: ^0.1.1
  sembast: ^3.1.0+2
  flutter_datetime_picker: ^1.5.1
  stacked: ^2.2.3
  kiwi: ^3.0.0
  shared_preferences: ^2.0.6
  openapi_generator_annotations: ^1.1.4
  get_storage: ^2.0.3
  get: ^4.3.8
  jwt_decoder: ^2.0.1
  fluttertoast: ^8.0.8
  open_file: ^3.2.1
  path_provider: ^2.0.3
  local_auth: ^1.1.7
  package_info_plus: ^1.0.6
  device_info_plus: ^3.0.1
  super_easy_permissions: ^0.1.1
  uni_links: ^0.5.1
  after_layout: ^1.1.0
  firebase_core: ^1.7.0
  socket_io_client: ^1.0.1
  firebase_analytics: ^8.3.3
  argon_buttons_flutter: ^1.1.0
  flutter_launcher_icons: "^0.9.2"
```

**Podfile:**
```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '12.3'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'Firebase/Analytics'

  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.3'
    end
  end
end

```

**Flutter doctor:**
```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en)
    • Flutter version 2.5.2 at /Users/ayazpanahov/Files/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (2 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at /Users/ayazpanahov/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.1.2
    • Dart plugin version 202.8488

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] VS Code (version 1.49.0)
    • VS Code at /Users/ayazpanahov/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • SM G975F (mobile)           • R58M352GZWD               • android-arm64  • Android 11 (API 30)
    • iPad 11 Pro M1 AIH (mobile) • 00008103-000A692236EB001E • ios            • iOS 15.0.2 19A404
    • macOS (desktop)             • macos                     • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```
