### ISSUE TITLE
[cloud_firestore/already-exists] Target ID already exists

### ISSUE THREAD

**Issue by vixez** [FirebaseExtended/flutterfire#7197]
Hello,

We are seeing `Target ID already exists` often showing up in Sentry logs, but we have no idea what causes it.
Usually it is `Target ID already exists: 2` but sometimes it can be `Target ID already exists: 12` as well.

I'm not sure if this happens on mobile, judging from the Sentry logs it's only on web.

This is the stack I find in Sentry:
```
org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart in throwExpression at line 1111:37
org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart in guard.<anonymous function> at line 1142:25
… evelopment/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.6.0/lib/src/internals.dart in _invokeErrorHandler at line 101:18
org-dartlang-sdk:///lib/async/async_error.dart in _HandleErrorStream._handleError at line 45:12
org-dartlang-sdk:///lib/async/stream_pipe.dart in _ForwardingStreamSubscription._handleError at line 269:9
org-dartlang-sdk:///lib/async/stream_pipe.dart in Closure.forwardCallTo at line 157:5
org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart in _rootRunBinary at line 2172:5
org-dartlang-sdk:///lib/async/zone.dart in _rootRunBinary[function-entry$6] at line 1452:46
org-dartlang-sdk:///lib/async/zone.dart in _CustomZone.runBinary at line 1450:3
org-dartlang-sdk:///lib/async/zone.dart in aFh.Up at line 1341:34
```

**Comment by darshankawar** [comment]
@vixez 
Can you provide `flutter doctor -v` and `pubspec.yaml` ?
Thanks.

**Comment by vixez** [comment]
```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.5.2 at /Users/glennruysschaert/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • GM1913 (mobile) • 2b00d10b • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 94.0.4606.81

• No issues found!

```


```
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  platform_info: ^3.1.0
  device_info_plus: ^2.0.1
  platform_detect2: ^1.4.0
  firebase_core: ^1.0.4
  cloud_firestore: ^2.4.0
  sentry_flutter: ^6.0.0
  pretty_json: ^2.0.0
  uuid: ^3.0.2
  ansicolor: ^2.0.1
  #cloud_firestore_mocks: 0.8.0
  universal_io: ^2.0.1
  cloud_functions: ^3.0.0
  collection: ^1.15.0
  jose: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4

flutter:
```
