### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] "Received an invalid notification content" error when clicking on notification (iOS)

### ISSUE THREAD

**Issue by benha0898** [FirebaseExtended/flutterfire#7249]
## Bug report

**Describe the bug**
I use FCM in my app for push notifications, and occasionally AwesomeNotifications for local notifications. On Android everything works great -- I can send, receive and handle all types of notifications. But in iOS, **when I click on an FCM-generated notification, it freezes at the splash screen and eventually crashes.** In debug mode, it continuously shows the error "Received an invalid notification content" and points to a line in `SwiftAwesomeNotificationsPlugin.swift`. I find that strange, since it was an FCM notification, being sent via https://fcm.googleapis.com/fcm/send, with this payload:
```
{
  "registration_ids": [
    {MY_FCM_TOKEN}
  ],
  "notification": {
  	"title": "This is a test notification",
    "body": "This is the body text"
  },
  "data": {
  	"click_action": "FLUTTER_NOTIFICATION_CLICK",
    "type": "CANCELED_SHOW"
  }
}
```

This is similar to [FirebaseExtended/flutterfire/issues/7243](https://github.com/FirebaseExtended/flutterfire/issues/7243), except I wasn't trying to use AwesomeNotifications in this use case at all.

I've tried;

- Adding `"content_available": true`
- Using APNS token instead of FCM token
- Not initializing AwesomeNotifications at the beginning

### Steps to reproduce

1. Initialize FirebaseMessaging and AwesomeNotifications at the beginning of the app
2. Put the app in the background
3. Send a push notification request using the link above (you can use the same payload too)
4. Watch it crash and burn

### Expected behavior

Clicking on an FCM notification should trigger the `onMessageOpenedApp` event, where I handle all background notifications (e.g. go to a new screen).

---

### Flutter doctor

<details><summary>Doctor Summary</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.1 20C69 darwin-x64, locale en-CA)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.57.1)
[✓] Connected device (1 available)
```

</details>

---

### Flutter dependencies

<details><summary>pubspec.yaml</summary>

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^4.0.6
  agora_rtm: ^1.0.0
  audioplayers: ^0.19.1
  awesome_notifications: ^0.0.6+10
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.3.0
  device_info_plus: ^2.1.0
  enum_to_string: ^2.0.1
  firebase_analytics: ^8.1.2
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.7
  firebase_dynamic_links: ^2.0.6
  firebase_messaging: ^10.0.4
  firebase_storage: ^10.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_libphonenumber: ^1.1.0
  flutter_native_splash: ^1.1.5+1
  get: ^4.3.4
  google_fonts: ^2.1.0
  http: ^0.13.3
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  json_annotation: null
  package_info_plus: ^1.3.0
  page_transition: ^2.0.2
  permission_handler: ^8.1.2
  provider: ^5.0.0
  rainbow_color: ^2.0.1
  share: ^2.0.4
  shared_preferences: ^2.0.6
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.12
  wakelock: ^0.5.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#40139b"
  image: "assets/logo.png"

dev_dependencies:
  build_runner: ^1.10.11
  flutter_test:
    sdk: flutter
  json_serializable: null
  dependency_validator: ^3.1.0
```
</details>

- Device: iPhone 11, iOS 15
- Flutter SDK: 2.5.3
- Dart SDK: 2.14.4

---

### Relevant Code

<details><summary>main()</summary>

```
Future<void> main() async {
  runZonedGuarded<Future<void>>(() async {
    WidgetsFlutterBinding.ensureInitialized();
    AwesomeNotifications().initialize(
      'resource://drawable/res_notification_app_icon',
      [
        NotificationChannel(
          channelKey: 'basic_channel',
          channelName: 'Basic Notifications',
          defaultColor: MyTheme.purple,
          importance: NotificationImportance.High,
          channelShowBadge: false,
          playSound: true,
        ),
        NotificationChannel(
          channelKey: 'scheduled_channel',
          channelName: 'Scheduled Notifications',
          defaultColor: MyTheme.purple,
          importance: NotificationImportance.High,
          channelShowBadge: false,
          playSound: true,
        ),
      ],
    ).then((value) {
      print("AwesomeNotifications initialized: $value");
      if (Platform.isIOS)
        AwesomeNotifications().getGlobalBadgeCounter().then((value) {
          if (value > 0) {
            AwesomeNotifications().setGlobalBadgeCounter(0);
          }
        });
    });

    await Firebase.initializeApp();

    await FirebaseMessaging.instance.requestPermission();

    FirebaseCrashlytics.instance.setUserIdentifier(deviceId);
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
    if (kDebugMode) {
      await FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);
    }

    runApp(MyApp());
  }, (error, stack) => FirebaseCrashlytics.instance.recordError(error, stack));
}
```

</details>

<details><summary>Initialize FirebaseMessaging</summary>

```
Future _initFCM() async {
    PermissionStatus status = await Permission.notification.request();
    print("FCM Status: $status");
    if (status.isPermanentlyDenied) {
      openAppSettings();
    } else if (!status.isDenied) {
      print(
          "Initialize FCM. Listen to background messages. Get initial message");
      final _firebaseMessaging = FirebaseMessaging.instance;
      final PushNotificationService pushNotificationService =
          PushNotificationService();
      await pushNotificationService.initialize(_firebaseMessaging);

      FirebaseMessaging.onBackgroundMessage(notificationMessageHandler);

      // Try to get initial notification message if there's any
      RemoteMessage? initialMessage =
          await _firebaseMessaging.getInitialMessage();
      if (initialMessage != null) {
        final PushNotificationMessage notification = PushNotificationMessage(
          title: initialMessage.notification!.title,
          body: initialMessage.notification!.body,
          data: initialMessage.data,
        );
        print("Received initial message: $notification.");
        await pushNotificationService.handleNotification(notification);
      }
    }
  }
```

</details>

<details><summary>PushNotificationService.initialize()</summary>

```
Future initialize(FirebaseMessaging fcm) async {
    // Get FCM token
    String? token = await fcm.getToken();
    String? apnsToken = await fcm.getAPNSToken();

    // Listen for new FCM tokens
    fcm.onTokenRefresh.listen((String newToken) {
      print("New FirebaseMessaging token: $newToken");
    });

    // Receiving notification while app is open
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      final PushNotificationMessage notification = PushNotificationMessage(
        title: message.notification!.title,
        body: message.notification!.body,
        data: message.data,
      );
      print("OnMessage (foreground notification): $notification.");
    });

    // When user clicks on a notification (when app is not terminated)
    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      final PushNotificationMessage notification = PushNotificationMessage(
        title: message.notification!.title,
        body: message.notification!.body,
        data: message.data,
      );
      print("OnMessageOpenedApp: $notification.");
      handleNotification(notification);
    });

    AwesomeNotifications().createdStream.listen((ReceivedNotification notification) {
      print("A ${notification.channelKey} notification was created.");
    });

    AwesomeNotifications().actionStream.listen((ReceivedAction action) async {
      if (action.channelKey == 'basic_channel' && Platform.isIOS) {
        AwesomeNotifications().getGlobalBadgeCounter().then((value) {
          AwesomeNotifications().setGlobalBadgeCounter(value - 1);
        });
      }
      print(
          "A ${action.channelKey} notification action was made: ${action.buttonKeyPressed}");

      if (action.payload != null) {
        final PushNotificationMessage notification = PushNotificationMessage(
            title: action.title, body: action.body, data: action.payload!);
        handleNotification(notification);
      }
    });

    AwesomeNotifications().dismissedStream.listen((ReceivedAction action) {
      if (action.channelKey == 'basic_channel' && Platform.isIOS) {
        AwesomeNotifications().getGlobalBadgeCounter().then((value) {
          AwesomeNotifications().setGlobalBadgeCounter(value - 1);
        });
      }
      print("A ${action.channelKey} notification action was dismissed");
    });
  }
```

</details>

![image](https://user-images.githubusercontent.com/35279550/139010601-704c8944-e75d-4f87-9708-3bf552c370fe.png)
![image](https://user-images.githubusercontent.com/35279550/139010638-6574acef-8c24-4513-adc6-76cf2f802f9e.png)
