### ISSUE TITLE
🐛 [firebase_messaging] Error building with XCode (GULAppEnvironmentUtil)

### ISSUE THREAD

**Issue by mrcsilva** [FirebaseExtended/flutterfire#7748]
## Bug report

**Describe the bug**
After adding the dependency for firebase_messaging iOS stopped building and returns the following error:
```
In module 'GoogleUtilities' imported from /Users/mario/Desktop/shareio/ios/Pods/FirebaseMessaging/
FirebaseMessaging/Sources/FIRMessagingUtilities.m:20:

/Users/mario/Desktop/shareio/ios/Pods/GoogleUtilities/GoogleUtilities/
Environment/Public/GoogleUtilities/GULAppEnvironmentUtil.h:21:12: note: definition here is not reachable
    @interface GULAppEnvironmentUtil : NSObject
```

---

## Additional context

pubspec.yaml

<details><summary>Click To Expand</summary>

```
name: shareio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.8.1
  crypto: ^3.0.1
  provider: ^6.0.2
  file_picker: ^4.3.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  async: ^2.8.2
  worker_manager: ^4.2.4
  app_tracking_transparency: ^2.0.2+1
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.2.0
  firebase_crashlytics: ^2.4.4
  firebase_performance: ^0.8.0+3
  firebase_analytics: ^9.0.4
  firebase_remote_config: ^1.0.3
  google_mobile_ads: ^1.0.1
  shared_preferences: ^2.0.11
  purchases_flutter: ^3.8.0
  webview_flutter: ^3.0.0
  ionicons: ^0.1.2
  intl: ^0.17.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/icon.png

```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
[✓] VS Code (version 1.63.0)
[✓] Connected device (3 available)
    ! Error: Mário’s iPhone is busy: Fetching debug symbols for Mário’s iPhone. Xcode will continue when Mário’s iPhone is finished. (code -10)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.15.1
Flutter SDK 2.8.1
shareio 1.0.0+1

dependencies:
- app_tracking_transparency 2.0.2+1 [flutter]
- async 2.8.2 [collection meta]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.4
- file_picker 4.3.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path]
- firebase_analytics 9.0.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.10.6 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.4.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 11.2.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.8.0+3 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 1.0.3 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_local_notifications 9.2.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_webrtc 0.8.1 [dart_webrtc flutter path_provider webrtc_interface]
- google_mobile_ads 1.0.1 [meta flutter]
- intl 0.17.0 [clock path]
- ionicons 0.1.2 [flutter]
- path_provider 2.0.8 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 8.3.0 [flutter meta permission_handler_platform_interface]
- provider 6.0.2 [collection flutter nested]
- purchases_flutter 3.8.0 [flutter collection]
- shared_preferences 2.0.11 [flutter meta shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- webview_flutter 3.0.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- worker_manager 4.2.5 [async collection]

dev dependencies:
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_launcher_icons 0.9.2 [args image path yaml]

transitive dependencies:
- archive 3.1.6 [crypto path]
- args 2.3.0
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- dart_webrtc 1.0.3 [webrtc_interface]
- dbus 0.6.6 [args ffi meta xml]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics_platform_interface 3.0.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+4 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.11 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.5 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.1.0+3 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.0+3 [firebase firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- firebase_remote_config_platform_interface 1.0.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.0.3 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- flutter_local_notifications_linux 0.4.1+1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.0 [archive meta xml]
- js 0.6.3
- meta 1.7.0
- nested 1.0.0 [flutter]
- path 1.8.1
- path_provider_android 2.0.11 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.4 [ffi flutter meta path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.4 [flutter meta path_provider_platform_interface]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.4 [ffi flutter meta path path_provider_platform_interface win32]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.0.2 [meta]
- process 4.2.4 [file path platform]
- shared_preferences_android 2.0.9 [flutter meta shared_preferences_platform_interface]
- shared_preferences_ios 2.0.8 [flutter meta shared_preferences_platform_interface]
- shared_preferences_linux 2.0.3 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.3 [file flutter meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- timezone 0.8.0 [path]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
- webrtc_interface 1.0.1
- webview_flutter_android 2.8.2 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.8.0 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.7.1 [flutter webview_flutter_platform_interface]
- win32 2.3.3 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---
