### ISSUE TITLE
🐛 [dynamic_link] Android App installed from dynamic link doesn't take user to the right screen

### ISSUE THREAD

**Issue by khaiql** [FirebaseExtended/flutterfire#7800]
## Bug report

Similar to this bug https://github.com/FirebaseExtended/flutterfire/issues/1861, but it happens to Android. When a user clicks on the dynamic link without the app installed, the user is taken to Play store to install. However, ~50% of the time (I test this myself) the initial link is not detected and the app does not take the user to the desired screen. 

My code to handle the link: 

```dart
  Future<void> _initDynamicLinks() async {
    // Adding a little delay to address problem when initial link could be null
    // https://betterprogramming.pub/deep-linking-in-flutter-with-firebase-dynamic-links-8a4b1981e1eb
    final delayMs = RemoteConfigService.instance
        .getInt(RemoteConfigService.initDynamicLinkDelayMs);
    await Future.delayed(Duration(milliseconds: delayMs));
    final data = await FirebaseDynamicLinks.instance.getInitialLink();
    final deepLink = data?.link;

    if (deepLink != null) {
      _handleDeepLinkRoute(deepLink);
    }

    FirebaseDynamicLinks.instance.onLink.listen((dynamicLink) {
      final deepLink = dynamicLink.link;
      _handleDeepLinkRoute(deepLink);
    });
  }
```

Notice my comment about adding the small delays, I tried that but it didn't help. 

### Steps to reproduce

1. Open the dynamic link without the app installed
2. If it works, uninstall the app and click on the link again
4. See the app doesn't open the right screen

### Expected behavior

The initial link should be recognized and handled properly

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  provider: ^6.0.1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  form_field_validator: ^1.1.0
  firebase_core: ^1.2.0
  firebase_auth: ^3.0.1
  firebase_messaging: ^11.1.0
  firebase_dynamic_links: ^4.0.2
  firebase_analytics: ^9.0.3
  firebase_crashlytics: ^2.0.5
  firebase_remote_config: ^1.0.2
  firebase_storage: ^10.2.4
  firebase_app_installations: ^0.1.0+4
  firebase_performance: ^0.8.0+3
  cloud_firestore: ^3.1.0
  phone_number: ^0.12.0+1
  google_sign_in: ^5.0.2
  graphql_flutter: ^5.0.0
```

</details>

---
