### ISSUE TITLE
🐛 [cloud_firestore] cloud firestore is not working with minifyenabled true and shrinkResources true

### ISSUE THREAD

**Issue by anujsaxenadev** [FirebaseExtended/flutterfire#8176]
## Bug report

**Describe the bug**
cloud_firestore is not working with minifyenabled true and shrinkResources true in android gradle. When i am accessing the cloud_firestore i am getting a crash. There is one issue that is exactly the same as this one - https://github.com/FirebaseExtended/flutterfire/issues/7406
But issue 7406 is closed and I think disabling minifyenabled and shrinkResources for release is not the right call. so i am opening this issue.

### Expected behavior

With minifyenabled and shrinkResources the app should not crash with cloud_firestore. In my pubspec.lock i am using 

cloud_firestore version - 2.5.4
firebase_auth version - 3.3.7
firebase_core version - 1.12.0

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.5.0, on macOS 11.3 20E232 darwin-x64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (1 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
  get_it: ^7.2.0
  provider: ^5.0.0
  super_tooltip: ^1.0.1
  flutter_inappwebview: ^5.3.2
  pin_code_fields: ^7.3.0
  dropdown_below: ^1.0.2
  fluro: ^2.0.3
  fluttertoast: ^8.0.8
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.6
  environment_config: ^3.0.0
  flutter_config: ^2.0.0
  uni_links: ^0.5.1
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5
  flutter_local_notifications: ^9.3.2
  firebase_crashlytics: ^2.2.1
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  collection: ^1.15.0
  property_change_notifier: ^0.3.0
  photo_manager: ^1.3.7
  image_picker: ^0.8.4+2
  camera: 0.9.4+11
  permission_handler: 8.1.6
  cloud_firestore: ^2.5.4
  flutter_html: ^2.1.5
  url_launcher: ^6.0.12
  modal_bottom_sheet: ^2.0.0
  flutter_holo_date_picker: ^1.0.1+2
  fl_chart: ^0.40.2
  flutter_downloader: ^1.7.1
  path_provider: ^2.0.8
  shimmer: ^2.0.0
  device_info_plus: ^3.2.0
  firebase_auth: ^3.3.4
  share_plus: 3.0.4
  external_path: ^1.0.1
  lottie: ^1.2.2
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  http_mock_adapter: ^0.2.1
  build_runner: ^2.0.4
  fake_cloud_firestore: ^1.1.3
  flutter_launcher_icons: ^0.9.2
```

</details>

---
