### ISSUE TITLE
Issue with flutterfire_ui: ^0.3.5+1

### ISSUE THREAD

**Issue by KhnifesKyrillus** [FirebaseExtended/flutterfire#8189]
Hello,

I have cant run the flutterfire package I always get this error:

```
The class is loaded from C:/Users/khnif/.gradle/caches/transforms-2/files-2.1/4140f7cd8ea831b99a52f8a19075d10f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: C:\Users\khnif\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\sign_in_with_apple-3.3.0\android\src\main\kotlin\com\aboutyou\dart_packages\sign_in_with_apple\SignInWithApplePlugin.kt: (174, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from C:/Users/khnif/.gradle/caches/transforms-2/files-2.1/4140f7cd8ea831b99a52f8a19075d10f/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sign_in_with_apple:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s

┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                       │
│ Find the latest version on https://kotlinlang.org/docs/gradle.html#plugin-and-versions, then │
│ update C:\Users\khnif\OneDrive\Documents\PUMP\pump_app\android\build.gradle:                 │
│ ext.kotlin_version = '<latest-version>'                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1
```

Firebase is initialized correctly and I don't know what's wrong.

Here my pubspec.yaml:
```
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.1
  json_annotation: ^4.1.0
  youtube_player_flutter: ^8.0.0
  get_it: ^7.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_secure_storage: ^5.0.2
  flutter_tags_x: ^1.0.0
  carousel_slider: ^4.0.0
  mutex: ^3.0.0
  uuid: ^3.0.5
  confetti: ^0.6.0
  flutter_emoji: ^2.2.1+1
  material_floating_search_bar: ^0.3.6
  file_picker: ^4.2.7
  infinite_scroll_pagination: ^3.1.0
  im_stepper: ^0.1.3
  horizontal_blocked_scroll_physics: ^4.0.0
  auto_size_text: ^3.0.0
  onboarding: ^2.1.0
  sliding_up_panel: ^2.0.0+1

  flex_color_scheme: ^4.2.0

  #navigation
  beamer: ^1.1.0

  #hive
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  #ferry
  ferry: ^0.10.4
  gql_http_link: ^0.4.0
  ferry_hive_store: ^0.4.4
  gql_build: ^0.2.0
  built_collection: ^5.1.1
  ferry_flutter: ^0.5.4

  #firebase
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  firebase_crashlytics: ^2.4.3
  firebase_analytics: ^9.0.3
  flutterfire_ui: ^0.3.5+1
  firebase_dynamic_links: ^4.0.3
  google_sign_in: ^5.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon.jpg"



dev_dependencies:
  build_runner: ^2.1.1
  ferry_generator: ^0.4.4
  flutter_test:
    sdk: flutter

```
